In [ ]:
!pip install requests pandas

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import getpass

API_KEY = getpass.getpass("Enter your SerpApi API key: ")

Enter your SerpApi API key: ··········

In [ ]:
import requests
import pandas as pd
import getpass
import time

# ============================================================
# 1. CONFIGURATION
# ============================================================

API_KEY = getpass.getpass("Enter your SerpApi API key: ")

CITY = "Chennai"
STATE = "Tamil Nadu"
COUNTRY_CODE = "in"

# Google Hotels requires stay dates.
CHECK_IN = "2026-10-15"
CHECK_OUT = "2026-10-16"

# Collect up to 1000 unique hotels
TARGET_HOTELS = 1000

# Maximum number of review pages per hotel
MAX_REVIEW_PAGES = 3

OUTPUT_FILE = "chennai_hotel_dataset.csv"
BASE_URL = "https://serpapi.com/search.json"

# Search multiple areas to increase hotel coverage.
AREAS = [
    "Central Chennai",
    "T Nagar",
    "Nungambakkam",
    "Anna Nagar",
    "Adyar",
    "Besant Nagar",
    "Velachery",
    "Guindy",
    "OMR",
    "Sholinganallur",
    "Perungudi",
    "Thoraipakkam",
    "ECR",
    "Mylapore",
    "Alwarpet",
    "Royapettah",
    "Egmore",
    "Kilpauk",
    "Porur",
    "Vadapalani",
    "Koyambedu",
    "Chromepet",
    "Pallavaram",
    "Tambaram",
    "Guindy",
    "Mount Road",
    "Chennai Airport",
    "Perambur",
    "Ambattur",
    "Madhavaram",
    "Washermanpet",
    "Triplicane",
    "Royapuram",
    "Alandur",
    "Saidapet",
    "Kodambakkam",
    "Ashok Nagar",
    "KK Nagar",
    "Purasawalkam",
    "Chetpet",
    "Shenoy Nagar",
    "RA Puram",
    "Thiruvanmiyur",
    "Neelankarai",
    "Kottivakkam",
    "Medavakkam",
    "Pallikaranai",
    "Madipakkam"
]

# ============================================================
# 2. HELPER FUNCTIONS
# ============================================================

def safe_request(params):
    params = params.copy()
    params["api_key"] = API_KEY

    try:
        response = requests.get(
            BASE_URL,
            params=params,
            timeout=60
        )

        if response.status_code != 200:
            print("API error:", response.status_code)
            print(response.text[:300])
            return {}

        data = response.json()

        if "error" in data:
            print("API error:", data["error"])
            return {}

        return data

    except requests.RequestException as e:
        print("Request failed:", e)
        return {}


def extract_price(hotel):
    rate = hotel.get("rate_per_night", {})

    if isinstance(rate, dict):
        return (
            rate.get("extracted_lowest")
            or rate.get("extracted_before_taxes_fees")
            or rate.get("lowest")
            or rate.get("before_taxes_fees")
        )

    return rate if isinstance(rate, (int, float)) else None


def extract_amenities(hotel):
    amenities = hotel.get("amenities", [])

    if isinstance(amenities, list):
        names = []

        for item in amenities:
            if isinstance(item, dict):
                name = item.get("name") or item.get("title")

                if name:
                    names.append(str(name))
            else:
                names.append(str(item))

        return " | ".join(names)

    return str(amenities) if amenities else None


def extract_location(hotel):
    address = hotel.get("address")

    if address:
        return address

    gps = hotel.get("gps_coordinates", {})

    if isinstance(gps, dict):
        lat = gps.get("latitude")
        lon = gps.get("longitude")

        if lat is not None and lon is not None:
            return f"Latitude: {lat}, Longitude: {lon}"

    return None


def extract_review_text(review):

    for key in ("snippet", "text"):

        value = review.get(key)

        if isinstance(value, str) and value.strip():
            return value.strip()

    return None


def extract_review_rating(review):

    rating = review.get("rating")

    if isinstance(rating, dict):
        return (
            rating.get("value")
            or rating.get("rating")
        )

    return rating


def make_hotel_row(hotel, area):

    return {
        "hotel_name": hotel.get("name"),

        "hotel_id": hotel.get("property_token"),

        "city": CITY,

        "location": extract_location(hotel),

        "price_per_night": extract_price(hotel),

        "hotel_category": hotel.get("hotel_class"),

        "customer_rating": hotel.get("overall_rating"),

        "review_count": hotel.get("reviews"),

        "amenities": extract_amenities(hotel),

        "search_area": area
    }


# ============================================================
# 3. SEARCH HOTELS ACROSS CHENNAI
# ============================================================

hotels_by_id = {}

for area in AREAS:

    if len(hotels_by_id) >= TARGET_HOTELS:
        break

    print(f"\nSearching: Hotels in {area}, {CITY}")

    next_page_token = None

    while len(hotels_by_id) < TARGET_HOTELS:

        params = {
            "engine": "google_hotels",

            "q": f"Hotels in {area}, {CITY}",

            "gl": COUNTRY_CODE,

            "hl": "en",

            "currency": "INR",

            "check_in_date": CHECK_IN,

            "check_out_date": CHECK_OUT
        }

        if next_page_token:

            params["next_page_token"] = next_page_token

        data = safe_request(params)

        if not data:
            break

        properties = data.get("properties", [])

        if not properties:
            break

        for hotel in properties:

            hotel_id = hotel.get("property_token")

            if not hotel_id:
                continue

            # Keep only one record per unique hotel.
            if hotel_id not in hotels_by_id:

                hotels_by_id[hotel_id] = {
                    **make_hotel_row(hotel, area),

                    "_raw_hotel": hotel
                }

            if len(hotels_by_id) >= TARGET_HOTELS:
                break

        print(
            "Unique Chennai hotels collected:",
            len(hotels_by_id)
        )

        next_page_token = (
            data.get("serpapi_pagination", {})
            .get("next_page_token")
        )

        if not next_page_token:
            break

        time.sleep(1)

    if len(hotels_by_id) >= TARGET_HOTELS:
        break


print("\n========================================")
print("Unique Chennai hotels collected:",
      len(hotels_by_id))
print("========================================")


# ============================================================
# 4. FETCH REVIEWS FOR EACH HOTEL
# ============================================================

all_rows = []

skipped_reviews = 0

hotel_items = list(hotels_by_id.values())


for hotel_num, hotel_data in enumerate(
    hotel_items,
    start=1
):

    hotel = hotel_data["_raw_hotel"]

    hotel_id = hotel.get("property_token")

    print(
        f"\n[{hotel_num}/{len(hotel_items)}] "
        f"{hotel.get('name')}"
    )

    hotel_details = {
        key: value
        for key, value in hotel_data.items()
        if key != "_raw_hotel"
    }

    next_review_token = None

    review_pages = 0

    valid_reviews = 0

    while review_pages < MAX_REVIEW_PAGES:

        params = {

            "engine": "google_hotels_reviews",

            "property_token": hotel_id,

            "hl": "en",

            "sort_by": 2
        }

        if next_review_token:

            params["next_page_token"] = (
                next_review_token
            )

        review_data = safe_request(params)

        if not review_data:
            break

        reviews = review_data.get(
            "reviews",
            []
        )

        if not reviews:
            break

        review_pages += 1

        for review in reviews:

            review_text = extract_review_text(
                review
            )

            if not review_text:

                skipped_reviews += 1

                continue

            row = hotel_details.copy()

            row.update({

                "review_text":
                    review_text,

                "individual_review_rating":
                    extract_review_rating(review),

                "review_date":
                    review.get("date"),

                "review_source":
                    review.get("source")
            })

            all_rows.append(row)

            valid_reviews += 1

        next_review_token = (
            review_data
            .get("serpapi_pagination", {})
            .get("next_page_token")
        )

        if not next_review_token:
            break

        time.sleep(1)

    print(
        "Reviews with text:",
        valid_reviews
    )

    time.sleep(1)


# ============================================================
# 5. SAVE THE COMBINED DATASET
# ============================================================

columns = [

    "hotel_name",

    "hotel_id",

    "city",

    "location",

    "price_per_night",

    "hotel_category",

    "customer_rating",

    "review_count",

    "amenities",

    "review_text",

    "individual_review_rating",

    "review_date",

    "review_source",

    "search_area"
]


df = pd.DataFrame(
    all_rows,
    columns=columns
)


if not df.empty:

    # Remove rows without review text.

    df = df[
        df["review_text"].notna()
        &
        df["review_text"]
        .astype(str)
        .str.strip()
        .ne("")
    ].copy()

    # Remove exact duplicate rows.

    df.drop_duplicates(
        inplace=True
    )


# ============================================================
# 6. SAVE CSV
# ============================================================

df.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"
)


# ============================================================
# 7. FINAL SUMMARY
# ============================================================

print("\n")
print("==============================================")
print("       CHENNAI HOTEL DATASET SUMMARY")
print("==============================================")

print(
    "Target hotels:",
    TARGET_HOTELS
)

print(
    "Unique hotels found:",
    len(hotels_by_id)
)

print(
    "Hotels with text-bearing reviews:",
    df["hotel_id"].nunique()
    if not df.empty
    else 0
)

print(
    "Review rows saved:",
    len(df)
)

print(
    "Reviews skipped for empty text:",
    skipped_reviews
)

print(
    "CSV saved:",
    OUTPUT_FILE
)

print("==============================================")


display(
    df.head(10)
)

Streaming output truncated to the last 5000 lines.
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[289/1000] KLR GUEST HOUSE
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[290/1000] Hotel O by OYO Tnagar Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[291/1000] OYO 12236 The Pearl
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[292/1000] Hotel O Golden Tower
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[293/1000] Metro Palace
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[294/1000] Kuber Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[295/1000] Hotel Swagath
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[296/1000] Kings Hotel - Egmore
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[297/1000] OYO 67922 Temple Tree Gust House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[298/1000] FabExpress Shree Shylee Niwas
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[299/1000] Nimalan Residency Arumbakkam
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[300/1000] Rudhra service Apartments
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[301/1000] Kashvis Mayura Sirur Home
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[302/1000] FabHotel Apple Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[303/1000] OYO Amrita Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[304/1000] The view signature studio
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[305/1000] G Silver Ashok Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[306/1000] OYO Angson Apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[307/1000] Mr.White Prime Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[308/1000] The White House Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[309/1000] GreenLand Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[310/1000] OYO Flagship 6339 Anna Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[311/1000] ARADHANA HOME STAY
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[312/1000] Rini Resort
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[313/1000] Capital O 64612 SSR Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[314/1000] Arul Chettinadu Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[315/1000] FabHotel MGR House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[316/1000] Collection O 39440 Alreef Residency Vadapalani
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[317/1000] Smart Stay
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[318/1000] Pebbles Serviced Apartments - Executive Double Room
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[319/1000] Capital O 78164 Akshaya Business Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[320/1000] Hotel Campus
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[321/1000] Collection O 75820 Madras Metro Club, T Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[322/1000] Chellam Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[323/1000] OYO Flagship 486 Nungambakkam - Greams road
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[324/1000] Live on CHN1514
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[325/1000] Faazil Mansion
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[326/1000] Golden Fruits Business Suites - Standard Double Room
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[327/1000] ISHKA INN
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[328/1000] OYO 13424 Hotel Anushka
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[329/1000] Sun Palace
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[330/1000] Eco Stay T Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[331/1000] Tharif Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[332/1000] Le Stay inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[333/1000] OYO Rich Manor
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[334/1000] Collection O 2527 Lake View Park
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[335/1000] OYO 41949 Kjr Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[336/1000] Shri Ganesh Bhavan
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[337/1000] OYO 67737 Happy Rooms
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[338/1000] Collection O 5446 Hotel Maharajay
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[339/1000] SPOT ON 45468 Kumarans Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[340/1000] Collection O Sai Lakshmi Nivas Service Apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[341/1000] samrat sorrento guest house
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[342/1000] Collection O Bkr Grand Hotel Near Ags Cinemas T Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[343/1000] Chennai Palace
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[344/1000] SANSKRITII
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[345/1000] Townhouse Majestic Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[346/1000] Flagship Vadapalani Near Pvr Spi Palazzo Chennai
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[347/1000] Hotel O by OYO Dream Palace Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[348/1000] Balamurugan Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[349/1000] SilverKey Executive Stays 20006 T Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[350/1000] Collection O 13006 Pleasant Stays
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[351/1000] OYO Flagship 468 T Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[352/1000] Sukrithi Premium Serviced Apartment - F2 - Two-Bedroom Apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[353/1000] Jasmine park - Executive Deluxe Double Room
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[354/1000] Hotel O By OYO Jagadha Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[355/1000] ChennaiStayz
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[356/1000] Meriton Paying Guest for Men
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[357/1000] Capital O Emarald Hotel Near Albert Theatres
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[358/1000] OYO Flagship Flagship Vadapalani
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[359/1000] Hotel Sri Raghavendra
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[360/1000] GRAND TOWER
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[361/1000] Xavier Rajan Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[362/1000] OYO 80042 Collection O Innside Serviced Appartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[363/1000] OYO 19488 Sivaraj Homes
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[364/1000] Gem Palace
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[365/1000] Villa Ithaka by Youkoso - Standard Queen Room
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[366/1000] Angson serviced apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[367/1000] FabHotel La Mint
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[368/1000] OYO Hotel 6148 Green Grande Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[369/1000] Hotel Surya
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[370/1000] OYO 73855 Golden Stays
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[371/1000] Hotel Sribaas Kences Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[372/1000] Sri BKM Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[373/1000] Collection O 85873 ORGO Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[374/1000] Flagship Shree Shylee's Niwas
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[375/1000] Rias Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[376/1000] AFSAN PALACE
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[377/1000] PRK RESIDENCY
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[378/1000] OYO Jr Residency Near Pvr Spi Palazzo Chennai
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[379/1000] ALEGRIA REGENCY
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[380/1000] Aloha Stays|Pink Themed|2BHK|Velachery-Chennai
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[381/1000] Maison Peach
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[382/1000] OYO 10465 PJP PARK
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[383/1000] OYO 74611 Metropark Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[384/1000] Flagship I5 Boutique Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[385/1000] Pmr Star Residences
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[386/1000] OYO 60627 SM Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[387/1000] Hotel O by OYO SHAPPY INNÂ
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[388/1000] 3star guest house
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[389/1000] OYO Rich Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[390/1000] Flagship Prince Park 2
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[391/1000] Super Hotel O Park Town Near Nehru Stadium
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[392/1000] OYO Home 35914 Comfort 1bhk Near Saligramam
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[393/1000] The Grand Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[394/1000] OYO Sunflower Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[395/1000] Sishya Hotels Service Apartment Thoraipakkam, Chennai OMR, IT Expressway - Apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[396/1000] Majestic manor
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[397/1000] OYO Flagship Grand Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[398/1000] SilverKey Executive Stays 39923 Rathinammal Colony
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[399/1000] SPOT ON 72757 Gold Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[400/1000] Hotel O REDMOON RESIDENCY SIGNATURE
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[401/1000] OYO 47679 Rich Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[402/1000] OYO Apartment Gem Parc Near Ags Cinemas T Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[403/1000] Capital O CHN1639 Pkr Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[404/1000] KS groups Corprate
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[405/1000] 3 BHK Apartment near Airport Phoenix Mall in Madipakkam
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[406/1000] Aac
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[407/1000] S4 Homes
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[408/1000] Collection O Gani Home Stay
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[409/1000] OYO 48469 Greenline Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[410/1000] OYO The Oriental Business Hotel Near Ags Cinemas T Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[411/1000] OYO 721 Panasia Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[412/1000] Flagship Kishore Inn Near Pvr Cinemas Skywalk
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[413/1000] Celebrity Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[414/1000] Alianza Stay Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[415/1000] ATLANTIC GUEST HOUSE
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[416/1000] Hotel O by OYO Tiara Grand
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[417/1000] OYO Neethu Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[418/1000] OYO Flagship 342 Anna Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[419/1000] S4 Sruthi Service Apartments - One-Bedroom Apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[420/1000] Hotel Baskar Park
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[421/1000] Senate Regency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[422/1000] OYO Flagship 11910 Shasamco International
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[423/1000] GMT TOWER GUEST HOUSE
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[424/1000] OYO Flagship 466 T Nagar Bus Terminus
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[425/1000] Collection O
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[426/1000] Madurai Sri Muniyandi Villas
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[427/1000] Hotel O by OYO The prince Park
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[428/1000] Jamal Palace
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[429/1000] ANURAG lodge
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[430/1000] AMBIKA PALACE
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[431/1000] K M Mens Hostel Mogappair West
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[432/1000] REDFOX SERVICE APARTMENT - AMBATTUR
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[433/1000] Aashi-Premium Serviced Apartments - Deluxe Double Room (2 Adults + 1 Child)
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[434/1000] GG HOMES SERVICE APARTMENTS WITH KITCHEN
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[435/1000] SRI VARI GRAND
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[436/1000] SPOT ON 40322 D D Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[437/1000] OYO 3756 Jayam Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[438/1000] OYO Flagship Redfox Hotels
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[439/1000] Hotel Amrita Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[440/1000] SPOT ON 43912 3star Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[441/1000] Ram Palace
API error: 429
{

,hotel_name,hotel_id,city,location,price_per_night,hotel_category,customer_rating,review_count,amenities,review_text,individual_review_rating,review_date,review_source,search_area
0,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Good Experience,4.0,6 days ago,Google,Central Chennai
1,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Veryy good staff very nice I highly recommend ...,5.0,6 days ago,Google,Central Chennai
2,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,The rooms are very clean and well maintained a...,5.0,a week ago,Google,Central Chennai
3,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Excellent Service & Professional Hospitality\n...,5.0,3 weeks ago,Google,Central Chennai
4,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Very nice staff and clean and neat hotel,5.0,a month ago,Google,Central Chennai
5,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,"Best service by the staff, was very much impre...",5.0,a month ago,Google,Central Chennai
6,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Good service and hotel located near by Chennai...,5.0,a month ago,Google,Central Chennai
7,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,I made this reservation with Hydel Park nearly...,1.0,2 months ago,Google,Central Chennai
8,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Rooms and washrooms were clean and the service...,5.0,2 months ago,Google,Central Chennai
9,The Hydel Park (Business Class Hotel) Chennai,ChkIqvXWlP-Y1ut1Gg0vZy8xMXJrcGRneTB5EAE,Chennai,"Latitude: 13.0819449, Longitude: 80.2704062",2828.0,None,4.7,3599,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Good experience with the hydel park,5.0,2 months ago,Google,Central Chennai

In [ ]:
from google.colab import files
files.download("chennai_hotel_dataset.csv")

In [ ]:
import requests
import pandas as pd
import getpass
import time

# ============================================================
# 1. CONFIGURATION
# ============================================================

API_KEY = getpass.getpass("Enter your SerpApi API key: ")

CITY = "Pune"
STATE = "Maharashtra"
COUNTRY_CODE = "in"

# Google Hotels requires stay dates.
CHECK_IN = "2026-10-15"
CHECK_OUT = "2026-10-16"

# Collect up to 500 unique hotels
TARGET_HOTELS = 500

# Maximum number of review pages per hotel
MAX_REVIEW_PAGES = 3

OUTPUT_FILE = "pune_hotel_dataset.csv"
BASE_URL = "https://serpapi.com/search.json"

# Search multiple areas of Pune to increase coverage.
AREAS = [
    # Central Pune
    "Central Pune",
    "Shivajinagar",
    "Deccan Gymkhana",
    "Camp",
    "Swargate",
    "Shaniwar Peth",
    "Sadashiv Peth",
    "Budhwar Peth",

    # Koregaon Park / East Pune
    "Koregaon Park",
    "Kalyani Nagar",
    "Viman Nagar",
    "Kharadi",
    "Mundhwa",
    "Magarpatta",

    # Hinjewadi / West Pune
    "Hinjewadi",
    "Wakad",
    "Baner",
    "Balewadi",
    "Aundh",
    "Pashan",
    "Bavdhan",
    "Sus",

    # South Pune
    "Katraj",
    "Kondhwa",
    "NIBM",
    "Wanowrie",
    "Hadapsar",
    "Fursungi",
    "Bibwewadi",
    "Dhankawadi",

    # North Pune
    "Kothrud",
    "Warje",
    "Bopodi",
    "Khadki",
    "Akurdi",
    "Pimpri",
    "Chinchwad",
    "Bhosari",
    "Nigdi",

    # Pune Airport / nearby
    "Pune Airport",
    "Lohegaon",
    "Dhanori",
    "Vishrantwadi",

    # Additional areas
    "Yerawada",
    "Vishal Nagar",
    "Pimple Saudagar",
    "Pimple Gurav",
    "Ravet",
    "Talegaon"
]


# ============================================================
# 2. HELPER FUNCTIONS
# ============================================================

def safe_request(params):
    params = params.copy()
    params["api_key"] = API_KEY

    try:
        response = requests.get(
            BASE_URL,
            params=params,
            timeout=60
        )

        if response.status_code != 200:
            print("API error:", response.status_code)
            print(response.text[:300])
            return {}

        data = response.json()

        if "error" in data:
            print("API error:", data["error"])
            return {}

        return data

    except requests.RequestException as e:
        print("Request failed:", e)
        return {}


def extract_price(hotel):
    rate = hotel.get("rate_per_night", {})

    if isinstance(rate, dict):
        return (
            rate.get("extracted_lowest")
            or rate.get("extracted_before_taxes_fees")
            or rate.get("lowest")
            or rate.get("before_taxes_fees")
        )

    return rate if isinstance(rate, (int, float)) else None


def extract_amenities(hotel):
    amenities = hotel.get("amenities", [])

    if isinstance(amenities, list):
        names = []

        for item in amenities:
            if isinstance(item, dict):
                name = item.get("name") or item.get("title")

                if name:
                    names.append(str(name))
            else:
                names.append(str(item))

        return " | ".join(names)

    return str(amenities) if amenities else None


def extract_location(hotel):
    address = hotel.get("address")

    if address:
        return address

    gps = hotel.get("gps_coordinates", {})

    if isinstance(gps, dict):
        lat = gps.get("latitude")
        lon = gps.get("longitude")

        if lat is not None and lon is not None:
            return f"Latitude: {lat}, Longitude: {lon}"

    return None


def extract_review_text(review):

    for key in ("snippet", "text"):

        value = review.get(key)

        if isinstance(value, str) and value.strip():
            return value.strip()

    return None


def extract_review_rating(review):

    rating = review.get("rating")

    if isinstance(rating, dict):
        return (
            rating.get("value")
            or rating.get("rating")
        )

    return rating


def make_hotel_row(hotel, area):

    return {
        "hotel_name": hotel.get("name"),

        "hotel_id": hotel.get("property_token"),

        "city": CITY,

        "location": extract_location(hotel),

        "price_per_night": extract_price(hotel),

        "hotel_category": hotel.get("hotel_class"),

        "customer_rating": hotel.get("overall_rating"),

        "review_count": hotel.get("reviews"),

        "amenities": extract_amenities(hotel),

        "search_area": area
    }


# ============================================================
# 3. SEARCH HOTELS ACROSS PUNE
# ============================================================

hotels_by_id = {}

for area in AREAS:

    if len(hotels_by_id) >= TARGET_HOTELS:
        break

    print(f"\nSearching: Hotels in {area}, {CITY}")

    next_page_token = None

    while len(hotels_by_id) < TARGET_HOTELS:

        params = {
            "engine": "google_hotels",

            "q": f"Hotels in {area}, {CITY}",

            "gl": COUNTRY_CODE,

            "hl": "en",

            "currency": "INR",

            "check_in_date": CHECK_IN,

            "check_out_date": CHECK_OUT
        }

        if next_page_token:

            params["next_page_token"] = next_page_token

        data = safe_request(params)

        if not data:
            break

        properties = data.get("properties", [])

        if not properties:
            break

        for hotel in properties:

            hotel_id = hotel.get("property_token")

            if not hotel_id:
                continue

            # Keep only one record per unique hotel.
            if hotel_id not in hotels_by_id:

                hotels_by_id[hotel_id] = {
                    **make_hotel_row(hotel, area),

                    "_raw_hotel": hotel
                }

            if len(hotels_by_id) >= TARGET_HOTELS:
                break

        print(
            "Unique Pune hotels collected:",
            len(hotels_by_id)
        )

        next_page_token = (
            data.get("serpapi_pagination", {})
            .get("next_page_token")
        )

        if not next_page_token:
            break

        time.sleep(1)

    if len(hotels_by_id) >= TARGET_HOTELS:
        break


print("\n========================================")
print(
    "Unique Pune hotels collected:",
    len(hotels_by_id)
)
print("========================================")


# ============================================================
# 4. FETCH REVIEWS FOR EACH HOTEL
# ============================================================

all_rows = []

skipped_reviews = 0

hotel_items = list(hotels_by_id.values())


for hotel_num, hotel_data in enumerate(
    hotel_items,
    start=1
):

    hotel = hotel_data["_raw_hotel"]

    hotel_id = hotel.get("property_token")

    print(
        f"\n[{hotel_num}/{len(hotel_items)}] "
        f"{hotel.get('name')}"
    )

    hotel_details = {
        key: value
        for key, value in hotel_data.items()
        if key != "_raw_hotel"
    }

    next_review_token = None

    review_pages = 0

    valid_reviews = 0

    while review_pages < MAX_REVIEW_PAGES:

        params = {

            "engine": "google_hotels_reviews",

            "property_token": hotel_id,

            "hl": "en",

            "sort_by": 2
        }

        if next_review_token:

            params["next_page_token"] = (
                next_review_token
            )

        review_data = safe_request(params)

        if not review_data:
            break

        reviews = review_data.get(
            "reviews",
            []
        )

        if not reviews:
            break

        review_pages += 1

        for review in reviews:

            review_text = extract_review_text(
                review
            )

            if not review_text:

                skipped_reviews += 1

                continue

            row = hotel_details.copy()

            row.update({

                "review_text":
                    review_text,

                "individual_review_rating":
                    extract_review_rating(review),

                "review_date":
                    review.get("date"),

                "review_source":
                    review.get("source")
            })

            all_rows.append(row)

            valid_reviews += 1

        next_review_token = (
            review_data
            .get("serpapi_pagination", {})
            .get("next_page_token")
        )

        if not next_review_token:
            break

        time.sleep(1)

    print(
        "Reviews with text:",
        valid_reviews
    )

    time.sleep(1)


# ============================================================
# 5. SAVE THE COMBINED DATASET
# ============================================================

columns = [

    "hotel_name",

    "hotel_id",

    "city",

    "location",

    "price_per_night",

    "hotel_category",

    "customer_rating",

    "review_count",

    "amenities",

    "review_text",

    "individual_review_rating",

    "review_date",

    "review_source",

    "search_area"
]


df = pd.DataFrame(
    all_rows,
    columns=columns
)


if not df.empty:

    # Remove rows without review text.

    df = df[
        df["review_text"].notna()
        &
        df["review_text"]
        .astype(str)
        .str.strip()
        .ne("")
    ].copy()

    # Remove exact duplicate rows.

    df.drop_duplicates(
        inplace=True
    )


# ============================================================
# 6. SAVE CSV
# ============================================================

df.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"
)


# ============================================================
# 7. FINAL SUMMARY
# ============================================================

print("\n")
print("==============================================")
print("        PUNE HOTEL DATASET SUMMARY")
print("==============================================")

print(
    "Target hotels:",
    TARGET_HOTELS
)

print(
    "Unique hotels found:",
    len(hotels_by_id)
)

print(
    "Hotels with text-bearing reviews:",
    df["hotel_id"].nunique()
    if not df.empty
    else 0
)

print(
    "Review rows saved:",
    len(df)
)

print(
    "Reviews skipped for empty text:",
    skipped_reviews
)

print(
    "CSV saved:",
    OUTPUT_FILE
)

print("==============================================")


display(
    df.head(10)
)

Searching: Hotels in Central Pune, Pune
Unique Pune hotels collected: 20
Unique Pune hotels collected: 37
Unique Pune hotels collected: 55
Unique Pune hotels collected: 72
Unique Pune hotels collected: 87
Unique Pune hotels collected: 101
Unique Pune hotels collected: 121
Unique Pune hotels collected: 135
Unique Pune hotels collected: 139
Unique Pune hotels collected: 151
Unique Pune hotels collected: 166

Searching: Hotels in Shivajinagar, Pune
Unique Pune hotels collected: 185
Unique Pune hotels collected: 199
Unique Pune hotels collected: 212
Unique Pune hotels collected: 225
Unique Pune hotels collected: 245
Unique Pune hotels collected: 264
Unique Pune hotels collected: 282
Unique Pune hotels collected: 292
Unique Pune hotels collected: 295

Searching: Hotels in Deccan Gymkhana, Pune
Unique Pune hotels collected: 297
Unique Pune hotels collected: 302
Unique Pune hotels collected: 308
Unique Pune hotels collected: 312
Unique Pune hotels collected: 314
Unique Pune hotels collected: 316
Unique Pune hotels collected: 320

Searching: Hotels in Camp, Pune
Unique Pune hotels collected: 333
Unique Pune hotels collected: 344
Unique Pune hotels collected: 352
Unique Pune hotels collected: 371
Unique Pune hotels collected: 385
Unique Pune hotels collected: 400
Unique Pune hotels collected: 416
Unique Pune hotels collected: 427
Unique Pune hotels collected: 428

Searching: Hotels in Swargate, Pune
Unique Pune hotels collected: 429
Unique Pune hotels collected: 434
Unique Pune hotels collected: 435
Unique Pune hotels collected: 436
Unique Pune hotels collected: 437
Unique Pune hotels collected: 438
Unique Pune hotels collected: 438
Unique Pune hotels collected: 439

Searching: Hotels in Shaniwar Peth, Pune
Unique Pune hotels collected: 439
Unique Pune hotels collected: 439
Unique Pune hotels collected: 440
Unique Pune hotels collected: 440
Unique Pune hotels collected: 440
Unique Pune hotels collected: 440

Searching: Hotels in Sadashiv Peth, Pune
Unique Pune hotels collected: 440
Unique Pune hotels collected: 443
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444

Searching: Hotels in Budhwar Peth, Pune
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444
Unique Pune hotels collected: 444

Searching: Hotels in Koregaon Park, Pune
Unique Pune hotels collected: 449
Unique Pune hotels collected: 450
Unique Pune hotels collected: 453
Unique Pune hotels collected: 464
Unique Pune hotels collected: 474
Unique Pune hotels collected: 481
Unique Pune hotels collected: 482

Searching: Hotels in Kalyani Nagar, Pune
Unique Pune hotels collected: 494
Unique Pune hotels collected: 500

========================================
Unique Pune hotels collected: 500
========================================

[1/500] The Central Park Hotel, Pune
Reviews with text: 18

[2/500] St Laurn - Koregaon Park, Pune
Reviews with text: 16

[3/500] Octave Koregaon Park
Reviews with text: 17

[4/500] Hotel Studio Estique
Reviews with text: 22

[5/500] Park Central Hotel
Reviews with text: 19

[6/500] Park Ornate Hotel
Reviews with text: 12

[7/500] Octave Bund Garden
Reviews with text: 5

[8/500] The Residency Club
Reviews with text: 7

[9/500] Treebo Serenity Inn, Koregaon Park
Reviews with text: 13

[10/500] All seasons boutique rooms
Reviews with text: 20

[11/500] Crowne Plaza Pune City Centre by IHG
Reviews with text: 15

[12/500] O Hotel Pune- Koregaon Park
Reviews with text: 19

[13/500] Itsy Hotels Prince Regency
Reviews with text: 18

[14/500] Wellesley Hotel
Reviews with text: 20

[15/500] Kapila Business Hotel
Reviews with text: 14

[16/500] Bloom Hotel - Koregaon Park
Reviews with text: 18

[17/500] Hotel Shivkrupa
Reviews with text: 15

[18/500] Hotel Madhav International Pune
Reviews with text: 15

[19/500] Amrit Guest House Pune - Family Room
Reviews with text: 8

[20/500] Mangallam Guest House - Budget Double Room
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[21/500] Bestow Inn
Reviews with text: 17

[22/500] Haven Stays
Reviews with text: 5

[23/500] The Voyage | Cafe | Hostel | Co-work
Reviews with text: 24

[24/500] Lemon Tree Premier Pune
Reviews with text: 10

[25/500] The Samrat Hotel
Reviews with text: 13

[26/500] Hotel Executive Residency
Reviews with text: 14

[27/500] Quality Inn Mint
Reviews with text: 27

[28/500] Hotel Golden Arc
Reviews with text: 10

[29/500] Jugglers Backpack
Reviews with text: 22

[30/500] Surya Villa Hotel Pune
Reviews with text: 11

[31/500] Raaha Wellness - Homes | Boutique Wellness Stay in Koregaon Park Pune
Reviews with text: 2

[32/500] The pune story
Reviews with text: 15

[33/500] FabHotel Saffron Inn I
Reviews with text: 15

[34/500] Hostells
Reviews with text: 23

[35/500] Trance Sunderban Resort
Reviews with text: 14

[36/500] Apple Tree Hospitality
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[37/500] Luxurious 2 BHK Studio Apartment
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[38/500] Hoshtel99 - Prime - Stay, Cowork and Cafe
Reviews with text: 16

[39/500] House of KP by Union Living
Reviews with text: 18

[40/500] HOSHTEL99 - LUX
Reviews with text: 19

[41/500] Vib O Stay
Reviews with text: 21

[42/500] HOTEL VRINDAVAN
Reviews with text: 10

[43/500] HOTEL DREAMLAND
Reviews with text: 19

[44/500] Amrutwa Guest House
Reviews with text: 25

[45/500] Mangallam Guest House
Reviews with text: 23

[46/500] Zen Colive
Reviews with text: 22

[47/500] Collection O by OYO Sunshine Near Inox
Reviews with text: 12

[48/500] OYO 874 Hotel Le Royce
Reviews with text: 16

[49/500] Capital O 697 The Sirona Hotel
Reviews with text: 13

[50/500] Hotel Cozy Inn
Reviews with text: 12

[51/500] Apple Tree Hospitality
Reviews with text: 11

[52/500] Hostel Off Duty
Reviews with text: 24

[53/500] Collection O Hotel Safron Inn Dole Patil Road Pune
Reviews with text: 12

[54/500] Hotel Ashirwad
Reviews with text: 16

[55/500] FULLY FURNISHED 3 BHK IN KOREGAON PARK PUNE
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[56/500] Amrit Guest House
Reviews with text: 15

[57/500] Collection O 7275 Excellent Homes
Reviews with text: 16

[58/500] Hotel Lotus
Reviews with text: 10

[59/500] MOVE INN
Reviews with text: 26

[60/500] FabHotel Sai Inn - Hotels in Koregaon Park, Pune
Reviews with text: 20

[61/500] FabHotel Executive Residency - Hotels Near Koregaon Park
Reviews with text: 6

[62/500] The Ritz-Carlton, Pune
Reviews with text: 14

[63/500] Narayan Guest House
Reviews with text: 8

[64/500] Balaji Hotel Shastri Nagar - Hotel in Yerawada
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[65/500] Sheraton Grand Pune Bund Garden Hotel
Reviews with text: 13

[66/500] OSHO International Meditation Resort
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 10

[67/500] New White House Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[68/500] OYO Hotel Srimaan Near Inox
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[69/500] Satyam Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[70/500] Urban Nomads Pune | Co-Live & Co-Work
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[71/500] Cozy 1 Bhk Fully furnished flat in Koregaon park
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[72/500] Lofty Seasons Service Apartments - Executive Room, Smoking
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[73/500] Hotel O by OYO Galaxy Near INOX
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[74/500] OYO Residency Club Pune Near Lal Mahal
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[75/500] Hotel Matoshiree
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[76/500] Bradburry's Quiet Waters - Personality Hotels
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[77/500] White flint House By One Tree Stays
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[78/500] Gandharva Residency Koregaon Park (KP)
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[79/500] Abhibha Stays (Airbnb)
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[80/500] Capital O Hotel Regency Near Lal Mahal
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[81/500] Hotel Aradhya Executive
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[82/500] Hotel Nandadeep , Tadiwala road
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[83/500] Hotel Sargam - Lodging ,Bar & Resto
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[84/500] SMART INN
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[85/500] Lofty Seasons
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[86/500] FabHotel Galaxy Koregaon Park
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[87/500] Amazing Marble Bedroom with Romantic Tub
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[88/500] Hotel Magnus Fortune House, Magarpatta
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[89/500] The Westin Pune Koregaon Park
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[90/500] Magnus Vosiv Suites, Kalyani Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[91/500] Turf Club House Restaurant
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[92/500] E-Square The Fern Pune, Series by Marriott
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[93/500] Trance Oakwood Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[94/500] Hotel Sayba International
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[95/500] FabHotel Prime Embassy
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[96/500] Habitat Inn Hospitality Services
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[97/500] Hotel Ritz
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[98/500] Hotel Sudarshan - Hotel in Pune
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[99/500] Hotel RajMahal
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[100/500] Four Points by Sheraton Hotel & Serviced Apartments, Pune
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[101/500] FabHotel Gargi Deluxe - Hotel in Shivaji Nagar, Pune
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[102/500] Laxmi Happy Home
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[103/500] Shabnam Hotel | Veg & Non-Veg | Family Restaurant & Caterers
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[104/500] Hotel Deluxe
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[105/500] OYO Flagship 79527 Kohinoor Studios
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[106/500] OYO Flagship 47178 Pakko Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[107/500] Metro Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[108/500] HOTEL KAMLESH
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[109/500] Sharan Hermitage
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[110/500] BNB hospitality
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[111/500] Flagship Sk Hospitality
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[112/500] OYO 9224 La Royle Appartments
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[113/500] Randeep Lodge
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[114/500] Hotel Chandrama
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[115/500] Royal Guest House Apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[116/500] Mathura Lodge
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[117/500] Kabila (kabila Backpackers) By WB Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[118/500] Flagship Sai Inn Near Inox
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[119/500] OYO Corporate Comfort Service Apartment Near Phoenix Marketcity - Viman Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[120/500] 1Bhk house like your home
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[121/500] The Retreat KP
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[122/500] Hotel Ambience inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[123/500] FabHotel Habitat Tingre Nagar - Hotel in Tingre Nagar, Pune
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[124/500] Hotel Sayba Executive
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[125/500] Hotel Sai Inn Executive
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[126/500] Hotel O Hotel Galaxy Stay Airport Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[127/500] FabHotel silver oak
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[128/500] COLIWO UN - Viman Nagar (Colive/Cowork/Hostel)
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[129/500] Hotel Parag
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[130/500] Hotel Chaitanya Executive
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[131/500] Hotel Sai Pavilion Lodging
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[132/500] Hotel Rutugandh Heritage
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[133/500] Via Shri Krishna
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[134/500] Hotel O by OYO Pearl Inns Executive
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[135/500] Treebo Trend Ranjeet-Hotel near deccan
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[136/500] Cozy Riverview 1Bhk House in koregaon park
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[137/500] 3Bhk Luxury Apartments in Koregaon park
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[138/500] Brand New Premium 3bhk furnished Place
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[139/500] Riverside Jacuzzi Terrace patio with safety
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[140/500] Hotel O By OYO Shree Apartments
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[141/500] FabHotel GLH Stay - Hotels in Viman Nagar, Pune
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[142/500] Hotel Sundaram Executive
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[143/500] Hotel Radiant
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[144/500] Hotel Rajdhani
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[145/500] Lakme Executive Hotel Now Managed By Rapid Hospitality
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[146/500] Golden Eagle Executive
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[147/500] Hotel Padmakrishna
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[148/500] Hotel Shivam
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[149/500] Ocean's Executive
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[150/500] Via Season Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[151/500] Ozone Guest House (Lodging)
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[152/500] Hotel Elite Stay Mahalunge
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[153/500] HOTEL TOURIST INTERNATIONAL
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[154/500] Super Hotel O by OYO Pune Kasarwadi Railway Station
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[155/500] OYO Hotel Bel Air Near Phoenix Marketcity - Viman Nagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[156/500] FabHotel Baner Executive
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[157/500] HOTEL DELUXE
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[158/500] Hotel Laxminarayan Niwas
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[159/500] Hotel Satkar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[160/500] Super Townhouse Oak by OYO Viman Nagar Downtown Formerly Hotel Cilantro
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[161/500] Hotel HMR Royal Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[162/500] FabHotel MV Galaxy
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[163/500] FabHotel Nandanvan - Hotel in Swargate, Pune
API error: 429
{

,hotel_name,hotel_id,city,location,price_per_night,hotel_category,customer_rating,review_count,amenities,review_text,individual_review_rating,review_date,review_source,search_area
0,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,Good location with peaceful surroundings. Unfo...,3,5 days ago,Google,Central Pune
1,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,Ankit singh,5,2 weeks ago,Google,Central Pune
2,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,"Hotel Feedback – Central Park, Pune||We had bo...",5,2 weeks ago,Tripadvisor,Central Pune
3,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,"Great stay, excellent staff and very clean roo...",5,2 weeks ago,Tripadvisor,Central Pune
4,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,"Great place, great food, amazing hospitality. ...",5,2 weeks ago,Tripadvisor,Central Pune
5,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,Located in city centre|Wonderful atmosphere n ...,5,3 weeks ago,Tripadvisor,Central Pune
6,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,1 great hospitality |2 very good location|3 go...,5,3 weeks ago,Tripadvisor,Central Pune
7,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,Great experience overall. The location was con...,5,3 weeks ago,Tripadvisor,Central Pune
8,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,"Location is Good, ample of parking space and e...",5,3 weeks ago,Tripadvisor,Central Pune
9,"The Central Park Hotel, Pune",ChoIveHZrrPT_bDRARoNL2cvMTFiYnJnczh3YxAB,Pune,"Latitude: 18.5271764, Longitude: 73.8785874",4588.0,4-star hotel,4.1,4693,Free breakfast | Wi-Fi | Free parking | Outdoo...,Smooth check in and out . Very courteous staff...,5,3 weeks ago,Tripadvisor,Central Pune

In [ ]:
from google.colab import files
files.download("pune_hotel_dataset.csv")

In [ ]:
import requests
import pandas as pd
import getpass
import time

# ============================================================
# 1. CONFIGURATION
# ============================================================

API_KEY = getpass.getpass("Enter your SerpApi API key: ")

CITY = "Andhra Pradesh"
STATE = "Andhra Pradesh"
COUNTRY_CODE = "in"

# Google Hotels requires stay dates.
CHECK_IN = "2026-10-15"
CHECK_OUT = "2026-10-16"

# Collect up to 500 unique hotels
TARGET_HOTELS = 500

# Maximum number of review pages per hotel
MAX_REVIEW_PAGES = 3

OUTPUT_FILE = "andhra_pradesh_hotel_dataset.csv"
BASE_URL = "https://serpapi.com/search.json"


# ============================================================
# ANDHRA PRADESH LOCATIONS
# ============================================================

AREAS = [

    # --------------------------------------------------------
    # VISAKHAPATNAM REGION
    # --------------------------------------------------------

    "Visakhapatnam",
    "Vizag",
    "Dwaraka Nagar Visakhapatnam",
    "MVP Colony Visakhapatnam",
    "Siripuram Visakhapatnam",
    "Madhurawada Visakhapatnam",
    "Gajuwaka Visakhapatnam",
    "Rushikonda Visakhapatnam",
    "Beach Road Visakhapatnam",
    "RK Beach Visakhapatnam",
    "Waltair Visakhapatnam",
    "Airport Visakhapatnam",

    # --------------------------------------------------------
    # VIJAYAWADA REGION
    # --------------------------------------------------------

    "Vijayawada",
    "Benz Circle Vijayawada",
    "Governorpet Vijayawada",
    "Moghalrajpuram Vijayawada",
    "Labbipet Vijayawada",
    "Bhavanipuram Vijayawada",
    "Poranki Vijayawada",
    "Gollapudi Vijayawada",

    # --------------------------------------------------------
    # TIRUPATI REGION
    # --------------------------------------------------------

    "Tirupati",
    "Tirumala",
    "Tiruchanur",
    "Renigunta",
    "Tirupati Railway Station",
    "Tirupati Airport",

    # --------------------------------------------------------
    # GUNTUR REGION
    # --------------------------------------------------------

    "Guntur",
    "Brodipet Guntur",
    "Arundelpet Guntur",
    "Lakshmipuram Guntur",
    "Amaravati",
    "Mangalagiri",

    # --------------------------------------------------------
    # NELLORE REGION
    # --------------------------------------------------------

    "Nellore",
    "Nellore City",
    "Magunta Layout Nellore",
    "Trunk Road Nellore",
    "Kovur",

    # --------------------------------------------------------
    # KAKINADA REGION
    # --------------------------------------------------------

    "Kakinada",
    "Kakinada Beach",
    "Sarpavaram Kakinada",
    "Jagannaickpur Kakinada",

    # --------------------------------------------------------
    # RAJAHMUNDRY REGION
    # --------------------------------------------------------

    "Rajahmundry",
    "Rajamahendravaram",
    "Danavaipeta Rajahmundry",
    "Morampudi Rajahmundry",
    "Dowleswaram",

    # --------------------------------------------------------
    # ANANTAPUR REGION
    # --------------------------------------------------------

    "Anantapur",
    "Anantapur City",
    "Rudrampeta Anantapur",

    # --------------------------------------------------------
    # KURNOOL REGION
    # --------------------------------------------------------

    "Kurnool",
    "Kurnool City",
    "Budhawarpet Kurnool",
    "Nandyal",

    # --------------------------------------------------------
    # KADAPA REGION
    # --------------------------------------------------------

    "Kadapa",
    "YSR Kadapa",
    "Proddatur",
    "Rajampet",

    # --------------------------------------------------------
    # SRIKAKULAM REGION
    # --------------------------------------------------------

    "Srikakulam",
    "Srikakulam City",
    "Arasavalli",

    # --------------------------------------------------------
    # VIZIANAGARAM REGION
    # --------------------------------------------------------

    "Vizianagaram",
    "Vizianagaram City",

    # --------------------------------------------------------
    # ELURU REGION
    # --------------------------------------------------------

    "Eluru",
    "Eluru City",

    # --------------------------------------------------------
    # MACHILIPATNAM REGION
    # --------------------------------------------------------

    "Machilipatnam",
    "Machilipatnam Beach",

    # --------------------------------------------------------
    # BHIMAVARAM REGION
    # --------------------------------------------------------

    "Bhimavaram",
    "Bhimavaram City",

    # --------------------------------------------------------
    # ONGOLE REGION
    # --------------------------------------------------------

    "Ongole",
    "Ongole City",

    # --------------------------------------------------------
    # COASTAL / TOURISM
    # --------------------------------------------------------

    "Bapatla",
    "Bapatla Beach",
    "Suryalanka Beach",
    "Chirala",
    "Vodarevu Beach",
    "Kondapalli",

    # --------------------------------------------------------
    # ARTS / HERITAGE / PILGRIMAGE
    # --------------------------------------------------------

    "Lepakshi",
    "Srisailam",
    "Ahobilam",
    "Simhachalam",
    "Araku Valley",
    "Lambasingi",
    "Papikondalu",
    "Dwaraka Tirumala"
]


# ============================================================
# 2. HELPER FUNCTIONS
# ============================================================

def safe_request(params):

    params = params.copy()
    params["api_key"] = API_KEY

    try:

        response = requests.get(
            BASE_URL,
            params=params,
            timeout=60
        )

        if response.status_code != 200:

            print(
                "API error:",
                response.status_code
            )

            print(
                response.text[:300]
            )

            return {}

        data = response.json()

        if "error" in data:

            print(
                "API error:",
                data["error"]
            )

            return {}

        return data

    except requests.RequestException as e:

        print(
            "Request failed:",
            e
        )

        return {}


def extract_price(hotel):

    rate = hotel.get(
        "rate_per_night",
        {}
    )

    if isinstance(rate, dict):

        return (

            rate.get(
                "extracted_lowest"
            )

            or

            rate.get(
                "extracted_before_taxes_fees"
            )

            or

            rate.get(
                "lowest"
            )

            or

            rate.get(
                "before_taxes_fees"
            )
        )

    return (
        rate
        if isinstance(
            rate,
            (int, float)
        )
        else None
    )


def extract_amenities(hotel):

    amenities = hotel.get(
        "amenities",
        []
    )

    if isinstance(
        amenities,
        list
    ):

        names = []

        for item in amenities:

            if isinstance(
                item,
                dict
            ):

                name = (
                    item.get("name")
                    or
                    item.get("title")
                )

                if name:

                    names.append(
                        str(name)
                    )

            else:

                names.append(
                    str(item)
                )

        return " | ".join(names)

    return (
        str(amenities)
        if amenities
        else None
    )


def extract_location(hotel):

    address = hotel.get(
        "address"
    )

    if address:

        return address

    gps = hotel.get(
        "gps_coordinates",
        {}
    )

    if isinstance(
        gps,
        dict
    ):

        lat = gps.get(
            "latitude"
        )

        lon = gps.get(
            "longitude"
        )

        if (
            lat is not None
            and
            lon is not None
        ):

            return (
                f"Latitude: {lat}, "
                f"Longitude: {lon}"
            )

    return None


def extract_review_text(review):

    for key in (
        "snippet",
        "text"
    ):

        value = review.get(
            key
        )

        if (
            isinstance(
                value,
                str
            )
            and
            value.strip()
        ):

            return value.strip()

    return None


def extract_review_rating(review):

    rating = review.get(
        "rating"
    )

    if isinstance(
        rating,
        dict
    ):

        return (
            rating.get(
                "value"
            )

            or

            rating.get(
                "rating"
            )
        )

    return rating


def make_hotel_row(
    hotel,
    area
):

    return {

        "hotel_name":
            hotel.get("name"),

        "hotel_id":
            hotel.get(
                "property_token"
            ),

        "state":
            STATE,

        "location":
            extract_location(
                hotel
            ),

        "price_per_night":
            extract_price(
                hotel
            ),

        "hotel_category":
            hotel.get(
                "hotel_class"
            ),

        "customer_rating":
            hotel.get(
                "overall_rating"
            ),

        "review_count":
            hotel.get(
                "reviews"
            ),

        "amenities":
            extract_amenities(
                hotel
            ),

        "search_area":
            area
    }


# ============================================================
# 3. SEARCH HOTELS ACROSS ANDHRA PRADESH
# ============================================================

hotels_by_id = {}


for area in AREAS:

    if (
        len(hotels_by_id)
        >= TARGET_HOTELS
    ):

        break

    print(
        f"\nSearching: Hotels in "
        f"{area}, Andhra Pradesh"
    )

    next_page_token = None


    while (
        len(hotels_by_id)
        < TARGET_HOTELS
    ):

        params = {

            "engine":
                "google_hotels",

            "q":
                f"Hotels in "
                f"{area}, Andhra Pradesh",

            "gl":
                COUNTRY_CODE,

            "hl":
                "en",

            "currency":
                "INR",

            "check_in_date":
                CHECK_IN,

            "check_out_date":
                CHECK_OUT
        }


        if next_page_token:

            params[
                "next_page_token"
            ] = next_page_token


        data = safe_request(
            params
        )


        if not data:

            break


        properties = data.get(
            "properties",
            []
        )


        if not properties:

            break


        for hotel in properties:

            hotel_id = hotel.get(
                "property_token"
            )


            if not hotel_id:

                continue


            # Keep only one record
            # per unique hotel.

            if (
                hotel_id
                not in hotels_by_id
            ):

                hotels_by_id[
                    hotel_id
                ] = {

                    **make_hotel_row(
                        hotel,
                        area
                    ),

                    "_raw_hotel":
                        hotel
                }


            if (
                len(hotels_by_id)
                >= TARGET_HOTELS
            ):

                break


        print(
            "Unique Andhra Pradesh "
            "hotels collected:",
            len(hotels_by_id)
        )


        next_page_token = (

            data
            .get(
                "serpapi_pagination",
                {}
            )
            .get(
                "next_page_token"
            )
        )


        if not next_page_token:

            break


        time.sleep(1)


    if (
        len(hotels_by_id)
        >= TARGET_HOTELS
    ):

        break


print(
    "\n========================================"
)

print(
    "Unique Andhra Pradesh hotels collected:",
    len(hotels_by_id)
)

print(
    "========================================"
)


# ============================================================
# 4. FETCH REVIEWS FOR EACH HOTEL
# ============================================================

all_rows = []

skipped_reviews = 0

hotel_items = list(
    hotels_by_id.values()
)


for hotel_num, hotel_data in enumerate(
    hotel_items,
    start=1
):

    hotel = hotel_data[
        "_raw_hotel"
    ]

    hotel_id = hotel.get(
        "property_token"
    )


    print(
        f"\n[{hotel_num}/"
        f"{len(hotel_items)}] "
        f"{hotel.get('name')}"
    )


    hotel_details = {

        key: value

        for key, value
        in hotel_data.items()

        if key != "_raw_hotel"
    }


    next_review_token = None

    review_pages = 0

    valid_reviews = 0


    while (
        review_pages
        < MAX_REVIEW_PAGES
    ):

        params = {

            "engine":
                "google_hotels_reviews",

            "property_token":
                hotel_id,

            "hl":
                "en",

            "sort_by":
                2
        }


        if next_review_token:

            params[
                "next_page_token"
            ] = next_review_token


        review_data = safe_request(
            params
        )


        if not review_data:

            break


        reviews = review_data.get(
            "reviews",
            []
        )


        if not reviews:

            break


        review_pages += 1


        for review in reviews:

            review_text = (
                extract_review_text(
                    review
                )
            )


            if not review_text:

                skipped_reviews += 1

                continue


            row = (
                hotel_details.copy()
            )


            row.update({

                "review_text":
                    review_text,

                "individual_review_rating":
                    extract_review_rating(
                        review
                    ),

                "review_date":
                    review.get(
                        "date"
                    ),

                "review_source":
                    review.get(
                        "source"
                    )
            })


            all_rows.append(
                row
            )

            valid_reviews += 1


        next_review_token = (

            review_data

            .get(
                "serpapi_pagination",
                {}
            )

            .get(
                "next_page_token"
            )
        )


        if not next_review_token:

            break


        time.sleep(1)


    print(
        "Reviews with text:",
        valid_reviews
    )


    time.sleep(1)


# ============================================================
# 5. SAVE THE COMBINED DATASET
# ============================================================

columns = [

    "hotel_name",

    "hotel_id",

    "state",

    "location",

    "price_per_night",

    "hotel_category",

    "customer_rating",

    "review_count",

    "amenities",

    "review_text",

    "individual_review_rating",

    "review_date",

    "review_source",

    "search_area"
]


df = pd.DataFrame(
    all_rows,
    columns=columns
)


if not df.empty:

    # Remove rows without review text.

    df = df[
        df["review_text"]
        .notna()

        &

        df["review_text"]
        .astype(str)
        .str.strip()
        .ne("")
    ].copy()


    # Remove exact duplicate rows.

    df.drop_duplicates(
        inplace=True
    )


# ============================================================
# 6. SAVE CSV
# ============================================================

df.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"
)


# ============================================================
# 7. FINAL SUMMARY
# ============================================================

print("\n")

print(
    "=============================================="
)

print(
    "   ANDHRA PRADESH HOTEL DATASET SUMMARY"
)

print(
    "=============================================="
)


print(
    "Target hotels:",
    TARGET_HOTELS
)


print(
    "Unique hotels found:",
    len(hotels_by_id)
)


print(
    "Hotels with text-bearing reviews:",
    df["hotel_id"].nunique()
    if not df.empty
    else 0
)


print(
    "Review rows saved:",
    len(df)
)


print(
    "Reviews skipped for empty text:",
    skipped_reviews
)


print(
    "CSV saved:",
    OUTPUT_FILE
)


print(
    "=============================================="
)


display(
    df.head(10)
)

Enter your SerpApi API key: ··········

Searching: Hotels in Visakhapatnam, Andhra Pradesh
Unique Andhra Pradesh hotels collected: 20
Unique Andhra Pradesh hotels collected: 37
Unique Andhra Pradesh hotels collected: 55
Unique Andhra Pradesh hotels collected: 65
Unique Andhra Pradesh hotels collected: 78
Unique Andhra Pradesh hotels collected: 96
Unique Andhra Pradesh hotels collected: 113
Unique Andhra Pradesh hotels collected: 129
Unique Andhra Pradesh hotels collected: 138
Unique Andhra Pradesh hotels collected: 153
Unique Andhra Pradesh hotels collected: 169
Unique Andhra Pradesh hotels collected: 185
Unique Andhra Pradesh hotels collected: 199
Unique Andhra Pradesh hotels collected: 210
Unique Andhra Pradesh hotels collected: 226
Unique Andhra Pradesh hotels collected: 238
Unique Andhra Pradesh hotels collected: 256
Unique Andhra Pradesh hotels collected: 270
Unique Andhra Pradesh hotels collected: 279
Unique Andhra Pradesh hotels collected: 291
Unique Andhra Pradesh hotels collected: 304
Unique Andhra Pradesh hotels collected: 318
Unique Andhra Pradesh hotels collected: 333
Unique Andhra Pradesh hotels collected: 344
Unique Andhra Pradesh hotels collected: 357
Unique Andhra Pradesh hotels collected: 370
Unique Andhra Pradesh hotels collected: 382
Unique Andhra Pradesh hotels collected: 394
Unique Andhra Pradesh hotels collected: 404
Unique Andhra Pradesh hotels collected: 411
Unique Andhra Pradesh hotels collected: 424
Unique Andhra Pradesh hotels collected: 436
Unique Andhra Pradesh hotels collected: 448
Unique Andhra Pradesh hotels collected: 452
Unique Andhra Pradesh hotels collected: 470
Unique Andhra Pradesh hotels collected: 488
Unique Andhra Pradesh hotels collected: 500

========================================
Unique Andhra Pradesh hotels collected: 500
========================================

[1/500] Hotel Rockdale
Reviews with text: 25

[2/500] Keys Select By Lemon Tree Hotel, Visakhapatnam
Reviews with text: 19

[3/500] THE ROYALPARK HOTEL
Reviews with text: 14

[4/500] Treebo MVP Grand
Reviews with text: 22

[5/500] OYO Hotel Lakshmi Paradise
Reviews with text: 17

[6/500] Waltair Abode
Reviews with text: 14

[7/500] Northway Hotel
Reviews with text: 11

[8/500] HOTEL TOUCHWOOD
Reviews with text: 14

[9/500] Dwaraka Inn
Reviews with text: 13

[10/500] Lotus Park Hotel
Reviews with text: 15

[11/500] Vistaram Siri Varshini Inn
Reviews with text: 16

[12/500] Hotel Diamond's Pearl
Reviews with text: 11

[13/500] Olive Hotel Visakhapatnam by Embassy Group
Reviews with text: 23

[14/500] Hotel Leela Imperial
Reviews with text: 19

[15/500] Hotel Winsar Park
Reviews with text: 19

[16/500] Fabhotel Lorven Grand
Reviews with text: 6

[17/500] The Port Hotel
Reviews with text: 14

[18/500] LJ Dadi's Grand
Reviews with text: 15

[19/500] Swagan Home Stays NON AC 1 BHK Deluxe Flat - Two-Bedroom Apartment
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[20/500] Magnolia Villa Luxury 3 Bedroom Apartments - Three-Bedroom Apartment
Reviews with text: 8

[21/500] Hotel Lakshmi Residency
Reviews with text: 19

[22/500] Rosee Wood
Reviews with text: 18

[23/500] Zora Park Hotel
Reviews with text: 20

[24/500] Oviya Hotels
Reviews with text: 10

[25/500] Hotel Siri Grand
Reviews with text: 14

[26/500] Royal stay visakhapatnam
Reviews with text: 16

[27/500] The Butterfly Luxury Serviced Apartments
Reviews with text: 23

[28/500] Hotel Vivana
Reviews with text: 13

[29/500] Kushi Home Stay Guest House
Reviews with text: 17

[30/500] Hotel O by OYO Sri Balaji Grand
Reviews with text: 0

[31/500] The Pioneer
Reviews with text: 12

[32/500] Treebo Marina Grand
Reviews with text: 24

[33/500] Hotel Vishnu Residency
Reviews with text: 16

[34/500] The Pallagio
Reviews with text: 10

[35/500] Kushi’s Nap N Go Dormitory
Reviews with text: 20

[36/500] Coastal Horizon Suites
Reviews with text: 1

[37/500] Servostay New Penthouse Kitchen Near Beach with Parking - One-Bedroom Apartment
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[38/500] Hotel Sitara Grand, Dabagardens
Reviews with text: 17

[39/500] Hotel Akshaya
Reviews with text: 16

[40/500] The Park, Visakhapatnam
Reviews with text: 17

[41/500] Hotel BUDHIL PARK
Reviews with text: 7

[42/500] Best Western Plus Ramachandra Hotel
Reviews with text: 20

[43/500] Leeo Comforts
Reviews with text: 17

[44/500] Vizag Urban Nest
Reviews with text: 21

[45/500] OYO Hotel O
Reviews with text: 20

[46/500] Prime Beach Hotel
Reviews with text: 23

[47/500] The Central Suites
Reviews with text: 17

[48/500] Hotel Kinnera Comforts
Reviews with text: 15

[49/500] Gadiraju Palace Convention Center & Hotel
Reviews with text: 16

[50/500] Hotel Agarwal's residency
Reviews with text: 19

[51/500] Hotel Ambicas Grand
Reviews with text: 10

[52/500] Sris Guest House
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[53/500] Hotel Anantha Suites
Reviews with text: 25

[54/500] Feel Like Home - Three-Bedroom House
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[55/500] KB's Stay - The Orchid 2BHK Duplex
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[56/500] Treebo Premium Pl Grand, Visakhapatnam
Reviews with text: 21

[57/500] Zostel Visakhapatnam (Vizag)
Reviews with text: 20

[58/500] Treebo Premium The Regal Park
Reviews with text: 19

[59/500] Hotel O Spar Grand
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 12

[60/500] M.R. Hotels
Reviews with text: 18

[61/500] Fortune Inn Sree Kanya, Visakhapatnam - Member ITC hotels' group
Reviews with text: 27

[62/500] Treebo Premium Lalitha, Rk Beach
Reviews with text: 17

[63/500] Treebo Landmark
Reviews with text: 22

[64/500] Las Vegas
Reviews with text: 15

[65/500] OYO Collection O Visakhapatnam Railway Station
Reviews with text: 17

[66/500] Royal Fort Hotel
Reviews with text: 8

[67/500] Hotel Five Elements
Reviews with text: 13

[68/500] Hotel O
Reviews with text: 14

[69/500] Collection O Tennati Park Vizag Beach Formerly B Square Villa
Reviews with text: 16

[70/500] Best Western Plus Tejvivaan
Reviews with text: 22

[71/500] Gardinn
Reviews with text: 3

[72/500] HOTEL DAKSHIN SEA PARADISE
Reviews with text: 19

[73/500] Hotel c comfort
Reviews with text: 16

[74/500] Palm Beach Hotel
Reviews with text: 17

[75/500] Townhouse by OYO Sankaramatam Road Near Diamond Park
Reviews with text: 7

[76/500] Eesha Elite
Reviews with text: 19

[77/500] Premium Home Stay at VIP Road
Reviews with text: 1

[78/500] Swagan Homes Stays a Deluxe 1 BHK Flat
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[79/500] Servostay 5 Fully Furnished 2 BHK Flats in MVP Colony, Vizag - Two-Bedroom Apartment
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[80/500] Simhagiri Holiday Inn - One-Bedroom House
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[81/500] Stunning 3 BHK Full Furnished in Vizag - 1st Floor
Reviews with text: 1

[82/500] Scenic Hill View 2BHK | Kailasagiri & Beach
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[83/500] Quaint 9-bedroom bungalow with WiFi, AC in Visakhapatnam
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[84/500] Spacious 3BHK Family Escape | Kailasagiri & Beach
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[85/500] Panoramic 2BHK | Kailasagiri, Park & Beach
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[86/500] Cottage Close to Sea Beach
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[87/500] Feel Like Home - One-Bedroom House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[88/500] StayVista Residences - RK Beach with River View - Seaview Apartment w/ Balcony 3BR
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[89/500] Feel Like Home Rkbeach - One-Bedroom House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[90/500] Charming 2-bedroom apartment with WiFi, AC in serene Visakhapatnam Beach
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[91/500] StayVista Residences - RK Beach with River View - Premium Rooms w/ Beach View
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[92/500] Feel Like Home - Two-Bedroom Townhouse
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[93/500] Sreevia Residence
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[94/500] Feel Like Home Rkbeach - Six-Bedroom House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[95/500] Sterlinge Homestay - Suite
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[96/500] Feel Like Home Rkbeach - Four-Bedroom House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[97/500] Blue Moon Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[98/500] Treebo Rainbow Grand
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[99/500] Hotel CLASSIC Luxury
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[100/500] Hotel Bsquare
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[101/500] Hotel Vilaari Blue Marina
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[102/500] Hotel Paramount
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[103/500] SPOT ON SGS RESIDENCY
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[104/500] Elegant Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[105/500] Rainbow Grand Sri Balaji Hotels
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[106/500] Hotel O by OYO Stay Inn Maharani Peta
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[107/500] Sterlinge Homestay
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[108/500] HOTEL ARVIND STAY
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[109/500] MVP Cultural Homestay
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[110/500] Super Townhouse by OYO Daba Garden Road
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[111/500] Suncrisp Studio Rooms MVP
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[112/500] Servostay 5 Fully Furnished 2 BHK Flats in MVP Colony, Vizag
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[113/500] Servostay New Penthouse Kitchen Near Beach with Parking - One-Bedroom Apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[114/500] Supine Comfort
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[115/500] HOTEL CITY CENTRAL
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[116/500] Ambica Sea Green
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[117/500] Sarovar Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[118/500] Sky Mountains Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[119/500] Harika Guest inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[120/500] Hotel Nimantran Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[121/500] HOTEL RAJASTHAN PALACE
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[122/500] OYO Hotel O Allipuram Near Railway Station
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[123/500] Townhouse 1174 Hotel Cool River
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[124/500] HOTEL C3
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[125/500] Beach View Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[126/500] The coastal nest guest house
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[127/500] OYO Townhouse Dwarakanagar
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[128/500] 6 Beach facing Hotel Suites in Lovely R.K. Beach, Visakhapatnam, with AC, WiFi
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[129/500] Fully furnished 3 a/c bedrooms apartment in a central location of Visakhapatnam
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[130/500] Hotel KGB Coolriver
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[131/500] White Villa Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[132/500] HOTEL SINKA GRAND
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[133/500] ABC Grand Lodge
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[134/500] Hotel Rajdhani Grand
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[135/500] Hotel O SSG Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[136/500] OYO Flagship Hotel Gayatri
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[137/500] Hotel 7 lamps
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[138/500] Expansive 6BHK Villa Kailasagiri and Beach
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[139/500] Ritz Comfort
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[140/500] HOTEL ATHIDI INN
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[141/500] MJ Classic Stay Visakhapatnam
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[142/500] Taj Mahal Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[143/500] Daspalla Executive Court
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[144/500] Silvervilla guesthouse
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[145/500] Seatree Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[146/500] Hotel Green Tree
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[147/500] SRI SUN RISE INN
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[148/500] Townhouse by OYO MVP Sector With Kailasagiri Hill View
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[149/500] sri krishna residency mvp vizag
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[150/500] Dwaraka grand
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[151/500] Hotel O A1 Premium AC Rooms
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[152/500] Rahul guest house and service apartment - Double Room
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[153/500] Rahul's Castle 3bhk Guest House near NAD - Three-Bedroom Apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[154/500] Open Hotel by Olive - Oceanic Vibes
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[155/500] Smart Inn Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[156/500] Jazzy Beach Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[157/500] VizagVibesHomeStay
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[158/500] Vijaya Residency
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[159/500] OYO Townhouse Gajuwaka Near CMR Mall
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[160/500] Feel Like Home RK beach
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[161/500] Beach View Holiday Home
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[162/500] Hotel O Port Road Near Poorna Market
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[163/500] Welcomhotel By ITC Hotels, Devee Grand Bay, Visakhapatnam
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[164/500] Sri Srinivasa Guest House
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[165/500] Townhouse OAK Hotel SVA
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[166/500] LG Grand
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[167/500] HOTEL SRI PYDHI GRAND
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[168/500] Sree Balajee Classic Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[169/500] aakruthiinn - One-Bedroom Apartment
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[170/500] Hotel Royal Rajasthan
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[171/500] Hotel Valley Vista
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[172/500] Homey Suites - Vizag Beach
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[173/500] Hotel Seasons Comfort
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[174/500] Vennela Inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[175/500] SR Homes and Hospitality
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[176/500] Townhouse Oak Visakhapatnam Vishwanadh Sports Club
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[177/500] Konark inn
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[178/500] HOTEL BRK ICONIC RESIDENCY
API error: 429
{
  "error": "Your account has run out of searches."
}

,hotel_name,hotel_id,state,location,price_per_night,hotel_category,customer_rating,review_count,amenities,review_text,individual_review_rating,review_date,review_source,search_area
0,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,It was great experience having food at rockdal...,5,6 hours ago,Google,Visakhapatnam
1,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,I had a wonderful stay at Hotel Rockdale and r...,5,8 hours ago,Google,Visakhapatnam
2,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,Exceptional stay,5,a day ago,Google,Visakhapatnam
3,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,"Front office is very nice, helpful. Room clean...",3,a day ago,Google,Visakhapatnam
4,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,I enjoyed food and hospitality. Ambiance is fi...,5,Edited 2 days ago,Google,Visakhapatnam
5,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,Good,5,2 days ago,Google,Visakhapatnam
6,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,Not worth the money they charge. I dont recoomed.,2,3 days ago,Google,Visakhapatnam
7,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,We stayed at Rockdale for two nights in Deluxe...,5,3 days ago,Google,Visakhapatnam
8,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,Very good for stay and also good hospitality,5,3 days ago,Google,Visakhapatnam
9,Hotel Rockdale,ChoI6PWk9reL6YP3ARoNL2cvMTFjazgyaHJmeRAB,Andhra Pradesh,"Latitude: 17.716386, Longitude: 83.308313",1981.0,3-star hotel,4.4,11853,Free breakfast | Free Wi-Fi | Free parking | A...,Booked and stayed in superior room\nEverything...,5,3 days ago,Google,Visakhapatnam

In [ ]:
from google.colab import files
files.download("andhra_pradesh_hotel_dataset.csv")

In [ ]:
import os
import time
import requests
import pandas as pd

# ============================================================
# CONFIGURATION
# ============================================================

API_KEY = input("Enter your SerpApi API key: ").strip()

OUTPUT_FILE = "chennai_hotel_dataset.csv"
CHECKPOINT_FILE = "chennai_100_new_checkpoint.csv"

CITY = "Chennai"
TARGET_NEW_HOTELS = 100
MAX_REVIEW_PAGES = 3

BASE_URL = "https://serpapi.com/search.json"

# ============================================================
# CHENNAI AREAS
# ============================================================

CHENNAI_AREAS = [
    "Central Chennai",
    "T Nagar",
    "Anna Nagar",
    "Adyar",
    "Velachery",
    "Guindy",
    "Nungambakkam",
    "Egmore",
    "Mylapore",
    "Alwarpet",
    "Besant Nagar",
    "Royapettah",
    "Triplicane",
    "Kodambakkam",
    "Vadapalani",
    "Ashok Nagar",
    "Koyambedu",
    "Kilpauk",
    "Porur",
    "Koyambedu",
    "OMR",
    "Sholinganallur",
    "Perungudi",
    "Thoraipakkam",
    "Karapakkam",
    "Navalur",
    "Siruseri",
    "Tambaram",
    "Chromepet",
    "Pallavaram",
    "Medavakkam",
    "Pallikaranai",
    "Perumbakkam",
    "Porur",
    "Ramapuram",
    "Manapakkam",
    "Mogappair",
    "Ambattur",
    "Avadi",
    "Poonamallee",
    "Chennai Airport",
    "ECR",
    "Neelankarai",
    "Palavakkam",
    "Injambakkam",
    "Kottivakkam",
    "Madhya Kailash",
    "Mount Road",
    "Chennai Central",
    "Perambur",
    "Royapuram",
    "Washermenpet",
    "George Town",
    "Broadway",
    "Chetpet",
    "Purasawalkam",
    "Saidapet",
    "Thiruvanmiyur",
    "Kotturpuram"
]

# Remove accidental duplicate areas
CHENNAI_AREAS = list(dict.fromkeys(CHENNAI_AREAS))


# ============================================================
# LOAD EXISTING DATASET
# ============================================================

if os.path.exists(OUTPUT_FILE):

    df = pd.read_csv(OUTPUT_FILE)

    print("\n" + "=" * 70)
    print("EXISTING DATASET")
    print("=" * 70)

    print(f"Existing rows: {len(df)}")

else:

    df = pd.DataFrame()

    print("No existing dataset found. Starting fresh.")


# ============================================================
# GET EXISTING HOTEL IDS
# ============================================================

if not df.empty and "hotel_id" in df.columns:

    existing_hotel_ids = set(
        df["hotel_id"]
        .dropna()
        .astype(str)
    )

else:

    existing_hotel_ids = set()


print(
    f"Existing unique hotels: "
    f"{len(existing_hotel_ids)}"
)

print(
    f"Target new hotels: "
    f"{TARGET_NEW_HOTELS}"
)

print(
    f"Expected unique hotels after run: "
    f"{len(existing_hotel_ids) + TARGET_NEW_HOTELS}"
)


# ============================================================
# LOAD CHECKPOINT
# ============================================================

if os.path.exists(CHECKPOINT_FILE):

    checkpoint = pd.read_csv(CHECKPOINT_FILE)

    completed_hotels = set(
        checkpoint.loc[
            checkpoint["status"] == "completed",
            "hotel_id"
        ]
        .astype(str)
    )

    print(
        f"Previously completed in this run: "
        f"{len(completed_hotels)}"
    )

else:

    checkpoint = pd.DataFrame(
        columns=[
            "hotel_id",
            "hotel_name",
            "search_area",
            "status"
        ]
    )

    completed_hotels = set()


# ============================================================
# SAVE CHECKPOINT
# ============================================================

def save_checkpoint(
    hotel_id,
    hotel_name,
    search_area,
    status
):

    global checkpoint

    hotel_id = str(hotel_id)

    # Remove previous entry
    checkpoint = checkpoint[
        checkpoint["hotel_id"].astype(str) != hotel_id
    ]

    new_checkpoint = pd.DataFrame([
        {
            "hotel_id": hotel_id,
            "hotel_name": hotel_name,
            "search_area": search_area,
            "status": status
        }
    ])

    checkpoint = pd.concat(
        [
            checkpoint,
            new_checkpoint
        ],
        ignore_index=True
    )

    checkpoint.to_csv(
        CHECKPOINT_FILE,
        index=False
    )


# ============================================================
# SAVE DATASET
# ============================================================

def save_dataset():

    global df

    if "hotel_id" in df.columns:

        df["hotel_id"] = df["hotel_id"].astype(str)

    if "review_id" in df.columns:

        df = df.drop_duplicates(
            subset=["review_id"]
        )

    else:

        df = df.drop_duplicates()

    df.to_csv(
        OUTPUT_FILE,
        index=False
    )

    print(
        f"Dataset saved: "
        f"{len(df)} rows | "
        f"{df['hotel_id'].nunique()} unique hotels"
    )


# ============================================================
# SEARCH HOTELS USING SERPAPI
# ============================================================

def search_hotels(search_area):

    params = {
        "engine": "google_hotels",
        "q": f"Hotels in {search_area}, Chennai",
        "check_in_date": "2026-10-15",
        "check_out_date": "2026-10-16",
        "adults": "2",
        "currency": "INR",
        "gl": "in",
        "hl": "en",
        "api_key": API_KEY
    }

    response = requests.get(
        BASE_URL,
        params=params,
        timeout=60
    )

    response.raise_for_status()

    data = response.json()

    if "error" in data:

        print(
            f"SerpApi error: {data['error']}"
        )

        return []

    return data.get(
        "properties",
        []
    )


# ============================================================
# EXTRACT LOCATION
# ============================================================

def extract_location(hotel):

    gps = hotel.get("gps_coordinates")

    if gps:

        latitude = gps.get("latitude")
        longitude = gps.get("longitude")

        if latitude is not None and longitude is not None:

            return (
                f"Latitude: {latitude}, "
                f"Longitude: {longitude}"
            )

    return hotel.get(
        "address",
        ""
    )


# ============================================================
# EXTRACT AMENITIES
# ============================================================

def extract_amenities(hotel):

    amenities = []

    # Google Hotels commonly provides amenities
    for amenity in hotel.get(
        "amenities",
        []
    ):

        if isinstance(amenity, str):

            amenities.append(amenity)

        elif isinstance(amenity, dict):

            name = (
                amenity.get("name")
                or amenity.get("title")
            )

            if name:

                amenities.append(
                    str(name)
                )

    # Remove duplicates
    amenities = list(
        dict.fromkeys(amenities)
    )

    return " | ".join(
        amenities
    )


# ============================================================
# EXTRACT PRICE
# ============================================================

def extract_price(hotel):

    # Different Google Hotels responses
    # can expose price differently.

    price = hotel.get(
        "rate_per_night",
        {}
    )

    if isinstance(price, dict):

        value = (
            price.get("lowest")
            or price.get("extracted_lowest")
        )

        if value is not None:

            return value

    # Alternative field
    if hotel.get("price") is not None:

        return hotel.get("price")

    return None


# ============================================================
# CREATE HOTEL INFORMATION
# ============================================================

def make_hotel_row(
    hotel,
    search_area
):

    hotel_id = (
        hotel.get("property_token")
        or hotel.get("hotel_id")
    )

    hotel_name = hotel.get(
        "name",
        "Unknown Hotel"
    )

    gps = hotel.get(
        "gps_coordinates",
        {}
    )

    latitude = gps.get(
        "latitude"
    )

    longitude = gps.get(
        "longitude"
    )

    row = {

        "hotel_name":
            hotel_name,

        "hotel_id":
            str(hotel_id),

        "city":
            CITY,

        "location":
            extract_location(hotel),

        "latitude":
            latitude,

        "longitude":
            longitude,

        "price_per_night":
            extract_price(hotel),

        "hotel_category":
            hotel.get(
                "hotel_class"
            ),

        "customer_rating":
            hotel.get(
                "overall_rating"
            ),

        "review_count":
            hotel.get(
                "reviews"
            ),

        "amenities":
            extract_amenities(hotel),

        "review_text":
            "",

        "individual_review_rating":
            None,

        "review_date":
            "",

        "review_source":
            "Google Hotels via SerpApi",

        "search_area":
            search_area
    }

    return row


# ============================================================
# FETCH REVIEWS
# ============================================================

def fetch_reviews(
    hotel,
    search_area
):

    hotel_id = (
        hotel.get("property_token")
        or hotel.get("hotel_id")
    )

    hotel_name = hotel.get(
        "name",
        "Unknown Hotel"
    )

    if not hotel_id:

        return []

    all_reviews = []

    next_page_token = None

    for page in range(
        1,
        MAX_REVIEW_PAGES + 1
    ):

        params = {

            "engine":
                "google_hotels_reviews",

            "property_token":
                hotel_id,

            "hl":
                "en",

            "sort_by":
                "2",

            "api_key":
                API_KEY
        }

        # If SerpApi gives a next-page token,
        # use it for the next request.
        if next_page_token:

            params["next_page_token"] = (
                next_page_token
            )

        try:

            response = requests.get(
                BASE_URL,
                params=params,
                timeout=60
            )

            response.raise_for_status()

            data = response.json()

        except Exception as e:

            print(
                f"Review request failed: {e}"
            )

            break

        if "error" in data:

            print(
                f"Review API error: "
                f"{data['error']}"
            )

            break

        reviews = data.get(
            "reviews",
            []
        )

        if not reviews:

            break

        # ------------------------------------------
        # CONVERT REVIEWS TO OUR DATASET FORMAT
        # ------------------------------------------

        for review in reviews:

            reviewer = review.get(
                "user",
                {}
            )

            review_id = (
                review.get("review_id")
                or review.get("id")
            )

            # If SerpApi doesn't provide a review ID,
            # create a deterministic one.
            if not review_id:

                review_id = (
                    f"{hotel_id}_"
                    f"{len(all_reviews)}"
                )

            review_rating = (
                review.get("rating")
                or review.get(
                    "overall_rating"
                )
            )

            review_text = (
                review.get("snippet")
                or review.get("text")
                or review.get(
                    "review_text"
                )
                or ""
            )

            review_date = (
                review.get("date")
                or review.get(
                    "relative_date"
                )
                or ""
            )

            row = {

                "hotel_name":
                    hotel_name,

                "hotel_id":
                    str(hotel_id),

                "city":
                    CITY,

                "location":
                    extract_location(
                        hotel
                    ),

                "latitude":
                    hotel.get(
                        "gps_coordinates",
                        {}
                    ).get(
                        "latitude"
                    ),

                "longitude":
                    hotel.get(
                        "gps_coordinates",
                        {}
                    ).get(
                        "longitude"
                    ),

                "price_per_night":
                    extract_price(
                        hotel
                    ),

                "hotel_category":
                    hotel.get(
                        "hotel_class"
                    ),

                "customer_rating":
                    hotel.get(
                        "overall_rating"
                    ),

                "review_count":
                    hotel.get(
                        "reviews"
                    ),

                "amenities":
                    extract_amenities(
                        hotel
                    ),

                "review_text":
                    review_text,

                "individual_review_rating":
                    review_rating,

                "review_date":
                    review_date,

                "review_source":
                    "Google Hotels Reviews via SerpApi",

                "search_area":
                    search_area,

                "review_id":
                    review_id
            }

            all_reviews.append(
                row
            )

        # ------------------------------------------
        # NEXT PAGE
        # ------------------------------------------

        next_page_token = data.get(
            "serpapi_pagination",
            {}
        ).get(
            "next_page_token"
        )

        if not next_page_token:

            break

        time.sleep(1)

    return all_reviews


# ============================================================
# MAIN SCRAPING PROCESS
# ============================================================

new_hotel_ids = set()

new_hotels_collected = 0


print("\n" + "=" * 70)
print("STARTING CHENNAI NEW-HOTEL SCRAPING")
print("=" * 70)

print(
    f"Existing unique hotels: "
    f"{len(existing_hotel_ids)}"
)

print(
    f"Need NEW hotels: "
    f"{TARGET_NEW_HOTELS}"
)

print("=" * 70)


# ============================================================
# LOOP THROUGH CHENNAI AREAS
# ============================================================

for search_area in CHENNAI_AREAS:

    # Stop once 100 new hotels are collected
    if new_hotels_collected >= TARGET_NEW_HOTELS:

        break

    print("\n")
    print("=" * 70)

    print(
        f"SEARCH AREA: {search_area}"
    )

    print(
        f"Progress: "
        f"{new_hotels_collected}/"
        f"{TARGET_NEW_HOTELS} new hotels"
    )

    print("=" * 70)


    # ========================================================
    # SEARCH HOTELS
    # ========================================================

    try:

        hotels = search_hotels(
            search_area
        )

    except Exception as e:

        print(
            f"Hotel search failed for "
            f"{search_area}: {e}"
        )

        continue


    print(
        f"Hotels returned: "
        f"{len(hotels)}"
    )


    # ========================================================
    # PROCESS EACH HOTEL
    # ========================================================

    for hotel in hotels:

        # Stop at 100
        if new_hotels_collected >= TARGET_NEW_HOTELS:

            break


        # ----------------------------------------------------
        # HOTEL ID
        # ----------------------------------------------------

        hotel_id = (
            hotel.get("property_token")
            or hotel.get("hotel_id")
        )

        hotel_name = hotel.get(
            "name",
            "Unknown Hotel"
        )


        if not hotel_id:

            print(
                f"Skipping {hotel_name} "
                f"- no hotel ID"
            )

            continue


        hotel_id = str(
            hotel_id
        )


        # ----------------------------------------------------
        # SKIP EXISTING HOTELS
        # ----------------------------------------------------

        if hotel_id in existing_hotel_ids:

            print(
                f"SKIP EXISTING: "
                f"{hotel_name}"
            )

            continue


        # ----------------------------------------------------
        # SKIP ALREADY FOUND DURING THIS RUN
        # ----------------------------------------------------

        if hotel_id in new_hotel_ids:

            continue


        print("\n" + "-" * 60)

        print(
            f"NEW HOTEL "
            f"{new_hotels_collected + 1}/"
            f"{TARGET_NEW_HOTELS}"
        )

        print(
            f"Hotel: {hotel_name}"
        )

        print(
            f"Hotel ID: {hotel_id}"
        )

        print(
            f"Area: {search_area}"
        )

        print("-" * 60)


        # ====================================================
        # FETCH REVIEWS
        # ====================================================

        try:

            reviews = fetch_reviews(
                hotel,
                search_area
            )

        except Exception as e:

            print(
                f"Review collection failed: {e}"
            )

            reviews = []


        # ====================================================
        # IF REVIEWS EXIST
        # ====================================================

        if reviews:

            new_df = pd.DataFrame(
                reviews
            )

            df = pd.concat(
                [
                    df,
                    new_df
                ],
                ignore_index=True
            )

            # Remove duplicate reviews
            if "review_id" in df.columns:

                df = df.drop_duplicates(
                    subset=["review_id"]
                )

            print(
                f"Reviews collected: "
                f"{len(reviews)}"
            )

        else:

            # ------------------------------------------------
            # SAVE HOTEL EVEN IF NO REVIEWS
            # ------------------------------------------------
            #
            # This ensures that we really collect
            # 100 NEW UNIQUE HOTELS.

            hotel_row = make_hotel_row(
                hotel,
                search_area
            )

            df = pd.concat(
                [
                    df,
                    pd.DataFrame([
                        hotel_row
                    ])
                ],
                ignore_index=True
            )

            print(
                "No reviews found. "
                "Hotel information saved."
            )


        # ====================================================
        # SAVE IMMEDIATELY
        # ====================================================

        save_dataset()


        # ====================================================
        # UPDATE TRACKING
        # ====================================================

        new_hotel_ids.add(
            hotel_id
        )

        existing_hotel_ids.add(
            hotel_id
        )

        new_hotels_collected += 1


        save_checkpoint(
            hotel_id,
            hotel_name,
            search_area,
            "completed"
        )


        print(
            f"SUCCESS: {hotel_name}"
        )

        print(
            f"New hotel progress: "
            f"{new_hotels_collected}/"
            f"{TARGET_NEW_HOTELS}"
        )

        print(
            f"Total unique hotels currently: "
            f"{df['hotel_id'].nunique()}"
        )


        # Small delay
        time.sleep(2)


# ============================================================
# FINAL SAVE
# ============================================================

save_dataset()


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("CHENNAI SCRAPING COMPLETED")
print("=" * 70)

print(
    f"New hotels collected: "
    f"{new_hotels_collected}"
)

print(
    f"Total unique hotels: "
    f"{df['hotel_id'].nunique()}"
)

print(
    f"Total dataset rows: "
    f"{len(df)}"
)

print(
    f"Output file: "
    f"{OUTPUT_FILE}"
)

print(
    f"Checkpoint file: "
    f"{CHECKPOINT_FILE}"
)

print("=" * 70)


# ============================================================
# FINAL HOTEL COUNT CHECK
# ============================================================

print("\nFINAL HOTEL COUNT")

hotel_counts = (
    df.groupby("hotel_id")
      .size()
      .reset_index(
          name="review_rows"
      )
)

print(
    f"Unique hotels: "
    f"{len(hotel_counts)}"
)

print(
    f"Total review/data rows: "
    f"{len(df)}"
)

print(
    "\nDataset is ready."
)

Enter your SerpApi API key: 8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1

======================================================================
EXISTING DATASET
======================================================================
Existing rows: 976
Existing unique hotels: 55
Target new hotels: 100
Expected unique hotels after run: 155

======================================================================
STARTING CHENNAI NEW-HOTEL SCRAPING
======================================================================
Existing unique hotels: 55
Need NEW hotels: 100
======================================================================


======================================================================
SEARCH AREA: Central Chennai
Progress: 0/100 new hotels
======================================================================
Hotels returned: 20
SKIP EXISTING: The Hydel Park (Business Class Hotel) Chennai
SKIP EXISTING: Lemon Tree Hotel, Shimona Chennai
SKIP EXISTING: Four Points by Sheraton Chennai OMR
SKIP EXISTING: Ramada by Wyndham Chennai Egmore
SKIP EXISTING: Holiday Inn Express Chennai Omr Thoraipakkam, an IHG Hotel
SKIP EXISTING: Hotel Greenpark Chennai

------------------------------------------------------------
NEW HOTEL 1/100
Hotel: Leisure Stays - Premium Suites - Three-Bedroom Apartment
Hotel ID: ChkQgNb04cbP2_Z-Gg0vZy8xMW1reXJfcnA5EAI
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 6
Dataset saved: 7 rows | 2 unique hotels
SUCCESS: Leisure Stays - Premium Suites - Three-Bedroom Apartment
New hotel progress: 1/100
Total unique hotels currently: 2
SKIP EXISTING: Ramada Plaza by Wyndham Chennai
SKIP EXISTING: The Madras Grand - Hotel Egmore
SKIP EXISTING: Pride Premier Chennai
SKIP EXISTING: Bloom Hub | Guindy
SKIP EXISTING: The Nest Lovely 3BHK and 1BHK Villa - One-Bedroom Villa
SKIP EXISTING: E Hotel Chennai
SKIP EXISTING: Ginger Chennai OMR
SKIP EXISTING: JP Hotel Chennai
SKIP EXISTING: The Pride Fort Hotel
SKIP EXISTING: Raj Park Hotel Chennai
SKIP EXISTING: Hotel Ambica Empire

------------------------------------------------------------
NEW HOTEL 2/100
Hotel: Hanu Reddy Residences - Nawab Habibullah Avenue - Deluxe Double Room
Hotel ID: ChkQvpD9hc_j9IpNGg0vZy8xMXozOXR0MzFjEAI
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 8
Dataset saved: 15 rows | 3 unique hotels
SUCCESS: Hanu Reddy Residences - Nawab Habibullah Avenue - Deluxe Double Room
New hotel progress: 2/100
Total unique hotels currently: 3
SKIP EXISTING: Park Elanza


======================================================================
SEARCH AREA: T Nagar
Progress: 2/100 new hotels
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 3/100
Hotel: UPAR Hotels T Nagar
Hotel ID: ChoIxuiE08Hi-sqyARoNL2cvMTFydmNzZ3QyORAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 45 rows | 4 unique hotels
SUCCESS: UPAR Hotels T Nagar
New hotel progress: 3/100
Total unique hotels currently: 4

------------------------------------------------------------
NEW HOTEL 4/100
Hotel: The Lotus Apartment Hotel
Hotel ID: ChgIk_W8mNzN1IymARoLL2cvMXRmN2t6XzMQAQ
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 75 rows | 5 unique hotels
SUCCESS: The Lotus Apartment Hotel
New hotel progress: 4/100
Total unique hotels currently: 5

------------------------------------------------------------
NEW HOTEL 5/100
Hotel: ACD HOTELS
Hotel ID: ChkIqvisyL3luYYoGg0vZy8xMXhtdjIzY18wEAE
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 105 rows | 6 unique hotels
SUCCESS: ACD HOTELS
New hotel progress: 5/100
Total unique hotels currently: 6

------------------------------------------------------------
NEW HOTEL 6/100
Hotel: Grand Continent
Hotel ID: ChoIlMLAp6nGt7fwARoNL2cvMTF4ZDNuYzc5dBAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 135 rows | 7 unique hotels
SUCCESS: Grand Continent
New hotel progress: 6/100
Total unique hotels currently: 7

------------------------------------------------------------
NEW HOTEL 7/100
Hotel: Golden Fruits Business Suites
Hotel ID: ChkIx_uHhdvihZIlGg0vZy8xMWI1d2w0Y3o2EAE
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 165 rows | 8 unique hotels
SUCCESS: Golden Fruits Business Suites
New hotel progress: 7/100
Total unique hotels currently: 8

------------------------------------------------------------
NEW HOTEL 8/100
Hotel: The Saibaba Hotel | Accommodation in T Nagar Chennai
Hotel ID: ChoIk5zQ9LHkycPeARoNL2cvMTFoeDYxXzRkdxAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 195 rows | 9 unique hotels
SUCCESS: The Saibaba Hotel | Accommodation in T Nagar Chennai
New hotel progress: 8/100
Total unique hotels currently: 9

------------------------------------------------------------
NEW HOTEL 9/100
Hotel: SEASON 4 RESIDENCES - NUNGAMBAKKAM
Hotel ID: ChkIzeS18aLzpLkOGg0vZy8xMWY0d3RicDZmEAE
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 225 rows | 10 unique hotels
SUCCESS: SEASON 4 RESIDENCES - NUNGAMBAKKAM
New hotel progress: 9/100
Total unique hotels currently: 10
SKIP EXISTING: JJS PARK INN

------------------------------------------------------------
NEW HOTEL 10/100
Hotel: S Hotels Chennai
Hotel ID: ChcI0POnyafOra9uGgsvZy8xdGw4ajN5cxAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 255 rows | 11 unique hotels
SUCCESS: S Hotels Chennai
New hotel progress: 10/100
Total unique hotels currently: 11

------------------------------------------------------------
NEW HOTEL 11/100
Hotel: STAR CITY HOTELS
Hotel ID: ChkI0Jj58ab5x9kUGg0vZy8xMWcwbTU3ZHZiEAE
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 285 rows | 12 unique hotels
SUCCESS: STAR CITY HOTELS
New hotel progress: 11/100
Total unique hotels currently: 12

------------------------------------------------------------
NEW HOTEL 12/100
Hotel: Lloyds Serviced Apartments, T. Nagar Chennai
Hotel ID: ChgIuLff6YCfv-8rGgwvZy8xaGRfMnFjMncQAQ
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 315 rows | 13 unique hotels
SUCCESS: Lloyds Serviced Apartments, T. Nagar Chennai
New hotel progress: 12/100
Total unique hotels currently: 13

------------------------------------------------------------
NEW HOTEL 13/100
Hotel: Treebo Gt Meridian, T-Nagar
Hotel ID: ChoIlJXtrdLCo-PQARoNL2cvMTF6NjE2bXd5bBAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 345 rows | 14 unique hotels
SUCCESS: Treebo Gt Meridian, T-Nagar
New hotel progress: 13/100
Total unique hotels currently: 14

------------------------------------------------------------
NEW HOTEL 14/100
Hotel: Hotel Kheni
Hotel ID: ChkIh6-ohvba4P9MGg0vZy8xMWxiN3NoaHc2EAE
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 375 rows | 15 unique hotels
SUCCESS: Hotel Kheni
New hotel progress: 14/100
Total unique hotels currently: 15
SKIP EXISTING: Urvashi Residency - T.Nagar

------------------------------------------------------------
NEW HOTEL 15/100
Hotel: Malaysia Inn
Hotel ID: ChoI5OWW47uu3NSYARoNL2cvMTFjM21xYnkyMBAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 405 rows | 16 unique hotels
SUCCESS: Malaysia Inn
New hotel progress: 15/100
Total unique hotels currently: 16

------------------------------------------------------------
NEW HOTEL 16/100
Hotel: GREEN TREE HOTEL
Hotel ID: ChkIvYmE9YGpoN1qGg0vZy8xMWgycG43Z2YxEAE
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 435 rows | 17 unique hotels
SUCCESS: GREEN TREE HOTEL
New hotel progress: 16/100
Total unique hotels currently: 17

------------------------------------------------------------
NEW HOTEL 17/100
Hotel: 44 Oasis- Hotel T.Nagar
Hotel ID: ChoIx9Hswc6R286NARoNL2cvMTF3MXFoNjRiehAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 465 rows | 18 unique hotels
SUCCESS: 44 Oasis- Hotel T.Nagar
New hotel progress: 17/100
Total unique hotels currently: 18

------------------------------------------------------------
NEW HOTEL 18/100
Hotel: THE K11 HOTELS - CHENNAI
Hotel ID: ChkIj4Dr7dKs-8ZGGg0vZy8xMWJ6cnBkaHI0EAE
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 495 rows | 19 unique hotels
SUCCESS: THE K11 HOTELS - CHENNAI
New hotel progress: 18/100
Total unique hotels currently: 19

------------------------------------------------------------
NEW HOTEL 19/100
Hotel: ACD HOTELs
Hotel ID: ChoQ18m1vdXo_Z6LARoNL2cvMTFudGhyMDZ0cxAC
Area: T Nagar
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found. Hotel information saved.
Dataset saved: 495 rows | 19 unique hotels
SUCCESS: ACD HOTELs
New hotel progress: 19/100
Total unique hotels currently: 19

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 20/100
Hotel: Golden Fruits Business Suites - Standard Double Room
Hotel ID: ChoQ7d2QyoSKpubjARoNL2cvMTF6MTQ0NGtsMhAC
Area: T Nagar
------------------------------------------------------------
Reviews collected: 4
Dataset saved: 499 rows | 20 unique hotels
SUCCESS: Golden Fruits Business Suites - Standard Double Room
New hotel progress: 20/100
Total unique hotels currently: 20


======================================================================
SEARCH AREA: Anna Nagar
Progress: 20/100 new hotels
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 21/100
Hotel: Blu Iris (Hot Plate)
Hotel ID: ChkIttOO5b2Yh-FaGg0vZy8xMWNuNXFocTBxEAE
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 529 rows | 21 unique hotels
SUCCESS: Blu Iris (Hot Plate)
New hotel progress: 21/100
Total unique hotels currently: 21
SKIP EXISTING: JP Hotel Chennai
SKIP EXISTING: Metro Grand Hotel

------------------------------------------------------------
NEW HOTEL 22/100
Hotel: Zostel Chennai (Anna Nagar)
Hotel ID: ChkItKfJicT6g5o5Gg0vZy8xMXlmcjFmNHo5EAE
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 559 rows | 22 unique hotels
SUCCESS: Zostel Chennai (Anna Nagar)
New hotel progress: 22/100
Total unique hotels currently: 22
SKIP EXISTING: Emirates Residency - Hotel in Koyambedu Chennai

------------------------------------------------------------
NEW HOTEL 23/100
Hotel: Hotel Blu Ivy
Hotel ID: ChgI8a7Y5oCdqN8-GgwvZy8xcTVidnA2d24QAQ
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 589 rows | 23 unique hotels
SUCCESS: Hotel Blu Ivy
New hotel progress: 23/100
Total unique hotels currently: 23

------------------------------------------------------------
NEW HOTEL 24/100
Hotel: Hotel Chennai Deluxe
Hotel ID: ChoI2ru-md3-z-yYARoNL2cvMTFnMG12N3J3MBAB
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 619 rows | 24 unique hotels
SUCCESS: Hotel Chennai Deluxe
New hotel progress: 24/100
Total unique hotels currently: 24

------------------------------------------------------------
NEW HOTEL 25/100
Hotel: Blu Ivy Serene
Hotel ID: ChoIof37ipTJy86GARoNL2cvMTFxbnJtdHZwchAB
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 649 rows | 25 unique hotels
SUCCESS: Blu Ivy Serene
New hotel progress: 25/100
Total unique hotels currently: 25

------------------------------------------------------------
NEW HOTEL 26/100
Hotel: Madras House
Hotel ID: ChkItIvmkbfZgdowGg0vZy8xMWZybnYyY3E4EAE
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 679 rows | 26 unique hotels
SUCCESS: Madras House
New hotel progress: 26/100
Total unique hotels currently: 26
SKIP EXISTING: GM Residency

------------------------------------------------------------
NEW HOTEL 27/100
Hotel: Madras Regency
Hotel ID: ChkIq4jV19-h2-8ZGg0vZy8xMXFuZHRfODdyEAE
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 709 rows | 27 unique hotels
SUCCESS: Madras Regency
New hotel progress: 27/100
Total unique hotels currently: 27

------------------------------------------------------------
NEW HOTEL 28/100
Hotel: Hotel MMs Chennai Gateway
Hotel ID: ChkI88-91auKiq1UGg0vZy8xMXJiMTN2a2ozEAE
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 739 rows | 28 unique hotels
SUCCESS: Hotel MMs Chennai Gateway
New hotel progress: 28/100
Total unique hotels currently: 28

------------------------------------------------------------
NEW HOTEL 29/100
Hotel: Comfort Park Inn Koyambedu Chennai
Hotel ID: ChkIvZ6Pze7b_71mGg0vZy8xMXJjZGh0MXZzEAE
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 769 rows | 29 unique hotels
SUCCESS: Comfort Park Inn Koyambedu Chennai
New hotel progress: 29/100
Total unique hotels currently: 29

------------------------------------------------------------
NEW HOTEL 30/100
Hotel: Saaral Residency
Hotel ID: ChgI_rCRjIyGj7pnGgwvZy8xcHR3azBuN2oQAQ
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 799 rows | 30 unique hotels
SUCCESS: Saaral Residency
New hotel progress: 30/100
Total unique hotels currently: 30

------------------------------------------------------------
NEW HOTEL 31/100
Hotel: TREETOPS INN
Hotel ID: ChgI3vnik6WtglQaDS9nLzExazM0dmg5czAQAQ
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 829 rows | 31 unique hotels
SUCCESS: TREETOPS INN
New hotel progress: 31/100
Total unique hotels currently: 31

------------------------------------------------------------
NEW HOTEL 32/100
Hotel: OYO Townhouse 043 Anna Nagar
Hotel ID: ChkIirO4wMj3wOo_Gg0vZy8xMWZkNDIxeXhsEAE
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 859 rows | 32 unique hotels
SUCCESS: OYO Townhouse 043 Anna Nagar
New hotel progress: 32/100
Total unique hotels currently: 32

------------------------------------------------------------
NEW HOTEL 33/100
Hotel: Treebo Fourth Avenue
Hotel ID: ChkIi8Li346ZndwmGg0vZy8xMWJ6cTM5NHcxEAE
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 889 rows | 33 unique hotels
SUCCESS: Treebo Fourth Avenue
New hotel progress: 33/100
Total unique hotels currently: 33

------------------------------------------------------------
NEW HOTEL 34/100
Hotel: The Kanchi Residency
Hotel ID: ChgIr9W46aatt4OMARoLL2cvMXRmajFsdHYQAQ
Area: Anna Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 919 rows | 34 unique hotels
SUCCESS: The Kanchi Residency
New hotel progress: 34/100
Total unique hotels currently: 34

------------------------------------------------------------
NEW HOTEL 35/100
Hotel: Hygge Suites | Peaceful Stay in Anna Nagar
Hotel ID: ChoQg43p_tGpyLHIARoNL2cvMTF6ZDcyMjU4NxAC
Area: Anna Nagar
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found. Hotel information saved.
Dataset saved: 919 rows | 34 unique hotels
SUCCESS: Hygge Suites | Peaceful Stay in Anna Nagar
New hotel progress: 35/100
Total unique hotels currently: 34

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 36/100
Hotel: family and couple friendly and pet friendly
Hotel ID: ChoQj5D0_f7Oxb2YARoNL2cvMTF5M216MWx3OBAC
Area: Anna Nagar
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found. Hotel information saved.
Dataset saved: 919 rows | 34 unique hotels
SUCCESS: family and couple friendly and pet friendly
New hotel progress: 36/100
Total unique hotels currently: 34

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCH AREA: Adyar
Progress: 36/100 new hotels
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 37/100
Hotel: Kings Cross Residency
Hotel ID: ChkIzbL2_urpvvn3ARoML2cvMXE2a2szel9tEAE
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 949 rows | 35 unique hotels
SUCCESS: Kings Cross Residency
New hotel progress: 37/100
Total unique hotels currently: 35

------------------------------------------------------------
NEW HOTEL 38/100
Hotel: S4 Residency
Hotel ID: ChoIp4ah8_XcxZy0ARoNL2cvMTFieXNqdGs1XxAB
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 979 rows | 36 unique hotels
SUCCESS: S4 Residency
New hotel progress: 38/100
Total unique hotels currently: 36

------------------------------------------------------------
NEW HOTEL 39/100
Hotel: SKYRY HOTELS ADYAR
Hotel ID: ChkIxa6d4cyGsKBpGg0vZy8xMXFuZDI5Z3c3EAE
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1009 rows | 37 unique hotels
SUCCESS: SKYRY HOTELS ADYAR
New hotel progress: 39/100
Total unique hotels currently: 37

------------------------------------------------------------
NEW HOTEL 40/100
Hotel: Balaji Beach House
Hotel ID: ChkQm8en_p_m3JBDGg0vZy8xMXpkNzJsNXAxEAI
Area: Adyar
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found. Hotel information saved.
Dataset saved: 1009 rows | 37 unique hotels
SUCCESS: Balaji Beach House
New hotel progress: 40/100
Total unique hotels currently: 37

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 41/100
Hotel: Annsun Boutique Hotel
Hotel ID: ChgI6qac2e-7-MnJARoLL2cvMXRkeGo4dzAQAQ
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1039 rows | 38 unique hotels
SUCCESS: Annsun Boutique Hotel
New hotel progress: 41/100
Total unique hotels currently: 38

------------------------------------------------------------
NEW HOTEL 42/100
Hotel: RMC Travellers Inn
Hotel ID: ChgI8oGDn5TF5fssGgwvZy8xaGMxMW1ibngQAQ
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1069 rows | 39 unique hotels
SUCCESS: RMC Travellers Inn
New hotel progress: 42/100
Total unique hotels currently: 39
SKIP EXISTING: Flagship Bella Vagues Hotels Chennai

------------------------------------------------------------
NEW HOTEL 43/100
Hotel: Mahes Villa Svenks Hotels
Hotel ID: ChoI6Kie_5DF06-eARoNL2cvMTFuM2t6eTI3OBAB
Area: Adyar
------------------------------------------------------------
Reviews collected: 4
Dataset saved: 1073 rows | 40 unique hotels
SUCCESS: Mahes Villa Svenks Hotels
New hotel progress: 43/100
Total unique hotels currently: 40
SKIP EXISTING: S Hotels Chennai

------------------------------------------------------------
NEW HOTEL 44/100
Hotel: Ginger Chennai (Tharamani, IITM)
Hotel ID: ChgImOLY657aisD2ARoLL2cvMXZuX3hkNTkQAQ
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1103 rows | 41 unique hotels
SUCCESS: Ginger Chennai (Tharamani, IITM)
New hotel progress: 44/100
Total unique hotels currently: 41

------------------------------------------------------------
NEW HOTEL 45/100
Hotel: Stay Easy Tiruvanmiyur Chennai
Hotel ID: ChoI_LD-toOB3-jvARoNL2cvMTFiNm1jdmgwdxAB
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1133 rows | 42 unique hotels
SUCCESS: Stay Easy Tiruvanmiyur Chennai
New hotel progress: 45/100
Total unique hotels currently: 42

------------------------------------------------------------
NEW HOTEL 46/100
Hotel: MG Park
Hotel ID: ChoIzJy6uOHs9YnLARoNL2cvMTF4dGg0cW5sbhAB
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1163 rows | 43 unique hotels
SUCCESS: MG Park
New hotel progress: 46/100
Total unique hotels currently: 43

------------------------------------------------------------
NEW HOTEL 47/100
Hotel: Esthell Hotel
Hotel ID: ChkI4O3OkP3MhdB-Gg0vZy8xMWZ5emQwamtkEAE
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1193 rows | 44 unique hotels
SUCCESS: Esthell Hotel
New hotel progress: 47/100
Total unique hotels currently: 44

------------------------------------------------------------
NEW HOTEL 48/100
Hotel: Kaira Park
Hotel ID: ChoI14fl0avfibL6ARoNL2cvMTF4ZmRkNjQ1MRAB
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1223 rows | 45 unique hotels
SUCCESS: Kaira Park
New hotel progress: 48/100
Total unique hotels currently: 45

------------------------------------------------------------
NEW HOTEL 49/100
Hotel: The K11 Golden Gate - Chennai
Hotel ID: ChkIwonXzuPJnuVzGg0vZy8xMXg4ZG1iOGdxEAE
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1253 rows | 46 unique hotels
SUCCESS: The K11 Golden Gate - Chennai
New hotel progress: 49/100
Total unique hotels currently: 46

------------------------------------------------------------
NEW HOTEL 50/100
Hotel: Blue Shell
Hotel ID: ChkIroHNodrOpdZaGg0vZy8xMXltbXZmcmxkEAE
Area: Adyar
------------------------------------------------------------
Reviews collected: 28
Dataset saved: 1281 rows | 47 unique hotels
SUCCESS: Blue Shell
New hotel progress: 50/100
Total unique hotels currently: 47
SKIP EXISTING: Treebo Gt Meridian, T-Nagar

------------------------------------------------------------
NEW HOTEL 51/100
Hotel: Stay N Tour Home Adyar Chennai
Hotel ID: ChkIjs-r9JzHk_snGg0vZy8xMWw2NjQyOTY0EAE
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1311 rows | 48 unique hotels
SUCCESS: Stay N Tour Home Adyar Chennai
New hotel progress: 51/100
Total unique hotels currently: 48

------------------------------------------------------------
NEW HOTEL 52/100
Hotel: Staylite Suites Thiruvanmiyur Chennai
Hotel ID: ChkI2Z30l4709sliGg0vZy8xMWg2c2x2cWR6EAE
Area: Adyar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1341 rows | 49 unique hotels
SUCCESS: Staylite Suites Thiruvanmiyur Chennai
New hotel progress: 52/100
Total unique hotels currently: 49

------------------------------------------------------------
NEW HOTEL 53/100
Hotel: Royale Seabreeze Service Suites
Hotel ID: ChoQ06T-lvy19Kq3ARoNL2cvMTFuYm1xem5uNBAC
Area: Adyar
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found. Hotel information saved.
Dataset saved: 1341 rows | 49 unique hotels
SUCCESS: Royale Seabreeze Service Suites
New hotel progress: 53/100
Total unique hotels currently: 49

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCH AREA: Velachery
Progress: 53/100 new hotels
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 54/100
Hotel: Itsy Hotels Mirra
Hotel ID: ChoI5sulw7mv3qupARoNL2cvMTFoX3d0Z2I1OBAB
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1371 rows | 50 unique hotels
SUCCESS: Itsy Hotels Mirra
New hotel progress: 54/100
Total unique hotels currently: 50

------------------------------------------------------------
NEW HOTEL 55/100
Hotel: FabHotel Vijaylakshmi Stay Inn
Hotel ID: ChoI_sLO6cHs0_fsARoNL2cvMTF0Ymducmo5ahAB
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1401 rows | 51 unique hotels
SUCCESS: FabHotel Vijaylakshmi Stay Inn
New hotel progress: 55/100
Total unique hotels currently: 51

------------------------------------------------------------
NEW HOTEL 56/100
Hotel: Hablis - A Business Hotel In Chennal
Hotel ID: ChgIo8K35dr4tIE2GgwvZy8xMmpscjZsdzAQAQ
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1431 rows | 52 unique hotels
SUCCESS: Hablis - A Business Hotel In Chennal
New hotel progress: 56/100
Total unique hotels currently: 52

------------------------------------------------------------
NEW HOTEL 57/100
Hotel: BOULEVARD by Design Hotel Chennai
Hotel ID: ChkIo5b3iYSXy_d6Gg0vZy8xMWMyMGNoYncyEAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1461 rows | 53 unique hotels
SUCCESS: BOULEVARD by Design Hotel Chennai
New hotel progress: 57/100
Total unique hotels currently: 53

------------------------------------------------------------
NEW HOTEL 58/100
Hotel: Aashi Serviced Apartments
Hotel ID: ChoI7budyajc0_fQARoNL2cvMTF5eWhxMG43ZhAB
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1491 rows | 54 unique hotels
SUCCESS: Aashi Serviced Apartments
New hotel progress: 58/100
Total unique hotels currently: 54

------------------------------------------------------------
NEW HOTEL 59/100
Hotel: Chippy Residency
Hotel ID: ChoI-vawr43o8tLPARoNL2cvMTFzeXM5bTlqbhAB
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1521 rows | 55 unique hotels
SUCCESS: Chippy Residency
New hotel progress: 59/100
Total unique hotels currently: 55

------------------------------------------------------------
NEW HOTEL 60/100
Hotel: D and A BOUTIQUE HOTEL
Hotel ID: ChkIupGeofefot4dGg0vZy8xMXdoNmZtMHFxEAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1551 rows | 56 unique hotels
SUCCESS: D and A BOUTIQUE HOTEL
New hotel progress: 60/100
Total unique hotels currently: 56

------------------------------------------------------------
NEW HOTEL 61/100
Hotel: Four Points by Sheraton Chennai, Velachery
Hotel ID: ChkI9JS7iMLTsKRWGg0vZy8xMXk4Nnk5bGc3EAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1581 rows | 57 unique hotels
SUCCESS: Four Points by Sheraton Chennai, Velachery
New hotel progress: 61/100
Total unique hotels currently: 57

------------------------------------------------------------
NEW HOTEL 62/100
Hotel: Hotel O Velachery
Hotel ID: ChkIobKl1fTG7r4VGg0vZy8xMWM1ZnpmeXl0EAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1611 rows | 58 unique hotels
SUCCESS: Hotel O Velachery
New hotel progress: 62/100
Total unique hotels currently: 58

------------------------------------------------------------
NEW HOTEL 63/100
Hotel: Hotel Dhans
Hotel ID: ChkI1qCA4rLD6P8kGg0vZy8xMWdqd183YzVmEAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1641 rows | 59 unique hotels
SUCCESS: Hotel Dhans
New hotel progress: 63/100
Total unique hotels currently: 59

------------------------------------------------------------
NEW HOTEL 64/100
Hotel: 7 Hills Service Apartments
Hotel ID: ChkI7fzLv8Cwxuh8Gg0vZy8xMWcwbXY4eHFxEAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1671 rows | 60 unique hotels
SUCCESS: 7 Hills Service Apartments
New hotel progress: 64/100
Total unique hotels currently: 60

------------------------------------------------------------
NEW HOTEL 65/100
Hotel: FabHotel Harma Residency
Hotel ID: ChkIjq-9oeLonIwTGg0vZy8xMWg0ZGtmY3EyEAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1701 rows | 61 unique hotels
SUCCESS: FabHotel Harma Residency
New hotel progress: 65/100
Total unique hotels currently: 61

------------------------------------------------------------
NEW HOTEL 66/100
Hotel: The Westin Chennai Velachery
Hotel ID: ChYI29ajs42Eye9DGgovbS8wcGQ5OHB5EAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1731 rows | 62 unique hotels
SUCCESS: The Westin Chennai Velachery
New hotel progress: 66/100
Total unique hotels currently: 62
SKIP EXISTING: Ginger Chennai (Tharamani, IITM)

------------------------------------------------------------
NEW HOTEL 67/100
Hotel: Pine Tree Signature
Hotel ID: ChkIuq3n7b7T44kbGg0vZy8xMWYxMnNtbmxmEAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1761 rows | 63 unique hotels
SUCCESS: Pine Tree Signature
New hotel progress: 67/100
Total unique hotels currently: 63
SKIP EXISTING: Annsun Boutique Hotel

------------------------------------------------------------
NEW HOTEL 68/100
Hotel: KANS ONE - MADIPAKKAM
Hotel ID: ChoIw6eB34eRjJn1ARoNL2cvMTFzNXhwd3E1YxAB
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1791 rows | 64 unique hotels
SUCCESS: KANS ONE - MADIPAKKAM
New hotel progress: 68/100
Total unique hotels currently: 64

------------------------------------------------------------
NEW HOTEL 69/100
Hotel: FabHotel Nestlay Rooms Airport
Hotel ID: ChkI3aGO4veJqskoGg0vZy8xMW5nNnY5Z2s5EAE
Area: Velachery
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1821 rows | 65 unique hotels
SUCCESS: FabHotel Nestlay Rooms Airport
New hotel progress: 69/100
Total unique hotels currently: 65

------------------------------------------------------------
NEW HOTEL 70/100
Hotel: Aashi-Premium Serviced Apartments - Deluxe Double Room (2 Adults + 1 Child)
Hotel ID: ChoQhMOe797qntqeARoNL2cvMTF6eGhyazNzZhAC
Area: Velachery
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found. Hotel information saved.
Dataset saved: 1821 rows | 65 unique hotels
SUCCESS: Aashi-Premium Serviced Apartments - Deluxe Double Room (2 Adults + 1 Child)
New hotel progress: 70/100
Total unique hotels currently: 65

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 71/100
Hotel: Trendz service apartments - Standard Double or Twin Room with Balcony
Hotel ID: ChkQ39KshOyCo5lcGg0vZy8xMW53NTQ1MHF4EAI
Area: Velachery
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found. Hotel information saved.
Dataset saved: 1821 rows | 65 unique hotels
SUCCESS: Trendz service apartments - Standard Double or Twin Room with Balcony
New hotel progress: 71/100
Total unique hotels currently: 65

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCH AREA: Guindy
Progress: 71/100 new hotels
======================================================================
Hotels returned: 18
SKIP EXISTING: Hablis - A Business Hotel In Chennal

------------------------------------------------------------
NEW HOTEL 72/100
Hotel: Layalee Grande Hotel Chennai
Hotel ID: ChoIv5aFkIve8MmLARoNL2cvMTF0dDEwaF9fNxAB
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1851 rows | 66 unique hotels
SUCCESS: Layalee Grande Hotel Chennai
New hotel progress: 72/100
Total unique hotels currently: 66
SKIP EXISTING: Bloom Hub | Guindy

------------------------------------------------------------
NEW HOTEL 73/100
Hotel: HOTEL KINGS PALACE
Hotel ID: ChoIvKjd1LXc68TnARoNL2cvMTF0NjZmY3BfeRAB
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1881 rows | 67 unique hotels
SUCCESS: HOTEL KINGS PALACE
New hotel progress: 73/100
Total unique hotels currently: 67

------------------------------------------------------------
NEW HOTEL 74/100
Hotel: Hotel Beebiz Guindy
Hotel ID: ChkIoaivv7adv_h-Gg0vZy8xMWRfNzRuNzRsEAE
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1911 rows | 68 unique hotels
SUCCESS: Hotel Beebiz Guindy
New hotel progress: 74/100
Total unique hotels currently: 68
SKIP EXISTING: Ramada Plaza by Wyndham Chennai

------------------------------------------------------------
NEW HOTEL 75/100
Hotel: Le Royal Méridien Chennai
Hotel ID: ChYIvMj6rq_H-Z8QGgovbS8waGhxYnFtEAE
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1941 rows | 69 unique hotels
SUCCESS: Le Royal Méridien Chennai
New hotel progress: 75/100
Total unique hotels currently: 69

------------------------------------------------------------
NEW HOTEL 76/100
Hotel: Lemon Tree Hotel, Guindy, Chennai
Hotel ID: ChgI-uqRmtDarpXLARoLL2cvMXRkMHI5Z3cQAQ
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1971 rows | 70 unique hotels
SUCCESS: Lemon Tree Hotel, Guindy, Chennai
New hotel progress: 76/100
Total unique hotels currently: 70
SKIP EXISTING: Pine Tree Signature
SKIP EXISTING: Ginger Chennai (Tharamani, IITM)

------------------------------------------------------------
NEW HOTEL 77/100
Hotel: Urban Comforts Chennai
Hotel ID: ChkIyuuFhaS13uhsGg0vZy8xMXlrd2hxNDBjEAE
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2001 rows | 71 unique hotels
SUCCESS: Urban Comforts Chennai
New hotel progress: 77/100
Total unique hotels currently: 71
SKIP EXISTING: BOULEVARD by Design Hotel Chennai

------------------------------------------------------------
NEW HOTEL 78/100
Hotel: Balaji Residency Guindy
Hotel ID: ChkI94HS0PySn_5XGg0vZy8xMW5keTEzOXdfEAE
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2031 rows | 72 unique hotels
SUCCESS: Balaji Residency Guindy
New hotel progress: 78/100
Total unique hotels currently: 72

------------------------------------------------------------
NEW HOTEL 79/100
Hotel: Treebo Vapr Guindy Ekkatuthangal
Hotel ID: ChoI04em56XA6rnWARoNL2cvMTFyOHg0ZHR5XxAB
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2061 rows | 73 unique hotels
SUCCESS: Treebo Vapr Guindy Ekkatuthangal
New hotel progress: 79/100
Total unique hotels currently: 73

------------------------------------------------------------
NEW HOTEL 80/100
Hotel: Mount Kailash Suites Saidapet Chennai
Hotel ID: ChkI9-iHx7qx0-YrGg0vZy8xMWM0Nmp6XzFqEAE
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2091 rows | 74 unique hotels
SUCCESS: Mount Kailash Suites Saidapet Chennai
New hotel progress: 80/100
Total unique hotels currently: 74

------------------------------------------------------------
NEW HOTEL 81/100
Hotel: Kolam Dingai Serviced Residence
Hotel ID: ChoIhY3vuO2enNWaARoNL2cvMTF5cW5xOHJtbRAB
Area: Guindy
------------------------------------------------------------
Reviews collected: 11
Dataset saved: 2102 rows | 75 unique hotels
SUCCESS: Kolam Dingai Serviced Residence
New hotel progress: 81/100
Total unique hotels currently: 75

------------------------------------------------------------
NEW HOTEL 82/100
Hotel: Klase Hotels - hotels near chennai airport
Hotel ID: ChkIgOOysuKR8JAjGg0vZy8xMWZiMF81amhyEAE
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2132 rows | 76 unique hotels
SUCCESS: Klase Hotels - hotels near chennai airport
New hotel progress: 82/100
Total unique hotels currently: 76

------------------------------------------------------------
NEW HOTEL 83/100
Hotel: Park Hyatt Chennai
Hotel ID: ChYIyf-gpfGGzL5RGgovbS8wbjUzYzAxEAE
Area: Guindy
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2162 rows | 77 unique hotels
SUCCESS: Park Hyatt Chennai
New hotel progress: 83/100
Total unique hotels currently: 77


======================================================================
SEARCH AREA: Nungambakkam
Progress: 83/100 new hotels
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 84/100
Hotel: UPAR Hotels Nungambakkam
Hotel ID: ChoIwqCh26q4hbvDARoNL2cvMTFuN2tjOXdiYxAB
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2192 rows | 78 unique hotels
SUCCESS: UPAR Hotels Nungambakkam
New hotel progress: 84/100
Total unique hotels currently: 78
SKIP EXISTING: Park Elanza

------------------------------------------------------------
NEW HOTEL 85/100
Hotel: Park Avenue Hotel, Chennai
Hotel ID: ChkI2qij94HkzZPsARoML2cvMXB3ZmJneXk1EAE
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2222 rows | 79 unique hotels
SUCCESS: Park Avenue Hotel, Chennai
New hotel progress: 85/100
Total unique hotels currently: 79

------------------------------------------------------------
NEW HOTEL 86/100
Hotel: The Kings Park Grand
Hotel ID: ChkIv8GMwJDkhYo0Gg0vZy8xMXB6MDEwOHh4EAE
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2252 rows | 80 unique hotels
SUCCESS: The Kings Park Grand
New hotel progress: 86/100
Total unique hotels currently: 80

------------------------------------------------------------
NEW HOTEL 87/100
Hotel: Century Courtyard
Hotel ID: ChkI6uvJnLH6uaFyGg0vZy8xMW5tc254OHZtEAE
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2282 rows | 81 unique hotels
SUCCESS: Century Courtyard
New hotel progress: 87/100
Total unique hotels currently: 81

------------------------------------------------------------
NEW HOTEL 88/100
Hotel: Treebo Nestlay Rooms Nungambakkam
Hotel ID: ChkIsO7HqN7fv_JGGg0vZy8xMXZzMjJtemx2EAE
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2312 rows | 82 unique hotels
SUCCESS: Treebo Nestlay Rooms Nungambakkam
New hotel progress: 88/100
Total unique hotels currently: 82

------------------------------------------------------------
NEW HOTEL 89/100
Hotel: Harrisons Hotel
Hotel ID: ChkI5dfUlvGPldtYGg0vZy8xMWJ0dDVzM3I2EAE
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: Harrisons Hotel
New hotel progress: 89/100
Total unique hotels currently: 83
SKIP EXISTING: SEASON 4 RESIDENCES - NUNGAMBAKKAM

------------------------------------------------------------
NEW HOTEL 90/100
Hotel: Pine Tree Hotel
Hotel ID: ChkI0OSV3pHL08AsGg0vZy8xMWNrdmg0YzhkEAE
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkI0OSV3pHL08AsGg0vZy8xMWNrdmg0YzhkEAE&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.
Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: Pine Tree Hotel
New hotel progress: 90/100
Total unique hotels currently: 83

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 91/100
Hotel: The Park Chennai
Hotel ID: ChcI7d_9nMiv3Z_CARoKL20vMGhodDBiaxAB
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChcI7d_9nMiv3Z_CARoKL20vMGhodDBiaxAB&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.
Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: The Park Chennai
New hotel progress: 91/100
Total unique hotels currently: 83

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 92/100
Hotel: Royal Luxe Business Class Hotel
Hotel ID: ChoIrs-2guDd8IeYARoNL2cvMTF3OW5temIwYhAB
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChoIrs-2guDd8IeYARoNL2cvMTF3OW5temIwYhAB&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: Royal Luxe Business Class Hotel
New hotel progress: 92/100
Total unique hotels currently: 83

------------------------------------------------------------
NEW HOTEL 93/100
Hotel: Redstone Hotel
Hotel ID: ChoIjrXbjfu61IjnARoNL2cvMTFzNm00anlfNBAB
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChoIjrXbjfu61IjnARoNL2cvMTFzNm00anlfNBAB&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.
Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: Redstone Hotel
New hotel progress: 93/100
Total unique hotels currently: 83

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 94/100
Hotel: Pharos Hotels
Hotel ID: ChoI0IiTmePmrqjmARoNL2cvMTFzNGd6bjg1dhAB
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChoI0IiTmePmrqjmARoNL2cvMTFzNGd6bjg1dhAB&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.
Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: Pharos Hotels
New hotel progress: 94/100
Total unique hotels currently: 83

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 95/100
Hotel: Gulnaar Inn
Hotel ID: ChkIuaSSz5Ckm4dOGg0vZy8xMWdoZmdfbW1fEAE
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkIuaSSz5Ckm4dOGg0vZy8xMWdoZmdfbW1fEAE&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.
Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: Gulnaar Inn
New hotel progress: 95/100
Total unique hotels currently: 83

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 96/100
Hotel: Taj Coromandel, Chennai
Hotel ID: ChcI8fT3oo2YudLCARoKL20vMGhocWxudhAB
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChcI8fT3oo2YudLCARoKL20vMGhocWxudhAB&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.
Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: Taj Coromandel, Chennai
New hotel progress: 96/100
Total unique hotels currently: 83

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 97/100
Hotel: Sweet Memories stay
Hotel ID: ChkI2O7Ghu614v0_Gg0vZy8xMWpxc25iNHdsEAE
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkI2O7Ghu614v0_Gg0vZy8xMWpxc25iNHdsEAE&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: Sweet Memories stay
New hotel progress: 97/100
Total unique hotels currently: 83

------------------------------------------------------------
NEW HOTEL 98/100
Hotel: Treebo Pechis Castle
Hotel ID: ChoIkrOgloGSjYnUARoNL2cvMTFnOXZtazQzORAB
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChoIkrOgloGSjYnUARoNL2cvMTFnOXZtazQzORAB&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: Treebo Pechis Castle
New hotel progress: 98/100
Total unique hotels currently: 83

------------------------------------------------------------
NEW HOTEL 99/100
Hotel: The Belstead Hotel
Hotel ID: ChkIyqe8hYKInMY8Gg0vZy8xMWR4bGdjc2dfEAE
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkIyqe8hYKInMY8Gg0vZy8xMWR4bGdjc2dfEAE&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.
Dataset saved: 2342 rows | 83 unique hotels
SUCCESS: The Belstead Hotel
New hotel progress: 99/100
Total unique hotels currently: 83

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 100/100
Hotel: Sweet Memories- Perfect home stay - Superior Double Room
Hotel ID: ChkQwZjQqO6bmoYtGg0vZy8xMXRnZ3ByNDJmEAI
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkQwZjQqO6bmoYtGg0vZy8xMXRnZ3ByNDJmEAI&hl=en&sort_by=2&api_key=8d59aa17fa2898d550e74c1f16359c11330612a259078cc83a930061089f75b1
No reviews found. Hotel information saved.
Dataset saved: 2342 rows | 83 unique hotels

/tmp/ipykernel_1058/1236986249.py:967: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

SUCCESS: Sweet Memories- Perfect home stay - Superior Double Room
New hotel progress: 100/100
Total unique hotels currently: 83
Dataset saved: 2342 rows | 83 unique hotels


======================================================================
CHENNAI SCRAPING COMPLETED
======================================================================
New hotels collected: 100
Total unique hotels: 83
Total dataset rows: 2342
Output file: chennai_hotel_dataset.csv
Checkpoint file: chennai_100_new_checkpoint.csv
======================================================================

FINAL HOTEL COUNT
Unique hotels: 83
Total review/data rows: 2342

Dataset is ready.

In [ ]:
from google.colab import files

files.download("chennai_hotel_dataset.csv")

In [ ]:
import os
import time
import requests
import pandas as pd

# ============================================================
# CONFIGURATION
# ============================================================

API_KEY = input("Enter your SerpApi API key: ").strip()

# IMPORTANT:
# Keep using the SAME dataset file
OUTPUT_FILE = "chennai_hotel_dataset.csv"

# NEW checkpoint for this batch
CHECKPOINT_FILE = "chennai_next_100_checkpoint.csv"

CITY = "Chennai"

# ============================================================
# IMPORTANT
# ============================================================
# Your current dataset has 83 unique hotels.
#
# We now want 100 MORE NEW hotels.
#
# Expected final:
#
# 83 existing + 100 new = 183 unique hotels
# ============================================================

TARGET_NEW_HOTELS = 100

# Maximum review pages per hotel
MAX_REVIEW_PAGES = 3

BASE_URL = "https://serpapi.com/search.json"


# ============================================================
# CHENNAI SEARCH AREAS
# ============================================================

CHENNAI_AREAS = [

    # Central Chennai
    "Central Chennai",
    "Chennai Central",
    "Mount Road",
    "George Town",
    "Broadway",
    "Royapuram",
    "Washermenpet",

    # South / Central
    "T Nagar",
    "Nungambakkam",
    "Egmore",
    "Mylapore",
    "Alwarpet",
    "Royapettah",
    "Triplicane",
    "Chetpet",
    "Kilpauk",
    "Purasawalkam",
    "Saidapet",

    # West Chennai
    "Anna Nagar",
    "Mogappair",
    "Ambattur",
    "Avadi",
    "Poonamallee",
    "Porur",
    "Ramapuram",
    "Manapakkam",
    "Vadapalani",
    "Kodambakkam",
    "Ashok Nagar",
    "Koyambedu",

    # South Chennai
    "Guindy",
    "Adyar",
    "Besant Nagar",
    "Thiruvanmiyur",
    "Kotturpuram",
    "Madhya Kailash",
    "Velachery",
    "Pallikaranai",
    "Medavakkam",
    "Perumbakkam",

    # OMR
    "OMR",
    "Perungudi",
    "Thoraipakkam",
    "Karapakkam",
    "Sholinganallur",
    "Navalur",
    "Siruseri",

    # ECR
    "ECR",
    "Neelankarai",
    "Palavakkam",
    "Kottivakkam",
    "Kottivakkam ECR",
    "Injambakkam",

    # Tambaram side
    "Tambaram",
    "Chromepet",
    "Pallavaram",
    "Pammal",

    # Airport
    "Chennai Airport",

    # Northern / outer Chennai
    "Perambur",
    "Tondiarpet",
    "Madhavaram",
    "Red Hills",

    # Other important areas
    "Shenoy Nagar",
    "Aminjikarai",
    "Choolaimedu",
    "Nandanam",
    "Teynampet",
    "Thousand Lights",
    "Little Mount"
]

# Remove duplicate areas
CHENNAI_AREAS = list(
    dict.fromkeys(CHENNAI_AREAS)
)


# ============================================================
# LOAD EXISTING DATASET
# ============================================================

if os.path.exists(OUTPUT_FILE):

    df = pd.read_csv(
        OUTPUT_FILE
    )

    print("\n" + "=" * 70)
    print("EXISTING CHENNAI DATASET")
    print("=" * 70)

    print(
        f"Existing records: {len(df)}"
    )

else:

    print(
        f"\nERROR: {OUTPUT_FILE} not found."
    )

    print(
        "Make sure your existing Chennai CSV is "
        "uploaded to Colab."
    )

    raise FileNotFoundError(
        OUTPUT_FILE
    )


# ============================================================
# CHECK HOTEL_ID COLUMN
# ============================================================

if "hotel_id" not in df.columns:

    raise ValueError(
        "The dataset does not contain a 'hotel_id' column."
    )


# ============================================================
# GET EXISTING UNIQUE HOTEL IDS
# ============================================================

df["hotel_id"] = (
    df["hotel_id"]
    .astype(str)
)

existing_hotel_ids = set(
    df["hotel_id"]
    .dropna()
    .astype(str)
)


# Remove possible "nan"
existing_hotel_ids.discard(
    "nan"
)


print(
    f"Existing unique hotels: "
    f"{len(existing_hotel_ids)}"
)

print(
    f"New hotels required: "
    f"{TARGET_NEW_HOTELS}"
)

print(
    f"Expected final unique hotels: "
    f"{len(existing_hotel_ids) + TARGET_NEW_HOTELS}"
)

print("=" * 70)


# ============================================================
# LOAD NEW CHECKPOINT
# ============================================================

if os.path.exists(CHECKPOINT_FILE):

    checkpoint = pd.read_csv(
        CHECKPOINT_FILE
    )

    if not checkpoint.empty:

        completed_hotels = set(
            checkpoint.loc[
                checkpoint["status"] == "completed",
                "hotel_id"
            ]
            .astype(str)
        )

    else:

        completed_hotels = set()

    print(
        f"Hotels already completed in this batch: "
        f"{len(completed_hotels)}"
    )

else:

    checkpoint = pd.DataFrame(
        columns=[
            "hotel_id",
            "hotel_name",
            "search_area",
            "status"
        ]
    )

    completed_hotels = set()

    print(
        "No previous checkpoint found. "
        "Starting this batch fresh."
    )


# ============================================================
# PREVENT OLD CHECKPOINT HOTELS FROM BEING ADDED AGAIN
# ============================================================

known_hotel_ids = (
    existing_hotel_ids |
    completed_hotels
)


# ============================================================
# SAVE CHECKPOINT
# ============================================================

def save_checkpoint(
    hotel_id,
    hotel_name,
    search_area,
    status
):

    global checkpoint

    hotel_id = str(
        hotel_id
    )

    # Remove previous record for this hotel
    checkpoint = checkpoint[
        checkpoint["hotel_id"].astype(str)
        != hotel_id
    ]

    new_row = pd.DataFrame([
        {
            "hotel_id":
                hotel_id,

            "hotel_name":
                hotel_name,

            "search_area":
                search_area,

            "status":
                status
        }
    ])

    checkpoint = pd.concat(
        [
            checkpoint,
            new_row
        ],
        ignore_index=True
    )

    checkpoint.to_csv(
        CHECKPOINT_FILE,
        index=False
    )


# ============================================================
# SAVE DATASET
# ============================================================

def save_dataset():

    global df

    # Ensure hotel IDs are strings
    if "hotel_id" in df.columns:

        df["hotel_id"] = (
            df["hotel_id"]
            .astype(str)
        )

    # Remove duplicate reviews
    if "review_id" in df.columns:

        df = df.drop_duplicates(
            subset=["review_id"]
        )

    else:

        df = df.drop_duplicates()

    # Save
    df.to_csv(
        OUTPUT_FILE,
        index=False
    )

    print(
        f"Dataset saved: "
        f"{len(df)} records | "
        f"{df['hotel_id'].nunique()} unique hotels"
    )


# ============================================================
# SEARCH HOTELS USING SERPAPI
# ============================================================

def search_hotels(search_area):

    params = {

        "engine":
            "google_hotels",

        "q":
            f"Hotels in {search_area}, Chennai",

        "check_in_date":
            "2026-10-15",

        "check_out_date":
            "2026-10-16",

        "adults":
            "2",

        "currency":
            "INR",

        "gl":
            "in",

        "hl":
            "en",

        "api_key":
            API_KEY
    }

    response = requests.get(
        BASE_URL,
        params=params,
        timeout=60
    )

    response.raise_for_status()

    data = response.json()

    if "error" in data:

        print(
            f"SerpApi error: "
            f"{data['error']}"
        )

        return []

    return data.get(
        "properties",
        []
    )


# ============================================================
# EXTRACT LOCATION
# ============================================================

def extract_location(hotel):

    gps = hotel.get(
        "gps_coordinates"
    )

    if gps:

        latitude = gps.get(
            "latitude"
        )

        longitude = gps.get(
            "longitude"
        )

        if (
            latitude is not None
            and
            longitude is not None
        ):

            return (
                f"Latitude: {latitude}, "
                f"Longitude: {longitude}"
            )

    return hotel.get(
        "address",
        ""
    )


# ============================================================
# EXTRACT AMENITIES
# ============================================================

def extract_amenities(hotel):

    amenities = []

    for amenity in hotel.get(
        "amenities",
        []
    ):

        if isinstance(
            amenity,
            str
        ):

            amenities.append(
                amenity
            )

        elif isinstance(
            amenity,
            dict
        ):

            name = (
                amenity.get("name")
                or
                amenity.get("title")
            )

            if name:

                amenities.append(
                    str(name)
                )

    # Remove duplicate amenities
    amenities = list(
        dict.fromkeys(
            amenities
        )
    )

    return " | ".join(
        amenities
    )


# ============================================================
# EXTRACT PRICE
# ============================================================

def extract_price(hotel):

    price = hotel.get(
        "rate_per_night",
        {}
    )

    if isinstance(
        price,
        dict
    ):

        value = (
            price.get("lowest")
            or
            price.get("extracted_lowest")
        )

        if value is not None:

            return value

    # Alternative field
    if hotel.get(
        "price"
    ) is not None:

        return hotel.get(
            "price"
        )

    return None


# ============================================================
# CREATE HOTEL ROW
# ============================================================

def make_hotel_row(
    hotel,
    search_area
):

    hotel_id = (
        hotel.get(
            "property_token"
        )
        or
        hotel.get(
            "hotel_id"
        )
    )

    hotel_name = hotel.get(
        "name",
        "Unknown Hotel"
    )

    gps = hotel.get(
        "gps_coordinates",
        {}
    )

    latitude = gps.get(
        "latitude"
    )

    longitude = gps.get(
        "longitude"
    )

    return {

        "hotel_name":
            hotel_name,

        "hotel_id":
            str(hotel_id),

        "city":
            CITY,

        "location":
            extract_location(
                hotel
            ),

        "latitude":
            latitude,

        "longitude":
            longitude,

        "price_per_night":
            extract_price(
                hotel
            ),

        "hotel_category":
            hotel.get(
                "hotel_class"
            ),

        "customer_rating":
            hotel.get(
                "overall_rating"
            ),

        "review_count":
            hotel.get(
                "reviews"
            ),

        "amenities":
            extract_amenities(
                hotel
            ),

        "review_text":
            "",

        "individual_review_rating":
            None,

        "review_date":
            "",

        "review_source":
            "Google Hotels via SerpApi",

        "search_area":
            search_area,

        "review_id":
            ""
    }


# ============================================================
# FETCH REVIEWS
# ============================================================

def fetch_reviews(
    hotel,
    search_area
):

    hotel_id = (
        hotel.get(
            "property_token"
        )
        or
        hotel.get(
            "hotel_id"
        )
    )

    hotel_name = hotel.get(
        "name",
        "Unknown Hotel"
    )

    if not hotel_id:

        return []

    hotel_id = str(
        hotel_id
    )

    all_reviews = []

    next_page_token = None


    # ========================================================
    # REVIEW PAGES
    # ========================================================

    for page in range(
        1,
        MAX_REVIEW_PAGES + 1
    ):

        params = {

            "engine":
                "google_hotels_reviews",

            "property_token":
                hotel_id,

            "hl":
                "en",

            "sort_by":
                "2",

            "api_key":
                API_KEY
        }


        # Add pagination token
        if next_page_token:

            params[
                "next_page_token"
            ] = next_page_token


        try:

            response = requests.get(
                BASE_URL,
                params=params,
                timeout=60
            )

            response.raise_for_status()

            data = response.json()

        except Exception as e:

            print(
                f"Review request failed: {e}"
            )

            break


        # SerpApi error
        if "error" in data:

            print(
                f"Review API error: "
                f"{data['error']}"
            )

            break


        reviews = data.get(
            "reviews",
            []
        )


        # No reviews
        if not reviews:

            break


        # ====================================================
        # PROCESS REVIEWS
        # ====================================================

        for index, review in enumerate(
            reviews
        ):

            # -----------------------------------------------
            # REVIEW ID
            # -----------------------------------------------

            review_id = (
                review.get(
                    "review_id"
                )
                or
                review.get(
                    "id"
                )
            )

            # Create fallback ID
            if not review_id:

                review_id = (
                    f"{hotel_id}_"
                    f"{page}_"
                    f"{index}"
                )


            # -----------------------------------------------
            # REVIEW RATING
            # -----------------------------------------------

            review_rating = (
                review.get(
                    "rating"
                )
                or
                review.get(
                    "overall_rating"
                )
            )


            # -----------------------------------------------
            # REVIEW TEXT
            # -----------------------------------------------

            review_text = (

                review.get(
                    "snippet"
                )

                or

                review.get(
                    "text"
                )

                or

                review.get(
                    "review_text"
                )

                or
                ""
            )


            # -----------------------------------------------
            # REVIEW DATE
            # -----------------------------------------------

            review_date = (

                review.get(
                    "date"
                )

                or

                review.get(
                    "relative_date"
                )

                or
                ""
            )


            # -----------------------------------------------
            # CREATE ROW
            # -----------------------------------------------

            row = {

                "hotel_name":
                    hotel_name,

                "hotel_id":
                    hotel_id,

                "city":
                    CITY,

                "location":
                    extract_location(
                        hotel
                    ),

                "latitude":
                    hotel.get(
                        "gps_coordinates",
                        {}
                    ).get(
                        "latitude"
                    ),

                "longitude":
                    hotel.get(
                        "gps_coordinates",
                        {}
                    ).get(
                        "longitude"
                    ),

                "price_per_night":
                    extract_price(
                        hotel
                    ),

                "hotel_category":
                    hotel.get(
                        "hotel_class"
                    ),

                "customer_rating":
                    hotel.get(
                        "overall_rating"
                    ),

                "review_count":
                    hotel.get(
                        "reviews"
                    ),

                "amenities":
                    extract_amenities(
                        hotel
                    ),

                "review_text":
                    review_text,

                "individual_review_rating":
                    review_rating,

                "review_date":
                    review_date,

                "review_source":
                    "Google Hotels Reviews via SerpApi",

                "search_area":
                    search_area,

                "review_id":
                    review_id
            }

            all_reviews.append(
                row
            )


        # ====================================================
        # NEXT REVIEW PAGE
        # ====================================================

        next_page_token = (
            data.get(
                "serpapi_pagination",
                {}
            )
            .get(
                "next_page_token"
            )
        )


        if not next_page_token:

            break


        time.sleep(1)


    return all_reviews


# ============================================================
# MAIN SCRAPING PROCESS
# ============================================================

new_hotel_ids = set()

new_hotels_collected = 0


print("\n")
print("=" * 70)
print("STARTING CHENNAI - NEXT 100 NEW HOTELS")
print("=" * 70)

print(
    f"Existing unique hotels: "
    f"{len(existing_hotel_ids)}"
)

print(
    f"New hotels required: "
    f"{TARGET_NEW_HOTELS}"
)

print(
    f"Target after completion: "
    f"{len(existing_hotel_ids) + TARGET_NEW_HOTELS}"
)

print("=" * 70)


# ============================================================
# LOOP THROUGH AREAS
# ============================================================

for search_area in CHENNAI_AREAS:


    # Stop after 100 NEW hotels
    if (
        new_hotels_collected
        >=
        TARGET_NEW_HOTELS
    ):

        break


    print("\n")
    print("=" * 70)

    print(
        f"SEARCHING: {search_area}"
    )

    print(
        f"NEW HOTEL PROGRESS: "
        f"{new_hotels_collected}/"
        f"{TARGET_NEW_HOTELS}"
    )

    print("=" * 70)


    # ========================================================
    # SEARCH HOTELS
    # ========================================================

    try:

        hotels = search_hotels(
            search_area
        )

    except Exception as e:

        print(
            f"Hotel search failed: {e}"
        )

        continue


    print(
        f"Hotels returned: "
        f"{len(hotels)}"
    )


    # ========================================================
    # PROCESS HOTELS
    # ========================================================

    for hotel in hotels:


        # Stop at 100
        if (
            new_hotels_collected
            >=
            TARGET_NEW_HOTELS
        ):

            break


        # ====================================================
        # GET HOTEL ID
        # ====================================================

        hotel_id = (
            hotel.get(
                "property_token"
            )
            or
            hotel.get(
                "hotel_id"
            )
        )

        hotel_name = hotel.get(
            "name",
            "Unknown Hotel"
        )


        # No ID
        if not hotel_id:

            print(
                f"SKIP: {hotel_name} "
                f"- no hotel ID"
            )

            continue


        hotel_id = str(
            hotel_id
        )


        # ====================================================
        # SKIP EXISTING HOTEL
        # ====================================================

        if hotel_id in known_hotel_ids:

            print(
                f"SKIP EXISTING: "
                f"{hotel_name}"
            )

            continue


        # ====================================================
        # SKIP DUPLICATE IN THIS RUN
        # ====================================================

        if hotel_id in new_hotel_ids:

            continue


        # ====================================================
        # NEW HOTEL
        # ====================================================

        print("\n" + "-" * 60)

        print(
            f"NEW HOTEL "
            f"{new_hotels_collected + 1}/"
            f"{TARGET_NEW_HOTELS}"
        )

        print(
            f"Hotel: {hotel_name}"
        )

        print(
            f"Hotel ID: {hotel_id}"
        )

        print(
            f"Area: {search_area}"
        )

        print("-" * 60)


        # ====================================================
        # FETCH REVIEWS
        # ====================================================

        try:

            reviews = fetch_reviews(
                hotel,
                search_area
            )

        except Exception as e:

            print(
                f"Review collection failed: "
                f"{e}"
            )

            reviews = []


        # ====================================================
        # ADD REVIEWS
        # ====================================================

        if reviews:

            new_df = pd.DataFrame(
                reviews
            )

            df = pd.concat(
                [
                    df,
                    new_df
                ],
                ignore_index=True
            )

            print(
                f"Reviews collected: "
                f"{len(reviews)}"
            )


        # ====================================================
        # NO REVIEWS
        # ====================================================

        else:

            hotel_row = make_hotel_row(
                hotel,
                search_area
            )

            df = pd.concat(
                [
                    df,
                    pd.DataFrame([
                        hotel_row
                    ])
                ],
                ignore_index=True
            )

            print(
                "No reviews found."
            )

            print(
                "Hotel information saved."
            )


        # ====================================================
        # REMOVE DUPLICATE REVIEWS
        # ====================================================

        if "review_id" in df.columns:

            # Don't remove blank review IDs
            non_blank_review_ids = (
                df["review_id"]
                .fillna("")
                .astype(str)
                .str.strip()
                != ""
            )

            df_with_ids = df[
                non_blank_review_ids
            ].drop_duplicates(
                subset=["review_id"]
            )

            df_without_ids = df[
                ~non_blank_review_ids
            ]

            df = pd.concat(
                [
                    df_with_ids,
                    df_without_ids
                ],
                ignore_index=True
            )


        # ====================================================
        # SAVE IMMEDIATELY
        # ====================================================

        save_dataset()


        # ====================================================
        # UPDATE HOTEL TRACKING
        # ====================================================

        new_hotel_ids.add(
            hotel_id
        )

        existing_hotel_ids.add(
            hotel_id
        )

        known_hotel_ids.add(
            hotel_id
        )

        new_hotels_collected += 1


        # ====================================================
        # SAVE CHECKPOINT
        # ====================================================

        save_checkpoint(
            hotel_id,
            hotel_name,
            search_area,
            "completed"
        )


        # ====================================================
        # PROGRESS
        # ====================================================

        print(
            f"SUCCESS: {hotel_name}"
        )

        print(
            f"New hotels collected: "
            f"{new_hotels_collected}/"
            f"{TARGET_NEW_HOTELS}"
        )

        print(
            f"Total unique hotels now: "
            f"{df['hotel_id'].nunique()}"
        )

        print(
            f"Total records now: "
            f"{len(df)}"
        )


        # ====================================================
        # DELAY
        # ====================================================

        time.sleep(2)


# ============================================================
# FINAL SAVE
# ============================================================

save_dataset()


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("CHENNAI SCRAPING COMPLETED")
print("=" * 70)

print(
    f"New hotels collected: "
    f"{new_hotels_collected}"
)

print(
    f"Previous unique hotels: "
    f"{len(existing_hotel_ids) - new_hotels_collected}"
)

print(
    f"Total unique hotels: "
    f"{df['hotel_id'].nunique()}"
)

print(
    f"Total dataset rows: "
    f"{len(df)}"
)

print(
    f"Output file: "
    f"{OUTPUT_FILE}"
)

print(
    f"Checkpoint file: "
    f"{CHECKPOINT_FILE}"
)

print("=" * 70)


# ============================================================
# FINAL HOTEL COUNT
# ============================================================

print("\nFINAL HOTEL COUNT")

hotel_counts = (
    df.groupby(
        "hotel_id"
    )
    .size()
    .reset_index(
        name="review_rows"
    )
)


print(
    f"Unique hotels: "
    f"{len(hotel_counts)}"
)

print(
    f"Total review/data rows: "
    f"{len(df)}"
)


# ============================================================
# FINAL REVIEW STATISTICS
# ============================================================

if "review_text" in df.columns:

    review_text_count = (
        df["review_text"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
        .sum()
    )

    print(
        f"Records with review text: "
        f"{review_text_count}"
    )


if "individual_review_rating" in df.columns:

    review_rating_count = (
        df[
            "individual_review_rating"
        ]
        .notna()
        .sum()
    )

    print(
        f"Records with individual review rating: "
        f"{review_rating_count}"
    )


if "price_per_night" in df.columns:

    price_count = (
        df[
            "price_per_night"
        ]
        .notna()
        .sum()
    )

    print(
        f"Records with price: "
        f"{price_count}"
    )


print("\n" + "=" * 70)
print("DATASET IS READY")
print("=" * 70)

Enter your SerpApi API key: 419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58

======================================================================
EXISTING CHENNAI DATASET
======================================================================
Existing records: 2342
Existing unique hotels: 83
New hotels required: 100
Expected final unique hotels: 183
======================================================================
No previous checkpoint found. Starting this batch fresh.


======================================================================
STARTING CHENNAI - NEXT 100 NEW HOTELS
======================================================================
Existing unique hotels: 83
New hotels required: 100
Target after completion: 183
======================================================================


======================================================================
SEARCHING: Central Chennai
NEW HOTEL PROGRESS: 0/100
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 1/100
Hotel: Four Points by Sheraton Chennai OMR
Hotel ID: ChkIi-yZ2cj-tp8EGg0vZy8xMWZodHpkcnAzEAE
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2372 records | 84 unique hotels
SUCCESS: Four Points by Sheraton Chennai OMR
New hotels collected: 1/100
Total unique hotels now: 84
Total records now: 2372

------------------------------------------------------------
NEW HOTEL 2/100
Hotel: Ramada by Wyndham Chennai Egmore
Hotel ID: ChkIrsnv9YKcxYawARoML2cvMTFfcXljbno5EAE
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2402 records | 85 unique hotels
SUCCESS: Ramada by Wyndham Chennai Egmore
New hotels collected: 2/100
Total unique hotels now: 85
Total records now: 2402
SKIP EXISTING: The Hydel Park (Business Class Hotel) Chennai

------------------------------------------------------------
NEW HOTEL 3/100
Hotel: The Madras Grand - Hotel Egmore
Hotel ID: ChkI2-mPuoyJkIw0Gg0vZy8xMW5feHdsbXlzEAE
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2432 records | 86 unique hotels
SUCCESS: The Madras Grand - Hotel Egmore
New hotels collected: 3/100
Total unique hotels now: 86
Total records now: 2432

------------------------------------------------------------
NEW HOTEL 4/100
Hotel: GM Residency
Hotel ID: ChoIqsfUrrnAmrDbARoNL2cvMTFtNWYxYnMxdBAB
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2462 records | 87 unique hotels
SUCCESS: GM Residency
New hotels collected: 4/100
Total unique hotels now: 87
Total records now: 2462
SKIP EXISTING: Leisure Stays - Premium Suites - Three-Bedroom Apartment

------------------------------------------------------------
NEW HOTEL 5/100
Hotel: JP Hotel Chennai
Hotel ID: ChoIuO-FgaDr_aPnARoNL2cvMTFmeTkyajMyNhAB
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2492 records | 88 unique hotels
SUCCESS: JP Hotel Chennai
New hotels collected: 5/100
Total unique hotels now: 88
Total records now: 2492

------------------------------------------------------------
NEW HOTEL 6/100
Hotel: The Pride Fort Hotel
Hotel ID: ChoImJrkuNnypev0ARoNL2cvMTFoNG5oeGw5YhAB
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2522 records | 89 unique hotels
SUCCESS: The Pride Fort Hotel
New hotels collected: 6/100
Total unique hotels now: 89
Total records now: 2522

------------------------------------------------------------
NEW HOTEL 7/100
Hotel: Holiday Inn Express Chennai Omr Thoraipakkam, an IHG Hotel
Hotel ID: ChkI08uDs_CYoa8DGg0vZy8xMWY5eGx0OGZ0EAE
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2552 records | 90 unique hotels
SUCCESS: Holiday Inn Express Chennai Omr Thoraipakkam, an IHG Hotel
New hotels collected: 7/100
Total unique hotels now: 90
Total records now: 2552

------------------------------------------------------------
NEW HOTEL 8/100
Hotel: Pride Premier Chennai
Hotel ID: ChgI74rQ0LXxrJPhARoLL2cvMXRxNmJ5NHEQAQ
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2582 records | 91 unique hotels
SUCCESS: Pride Premier Chennai
New hotels collected: 8/100
Total unique hotels now: 91
Total records now: 2582

------------------------------------------------------------
NEW HOTEL 9/100
Hotel: Lemon Tree Hotel, Shimona Chennai
Hotel ID: ChoI472qjYmgzqyEARoNL2cvMTFiNXBodDJzZhAB
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2612 records | 92 unique hotels
SUCCESS: Lemon Tree Hotel, Shimona Chennai
New hotels collected: 9/100
Total unique hotels now: 92
Total records now: 2612

------------------------------------------------------------
NEW HOTEL 10/100
Hotel: The Nest Lovely 3BHK and 1BHK Villa - One-Bedroom Villa
Hotel ID: ChkQ8u7VyaCSwvh3Gg0vZy8xMXo0czl3eTNmEAI
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 16
Dataset saved: 2628 records | 93 unique hotels
SUCCESS: The Nest Lovely 3BHK and 1BHK Villa - One-Bedroom Villa
New hotels collected: 10/100
Total unique hotels now: 93
Total records now: 2628

------------------------------------------------------------
NEW HOTEL 11/100
Hotel: Hotel Greenpark Chennai
Hotel ID: ChoI7-jihInXvczJARoNL2cvMTFjNjd2a19rYhAB
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2658 records | 94 unique hotels
SUCCESS: Hotel Greenpark Chennai
New hotels collected: 11/100
Total unique hotels now: 94
Total records now: 2658

------------------------------------------------------------
NEW HOTEL 12/100
Hotel: Raj Park Hotel Chennai
Hotel ID: ChoIisqCmpLvpsutARoNL2cvMTFiNmc4djdmbRAB
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2688 records | 95 unique hotels
SUCCESS: Raj Park Hotel Chennai
New hotels collected: 12/100
Total unique hotels now: 95
Total records now: 2688

------------------------------------------------------------
NEW HOTEL 13/100
Hotel: Ramada Plaza by Wyndham Chennai
Hotel ID: ChkIlpuNgpuVu-stGg0vZy8xMWRfdGxqMWR0EAE
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2718 records | 96 unique hotels
SUCCESS: Ramada Plaza by Wyndham Chennai
New hotels collected: 13/100
Total unique hotels now: 96
Total records now: 2718
SKIP EXISTING: Hanu Reddy Residences - Nawab Habibullah Avenue - Deluxe Double Room

------------------------------------------------------------
NEW HOTEL 14/100
Hotel: JJS PARK INN
Hotel ID: ChkIvcy11daImLcVGg0vZy8xMWZrZjkxdDczEAE
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2748 records | 97 unique hotels
SUCCESS: JJS PARK INN
New hotels collected: 14/100
Total unique hotels now: 97
Total records now: 2748

------------------------------------------------------------
NEW HOTEL 15/100
Hotel: Hanu Reddy Residences, Nawab Habibullah Avenue - Boutique Urban Retreat - Superior Double Room
Hotel ID: ChoQ1u-PjY6Y3aPCARoNL2cvMTF0eHFsZDlxXxAC
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 8
Dataset saved: 2756 records | 98 unique hotels
SUCCESS: Hanu Reddy Residences, Nawab Habibullah Avenue - Boutique Urban Retreat - Superior Double Room
New hotels collected: 15/100
Total unique hotels now: 98
Total records now: 2756

------------------------------------------------------------
NEW HOTEL 16/100
Hotel: Grand Cascade Hotels
Hotel ID: ChkInbKSkoDr7-8MGg0vZy8xMWNsX2ticDAwEAE
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2786 records | 99 unique hotels
SUCCESS: Grand Cascade Hotels
New hotels collected: 16/100
Total unique hotels now: 99
Total records now: 2786

------------------------------------------------------------
NEW HOTEL 17/100
Hotel: Hotel Southern Comfort
Hotel ID: ChoIrrWJ84T2iZTgARoNL2cvMTFjNTVyM2RudBAB
Area: Central Chennai
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2816 records | 100 unique hotels
SUCCESS: Hotel Southern Comfort
New hotels collected: 17/100
Total unique hotels now: 100
Total records now: 2816


======================================================================
SEARCHING: Chennai Central
NEW HOTEL PROGRESS: 17/100
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 18/100
Hotel: Sheraton Grande Hotel
Hotel ID: ChkIl5jYvu790JcSGg0vZy8xMXN6Zng0M3RoEAE
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2846 records | 101 unique hotels
SUCCESS: Sheraton Grande Hotel
New hotels collected: 18/100
Total unique hotels now: 101
Total records now: 2846
SKIP EXISTING: The Hydel Park (Business Class Hotel) Chennai

------------------------------------------------------------
NEW HOTEL 19/100
Hotel: Stay Court (Business Class Hotel)
Hotel ID: ChkI0OuzxNrXzeccGg0vZy8xMXB3M3puczI1EAE
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2876 records | 102 unique hotels
SUCCESS: Stay Court (Business Class Hotel)
New hotels collected: 19/100
Total unique hotels now: 102
Total records now: 2876

------------------------------------------------------------
NEW HOTEL 20/100
Hotel: Sarovar Inn
Hotel ID: ChoIs8qepM2Rl8CSARoNL2cvMTFqNWJsdHc4chAB
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2906 records | 103 unique hotels
SUCCESS: Sarovar Inn
New hotels collected: 20/100
Total unique hotels now: 103
Total records now: 2906

------------------------------------------------------------
NEW HOTEL 21/100
Hotel: Liza Regency - Hotel & Restaurant
Hotel ID: ChoI1LX-q7C5_9e9ARoNL2cvMTFnNndmeDI4bhAB
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2936 records | 104 unique hotels
SUCCESS: Liza Regency - Hotel & Restaurant
New hotels collected: 21/100
Total unique hotels now: 104
Total records now: 2936

------------------------------------------------------------
NEW HOTEL 22/100
Hotel: The Park Avenue Hotel
Hotel ID: ChkIsoLUr_HGnZBQGg0vZy8xMWtqOHdka3ZuEAE
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2966 records | 105 unique hotels
SUCCESS: The Park Avenue Hotel
New hotels collected: 22/100
Total unique hotels now: 105
Total records now: 2966

------------------------------------------------------------
NEW HOTEL 23/100
Hotel: Bloom Hotel - Chennai Central
Hotel ID: ChkIypLZ3Ijm8PkeGg0vZy8xMW5qd3pnajZjEAE
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2996 records | 106 unique hotels
SUCCESS: Bloom Hotel - Chennai Central
New hotels collected: 23/100
Total unique hotels now: 106
Total records now: 2996

------------------------------------------------------------
NEW HOTEL 24/100
Hotel: Hotel AKMG Towers - Chennai
Hotel ID: ChkIwY2arcmNs4Q2Gg0vZy8xMXRwOXpibHM3EAE
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3026 records | 107 unique hotels
SUCCESS: Hotel AKMG Towers - Chennai
New hotels collected: 24/100
Total unique hotels now: 107
Total records now: 3026
SKIP EXISTING: Grand Cascade Hotels

------------------------------------------------------------
NEW HOTEL 25/100
Hotel: Sun City Chennai
Hotel ID: ChoIhY6EjaWC-tryARoNL2cvMTFwdjJ4M3NkNBAB
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3056 records | 108 unique hotels
SUCCESS: Sun City Chennai
New hotels collected: 25/100
Total unique hotels now: 108
Total records now: 3056

------------------------------------------------------------
NEW HOTEL 26/100
Hotel: Hotel Greens Gate
Hotel ID: ChoI2IDSlvuzlc2cARoNL2cvMTFidG1xcWpxXxAB
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3086 records | 109 unique hotels
SUCCESS: Hotel Greens Gate
New hotels collected: 26/100
Total unique hotels now: 109
Total records now: 3086

------------------------------------------------------------
NEW HOTEL 27/100
Hotel: Greens Estate
Hotel ID: ChkI5JCV6NiGzoM2Gg0vZy8xMXcya2dkeTM4EAE
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3116 records | 110 unique hotels
SUCCESS: Greens Estate
New hotels collected: 27/100
Total unique hotels now: 110
Total records now: 3116

------------------------------------------------------------
NEW HOTEL 28/100
Hotel: Orion Residency
Hotel ID: ChoI0JH41snSgJ7fARoNL2cvMTFiNnEzcHoxbhAB
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3146 records | 111 unique hotels
SUCCESS: Orion Residency
New hotels collected: 28/100
Total unique hotels now: 111
Total records now: 3146

------------------------------------------------------------
NEW HOTEL 29/100
Hotel: Liza Royale Hotel
Hotel ID: ChkI97yF3YfM-dwFGg0vZy8xMXl3cDFsa2Q2EAE
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3176 records | 112 unique hotels
SUCCESS: Liza Royale Hotel
New hotels collected: 29/100
Total unique hotels now: 112
Total records now: 3176

------------------------------------------------------------
NEW HOTEL 30/100
Hotel: Hotel White Mount
Hotel ID: ChoI0quVh4LJhfzTARoNL2cvMTFjMW5odnBtcBAB
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3206 records | 113 unique hotels
SUCCESS: Hotel White Mount
New hotels collected: 30/100
Total unique hotels now: 113
Total records now: 3206

------------------------------------------------------------
NEW HOTEL 31/100
Hotel: Hotel Park Tower
Hotel ID: ChoI5ZH0k67P9dTQARoNL2cvMTFnbXlyajEwaxAB
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3236 records | 114 unique hotels
SUCCESS: Hotel Park Tower
New hotels collected: 31/100
Total unique hotels now: 114
Total records now: 3236

------------------------------------------------------------
NEW HOTEL 32/100
Hotel: K.A.S.ROYAL RESIDENCY
Hotel ID: ChoI-ubOp_rp_8_nARoNL2cvMTF5MTlnXzJrZhAB
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 18
Dataset saved: 3254 records | 115 unique hotels
SUCCESS: K.A.S.ROYAL RESIDENCY
New hotels collected: 32/100
Total unique hotels now: 115
Total records now: 3254

------------------------------------------------------------
NEW HOTEL 33/100
Hotel: Hotel Sand Silver
Hotel ID: ChkI1Z72xLnP0epgGg0vZy8xMWY3NjZwcDR0EAE
Area: Chennai Central
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3284 records | 116 unique hotels
SUCCESS: Hotel Sand Silver
New hotels collected: 33/100
Total unique hotels now: 116
Total records now: 3284

------------------------------------------------------------
NEW HOTEL 34/100
Hotel: Oyster Stay - 3BHK - Luxury Stay
Hotel ID: ChkQ3sbv9Zy5kMxVGg0vZy8xMXhkM2pjdDUwEAI
Area: Chennai Central
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 3285 records | 117 unique hotels
SUCCESS: Oyster Stay - 3BHK - Luxury Stay
New hotels collected: 34/100
Total unique hotels now: 117
Total records now: 3285

/tmp/ipykernel_1058/654340771.py:1242: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 35/100
Hotel: The view signature studio
Hotel ID: ChoQ6o3MjL37ks24ARoNL2cvMTF4ZDJjc2dqdxAC
Area: Chennai Central
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 3285 records | 117 unique hotels
SUCCESS: The view signature studio
New hotels collected: 35/100
Total unique hotels now: 117
Total records now: 3285

/tmp/ipykernel_1058/654340771.py:1242: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCHING: Mount Road
NEW HOTEL PROGRESS: 35/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Hablis - A Business Hotel In Chennal

------------------------------------------------------------
NEW HOTEL 36/100
Hotel: E Hotel Chennai
Hotel ID: ChkIvdfSt_qtxtqLARoML2cvMTJoc2Rra183EAE
Area: Mount Road
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3315 records | 118 unique hotels
SUCCESS: E Hotel Chennai
New hotels collected: 36/100
Total unique hotels now: 118
Total records now: 3315
SKIP EXISTING: Century Courtyard
SKIP EXISTING: GREEN TREE HOTEL

------------------------------------------------------------
NEW HOTEL 37/100
Hotel: RR MOUNT ELITE SUITES
Hotel ID: ChoI9KCayqvy0tmVARoNL2cvMTFzYnhkMzl0YhAB
Area: Mount Road
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3345 records | 119 unique hotels
SUCCESS: RR MOUNT ELITE SUITES
New hotels collected: 37/100
Total unique hotels now: 119
Total records now: 3345

------------------------------------------------------------
NEW HOTEL 38/100
Hotel: Mount Residency
Hotel ID: ChgI7vHYlYm91e8IGgwvZy8xMXl3cnY4bTUQAQ
Area: Mount Road
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3375 records | 120 unique hotels
SUCCESS: Mount Residency
New hotels collected: 38/100
Total unique hotels now: 120
Total records now: 3375

------------------------------------------------------------
NEW HOTEL 39/100
Hotel: La Woods Hotel
Hotel ID: ChoI4azM0ejJs4-SARoNL2cvMTFkeGRjNjE5dBAB
Area: Mount Road
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3405 records | 121 unique hotels
SUCCESS: La Woods Hotel
New hotels collected: 39/100
Total unique hotels now: 121
Total records now: 3405

------------------------------------------------------------
NEW HOTEL 40/100
Hotel: Pine Tree Hotel
Hotel ID: ChkI0OSV3pHL08AsGg0vZy8xMWNrdmg0YzhkEAE
Area: Mount Road
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3435 records | 122 unique hotels
SUCCESS: Pine Tree Hotel
New hotels collected: 40/100
Total unique hotels now: 122
Total records now: 3435
SKIP EXISTING: The Saibaba Hotel | Accommodation in T Nagar Chennai
SKIP EXISTING: S Hotels Chennai
SKIP EXISTING: Mount Kailash Suites Saidapet Chennai

------------------------------------------------------------
NEW HOTEL 41/100
Hotel: GT Grande Hotel-Near US Consulate & Singapore Consulate
Hotel ID: ChoIzb_X8bT7ibeiARoNL2cvMTFzMzZfbTVnbRAB
Area: Mount Road
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3465 records | 123 unique hotels
SUCCESS: GT Grande Hotel-Near US Consulate & Singapore Consulate
New hotels collected: 41/100
Total unique hotels now: 123
Total records now: 3465
SKIP EXISTING: 44 Oasis- Hotel T.Nagar
SKIP EXISTING: Klase Hotels - hotels near chennai airport

------------------------------------------------------------
NEW HOTEL 42/100
Hotel: Supreme Stay - Hotel Chepauk
Hotel ID: ChoIt6DxrdTE2NieARoNL2cvMTF2MF9wNzcwOBAB
Area: Mount Road
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3495 records | 124 unique hotels
SUCCESS: Supreme Stay - Hotel Chepauk
New hotels collected: 42/100
Total unique hotels now: 124
Total records now: 3495
SKIP EXISTING: SEASON 4 RESIDENCES - NUNGAMBAKKAM

------------------------------------------------------------
NEW HOTEL 43/100
Hotel: HOTEL ROYAL PARK - Chennai
Hotel ID: ChoIprCG5LXk2Z_0ARoNL2cvMTFzYzFxMzk0NhAB
Area: Mount Road
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3525 records | 125 unique hotels
SUCCESS: HOTEL ROYAL PARK - Chennai
New hotels collected: 43/100
Total unique hotels now: 125
Total records now: 3525
SKIP EXISTING: Treebo Gt Meridian, T-Nagar

------------------------------------------------------------
NEW HOTEL 44/100
Hotel: Roshini Serviced Apartments - Deluxe Double Room (2 Adults + 1 Child)
Hotel ID: ChoQiJT7y_iaovDmARoNL2cvMTFuOWM0c25rXxAC
Area: Mount Road
------------------------------------------------------------
Reviews collected: 8
Dataset saved: 3533 records | 126 unique hotels
SUCCESS: Roshini Serviced Apartments - Deluxe Double Room (2 Adults + 1 Child)
New hotels collected: 44/100
Total unique hotels now: 126
Total records now: 3533

------------------------------------------------------------
NEW HOTEL 45/100
Hotel: DBS Apartments Nungambakkam
Hotel ID: ChkQm6SRlNiYzqhMGg0vZy8xMXpmYjRoZHB2EAI
Area: Mount Road
------------------------------------------------------------
Reviews collected: 3
Dataset saved: 3536 records | 127 unique hotels
SUCCESS: DBS Apartments Nungambakkam
New hotels collected: 45/100
Total unique hotels now: 127
Total records now: 3536


======================================================================
SEARCHING: George Town
NEW HOTEL PROGRESS: 45/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Sheraton Grande Hotel
SKIP EXISTING: Stay Court (Business Class Hotel)

------------------------------------------------------------
NEW HOTEL 46/100
Hotel: Greens Inn
Hotel ID: ChkIvcS5ivaWjYlvGg0vZy8xMXZ3eTN6dDJzEAE
Area: George Town
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3566 records | 128 unique hotels
SUCCESS: Greens Inn
New hotels collected: 46/100
Total unique hotels now: 128
Total records now: 3566
SKIP EXISTING: Bloom Hotel - Chennai Central
SKIP EXISTING: Liza Regency - Hotel & Restaurant
SKIP EXISTING: Orion Residency
SKIP EXISTING: Hotel AKMG Towers - Chennai
SKIP EXISTING: The Park Avenue Hotel
SKIP EXISTING: Hotel Sand Silver

------------------------------------------------------------
NEW HOTEL 47/100
Hotel: i5 palace
Hotel ID: ChkIks-gx4WTqbUrGg0vZy8xMWhkZnF5enQyEAE
Area: George Town
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3596 records | 129 unique hotels
SUCCESS: i5 palace
New hotels collected: 47/100
Total unique hotels now: 129
Total records now: 3596
SKIP EXISTING: Hotel White Mount
SKIP EXISTING: Sun City Chennai

------------------------------------------------------------
NEW HOTEL 48/100
Hotel: Horizon inn
Hotel ID: ChkItIOrkZzY7pEBGg0vZy8xMWZqMnpyOWdtEAE
Area: George Town
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3626 records | 130 unique hotels
SUCCESS: Horizon inn
New hotels collected: 48/100
Total unique hotels now: 130
Total records now: 3626

------------------------------------------------------------
NEW HOTEL 49/100
Hotel: Bhima's Inn
Hotel ID: ChcIsbb72s7D5YZbGgsvZy8xdGc2dDNzNhAB
Area: George Town
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3656 records | 131 unique hotels
SUCCESS: Bhima's Inn
New hotels collected: 49/100
Total unique hotels now: 131
Total records now: 3656

------------------------------------------------------------
NEW HOTEL 50/100
Hotel: SM Mansion
Hotel ID: ChgI6ZLRlt-M1NnhARoLL2cvMXRkcXk0ZDYQAQ
Area: George Town
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3686 records | 132 unique hotels
SUCCESS: SM Mansion
New hotels collected: 50/100
Total unique hotels now: 132
Total records now: 3686
SKIP EXISTING: Liza Royale Hotel
SKIP EXISTING: Sarovar Inn
SKIP EXISTING: K.A.S.ROYAL RESIDENCY
SKIP EXISTING: Oyster Stay - 3BHK - Luxury Stay

------------------------------------------------------------
NEW HOTEL 51/100
Hotel: GP Mansion - Single Room with Bathroom
Hotel ID: ChkQ6cev6rbz2ZdOGg0vZy8xMXR4cW04Z2YzEAI
Area: George Town
------------------------------------------------------------
Reviews collected: 16
Dataset saved: 3702 records | 133 unique hotels
SUCCESS: GP Mansion - Single Room with Bathroom
New hotels collected: 51/100
Total unique hotels now: 133
Total records now: 3702


======================================================================
SEARCHING: Broadway
NEW HOTEL PROGRESS: 51/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Sheraton Grande Hotel
SKIP EXISTING: The Hydel Park (Business Class Hotel) Chennai
SKIP EXISTING: Stay Court (Business Class Hotel)
SKIP EXISTING: Liza Regency - Hotel & Restaurant
SKIP EXISTING: The Park Avenue Hotel
SKIP EXISTING: Grand Cascade Hotels

------------------------------------------------------------
NEW HOTEL 52/100
Hotel: Greens Suite (Business Class Hotel)
Hotel ID: ChoIm6aQ4JiCsPu3ARoNL2cvMTFzOTMwZjA1NxAB
Area: Broadway
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3732 records | 134 unique hotels
SUCCESS: Greens Suite (Business Class Hotel)
New hotels collected: 52/100
Total unique hotels now: 134
Total records now: 3732
SKIP EXISTING: Bloom Hotel - Chennai Central
SKIP EXISTING: Hotel AKMG Towers - Chennai
SKIP EXISTING: Sarovar Inn
SKIP EXISTING: Orion Residency
SKIP EXISTING: Bhima's Inn
SKIP EXISTING: Liza Royale Hotel
SKIP EXISTING: Hotel Greens Gate
SKIP EXISTING: Greens Estate

------------------------------------------------------------
NEW HOTEL 53/100
Hotel: 4U Business Class Hotel
Hotel ID: ChoIgP_Ht53Uir6CARoNL2cvMTFkZmd0MGdwcBAB
Area: Broadway
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3762 records | 135 unique hotels
SUCCESS: 4U Business Class Hotel
New hotels collected: 53/100
Total unique hotels now: 135
Total records now: 3762

------------------------------------------------------------
NEW HOTEL 54/100
Hotel: Grand Elegant
Hotel ID: ChoIgZOz4LvboaO5ARoNL2cvMTFmajZ2dDA0eRAB
Area: Broadway
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3792 records | 136 unique hotels
SUCCESS: Grand Elegant
New hotels collected: 54/100
Total unique hotels now: 136
Total records now: 3792
SKIP EXISTING: Greens Inn
SKIP EXISTING: Oyster Stay - 3BHK - Luxury Stay

------------------------------------------------------------
NEW HOTEL 55/100
Hotel: Cozy 1-bedroom hotel suite in pleasant Chennai with AC, WiFi
Hotel ID: ChkQg77Gjsn4tvwxGg0vZy8xMW50aHIxamtoEAI
Area: Broadway
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 3792 records | 136 unique hotels
SUCCESS: Cozy 1-bedroom hotel suite in pleasant Chennai with AC, WiFi
New hotels collected: 55/100
Total unique hotels now: 136
Total records now: 3792

/tmp/ipykernel_1058/654340771.py:1242: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCHING: Royapuram
NEW HOTEL PROGRESS: 55/100
======================================================================
Hotels returned: 18
SKIP EXISTING: Sarovar Inn
SKIP EXISTING: Greens Inn
SKIP EXISTING: Bhima's Inn

------------------------------------------------------------
NEW HOTEL 56/100
Hotel: Al NOOR RESIDENCY BUSINESS CLASS HOTEL
Hotel ID: ChoItN2Cn5mt_8-vARoNL2cvMTF2MWJsYzI0ZhAB
Area: Royapuram
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3822 records | 137 unique hotels
SUCCESS: Al NOOR RESIDENCY BUSINESS CLASS HOTEL
New hotels collected: 56/100
Total unique hotels now: 137
Total records now: 3822
SKIP EXISTING: Hotel AKMG Towers - Chennai
SKIP EXISTING: SM Mansion
SKIP EXISTING: Sun City Chennai

------------------------------------------------------------
NEW HOTEL 57/100
Hotel: FabHotel Nestlay Rooms High Court
Hotel ID: ChkIquqqrqaoztcBGg0vZy8xMWx0djlwZHlyEAE
Area: Royapuram
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3852 records | 138 unique hotels
SUCCESS: FabHotel Nestlay Rooms High Court
New hotels collected: 57/100
Total unique hotels now: 138
Total records now: 3852

------------------------------------------------------------
NEW HOTEL 58/100
Hotel: THE NEST
Hotel ID: ChoIh6DCwpC55fbEARoNL2cvMTF5ajk2enFsahAB
Area: Royapuram
------------------------------------------------------------
Reviews collected: 23
Dataset saved: 3875 records | 139 unique hotels
SUCCESS: THE NEST
New hotels collected: 58/100
Total unique hotels now: 139
Total records now: 3875

------------------------------------------------------------
NEW HOTEL 59/100
Hotel: Hotel Santhi Bhavan
Hotel ID: ChkI0Junjdf00fJPGg0vZy8xMWM2ZjlnZjRrEAE
Area: Royapuram
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3905 records | 140 unique hotels
SUCCESS: Hotel Santhi Bhavan
New hotels collected: 59/100
Total unique hotels now: 140
Total records now: 3905

------------------------------------------------------------
NEW HOTEL 60/100
Hotel: The Cubic Stays
Hotel ID: ChkIosSbxMeOkKNOGg0vZy8xMXd0bHM1ajZ4EAE
Area: Royapuram
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3935 records | 141 unique hotels
SUCCESS: The Cubic Stays
New hotels collected: 60/100
Total unique hotels now: 141
Total records now: 3935
SKIP EXISTING: i5 palace

------------------------------------------------------------
NEW HOTEL 61/100
Hotel: ROYES PARK
Hotel ID: ChkIouDzyZz4nM1TGg0vZy8xMXZ5cnlwbjJ5EAE
Area: Royapuram
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3965 records | 142 unique hotels
SUCCESS: ROYES PARK
New hotels collected: 61/100
Total unique hotels now: 142
Total records now: 3965

------------------------------------------------------------
NEW HOTEL 62/100
Hotel: KLS Oceanic Inn
Hotel ID: ChkI-Ynj0tCv18pgGg0vZy8xMXdyNHg1YnhyEAE
Area: Royapuram
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3995 records | 143 unique hotels
SUCCESS: KLS Oceanic Inn
New hotels collected: 62/100
Total unique hotels now: 143
Total records now: 3995

------------------------------------------------------------
NEW HOTEL 63/100
Hotel: Hotel City Tower
Hotel ID: ChgI3bPmlerh-4HHARoLL2cvMXRmeDNiMzMQAQ
Area: Royapuram
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4025 records | 144 unique hotels
SUCCESS: Hotel City Tower
New hotels collected: 63/100
Total unique hotels now: 144
Total records now: 4025

------------------------------------------------------------
NEW HOTEL 64/100
Hotel: GP Mansion
Hotel ID: ChoIu7Ds54_7nsG5ARoNL2cvMTFjMW10anNsdhAB
Area: Royapuram
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4055 records | 145 unique hotels
SUCCESS: GP Mansion
New hotels collected: 64/100
Total unique hotels now: 145
Total records now: 4055

------------------------------------------------------------
NEW HOTEL 65/100
Hotel: City home
Hotel ID: ChkIrqT-m7Tu_bPMARoML2cvMXE2NWN4ZzMwEAE
Area: Royapuram
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4085 records | 146 unique hotels
SUCCESS: City home
New hotels collected: 65/100
Total unique hotels now: 146
Total records now: 4085

------------------------------------------------------------
NEW HOTEL 66/100
Hotel: DELMON Residency
Hotel ID: ChkI3ebWpZH5iKNZGg0vZy8xMXkwczV5Ymt4EAE
Area: Royapuram
------------------------------------------------------------
Reviews collected: 19
Dataset saved: 4104 records | 147 unique hotels
SUCCESS: DELMON Residency
New hotels collected: 66/100
Total unique hotels now: 147
Total records now: 4104


======================================================================
SEARCHING: Washermenpet
NEW HOTEL PROGRESS: 66/100
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 67/100
Hotel: Westin Residency
Hotel ID: ChoIgZHu_ejarfu4ARoNL2cvMTFjNThwNGNneRAB
Area: Washermenpet
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4134 records | 148 unique hotels
SUCCESS: Westin Residency
New hotels collected: 67/100
Total unique hotels now: 148
Total records now: 4134
SKIP EXISTING: Hotel AKMG Towers - Chennai
SKIP EXISTING: Greens Inn
SKIP EXISTING: Bhima's Inn
SKIP EXISTING: i5 palace

------------------------------------------------------------
NEW HOTEL 68/100
Hotel: Hotel GT Aathika Palace
Hotel ID: ChkIrvfehYrizqcbGg0vZy8xMW5iNXFrZDZuEAE
Area: Washermenpet
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4164 records | 149 unique hotels
SUCCESS: Hotel GT Aathika Palace
New hotels collected: 68/100
Total unique hotels now: 149
Total records now: 4164
SKIP EXISTING: FabHotel Nestlay Rooms High Court
SKIP EXISTING: Hotel City Tower
SKIP EXISTING: Sarovar Inn
SKIP EXISTING: KLS Oceanic Inn
SKIP EXISTING: ROYES PARK
SKIP EXISTING: Sun City Chennai
SKIP EXISTING: Al NOOR RESIDENCY BUSINESS CLASS HOTEL

------------------------------------------------------------
NEW HOTEL 69/100
Hotel: Hotel Blue Star International
Hotel ID: ChcIobjczb_EooMVGgsvZy8xdGo1cDRoahAB
Area: Washermenpet
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4194 records | 150 unique hotels
SUCCESS: Hotel Blue Star International
New hotels collected: 69/100
Total unique hotels now: 150
Total records now: 4194
SKIP EXISTING: SM Mansion
SKIP EXISTING: Hotel Santhi Bhavan
SKIP EXISTING: THE NEST
SKIP EXISTING: The Cubic Stays
SKIP EXISTING: GP Mansion - Single Room with Bathroom

------------------------------------------------------------
NEW HOTEL 70/100
Hotel: GP Mansion - Double Room with Private Bathroom
Hotel ID: ChkQt9H0lfut6Oh7Gg0vZy8xMW53NTR3OHozEAI
Area: Washermenpet
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 4194 records | 150 unique hotels
SUCCESS: GP Mansion - Double Room with Private Bathroom
New hotels collected: 70/100
Total unique hotels now: 150
Total records now: 4194

/tmp/ipykernel_1058/654340771.py:1242: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCHING: T Nagar
NEW HOTEL PROGRESS: 70/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Golden Fruits Business Suites

------------------------------------------------------------
NEW HOTEL 71/100
Hotel: Grand Chennai by GRT Hotels
Hotel ID: ChoIlZiWzfTq6MjZARoNL2cvMTFjbGxuNGNfNRAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4224 records | 151 unique hotels
SUCCESS: Grand Chennai by GRT Hotels
New hotels collected: 71/100
Total unique hotels now: 151
Total records now: 4224
SKIP EXISTING: UPAR Hotels T Nagar
SKIP EXISTING: JJS PARK INN

------------------------------------------------------------
NEW HOTEL 72/100
Hotel: The Accord Metropolitan
Hotel ID: ChYI-PvamN_4iPVCGgovbS8waF9jNzY1EAE
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4254 records | 152 unique hotels
SUCCESS: The Accord Metropolitan
New hotels collected: 72/100
Total unique hotels now: 152
Total records now: 4254

------------------------------------------------------------
NEW HOTEL 73/100
Hotel: GT Residency T Nagar
Hotel ID: ChoIjPzskLePyKCdARoNL2cvMTFxcHpobXhseRAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4284 records | 153 unique hotels
SUCCESS: GT Residency T Nagar
New hotels collected: 73/100
Total unique hotels now: 153
Total records now: 4284

------------------------------------------------------------
NEW HOTEL 74/100
Hotel: Itsy Hotels Deluxe Inn
Hotel ID: ChoI9c-Fnt_G7fWFARoNL2cvMTFkX2Qycjh3bRAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4314 records | 154 unique hotels
SUCCESS: Itsy Hotels Deluxe Inn
New hotels collected: 74/100
Total unique hotels now: 154
Total records now: 4314
SKIP EXISTING: S Hotels Chennai
SKIP EXISTING: Treebo Gt Meridian, T-Nagar
SKIP EXISTING: 44 Oasis- Hotel T.Nagar
SKIP EXISTING: THE K11 HOTELS - CHENNAI

------------------------------------------------------------
NEW HOTEL 75/100
Hotel: The Residency, Chennai
Hotel ID: ChgI5MPIoMO-8j4aDS9nLzExZjE1ano0ZmcQAQ
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4344 records | 155 unique hotels
SUCCESS: The Residency, Chennai
New hotels collected: 75/100
Total unique hotels now: 155
Total records now: 4344
SKIP EXISTING: The Saibaba Hotel | Accommodation in T Nagar Chennai
SKIP EXISTING: Grand Continent
SKIP EXISTING: The Lotus Apartment Hotel

------------------------------------------------------------
NEW HOTEL 76/100
Hotel: Grand Continent Premiere, T. Nagar
Hotel ID: ChoIvpa75d6W0_CyARoNL2cvMTF4bGdfcWpkMRAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4374 records | 156 unique hotels
SUCCESS: Grand Continent Premiere, T. Nagar
New hotels collected: 76/100
Total unique hotels now: 156
Total records now: 4374
SKIP EXISTING: STAR CITY HOTELS

------------------------------------------------------------
NEW HOTEL 77/100
Hotel: Blossoms Hotel and Serviced Apartments
Hotel ID: ChoI4KrKqYWRpPf7ARoNL2cvMTFzcGs5Y3c4NBAB
Area: T Nagar
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4404 records | 157 unique hotels
SUCCESS: Blossoms Hotel and Serviced Apartments
New hotels collected: 77/100
Total unique hotels now: 157
Total records now: 4404
SKIP EXISTING: Golden Fruits Business Suites - Standard Double Room

------------------------------------------------------------
NEW HOTEL 78/100
Hotel: Jasmine park - Executive Deluxe Double Room
Hotel ID: ChkQ1onWre-omPFSGg0vZy8xMXp4cmtsMmY2EAI
Area: T Nagar
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 4404 records | 157 unique hotels
SUCCESS: Jasmine park - Executive Deluxe Double Room
New hotels collected: 78/100
Total unique hotels now: 157
Total records now: 4404

/tmp/ipykernel_1058/654340771.py:1242: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCHING: Nungambakkam
NEW HOTEL PROGRESS: 78/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Park Avenue Hotel, Chennai
SKIP EXISTING: UPAR Hotels Nungambakkam

------------------------------------------------------------
NEW HOTEL 79/100
Hotel: Park Elanza
Hotel ID: ChkIkLSl9o652vMwGg0vZy8xMWgyNDl0NzR5EAE
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4434 records | 158 unique hotels
SUCCESS: Park Elanza
New hotels collected: 79/100
Total unique hotels now: 158
Total records now: 4434
SKIP EXISTING: The Kings Park Grand
SKIP EXISTING: Century Courtyard
SKIP EXISTING: Treebo Nestlay Rooms Nungambakkam
SKIP EXISTING: Harrisons Hotel
SKIP EXISTING: SEASON 4 RESIDENCES - NUNGAMBAKKAM
SKIP EXISTING: Pine Tree Hotel

------------------------------------------------------------
NEW HOTEL 80/100
Hotel: The Park Chennai
Hotel ID: ChcI7d_9nMiv3Z_CARoKL20vMGhodDBiaxAB
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4464 records | 159 unique hotels
SUCCESS: The Park Chennai
New hotels collected: 80/100
Total unique hotels now: 159
Total records now: 4464

------------------------------------------------------------
NEW HOTEL 81/100
Hotel: Royal Luxe Business Class Hotel
Hotel ID: ChoIrs-2guDd8IeYARoNL2cvMTF3OW5temIwYhAB
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4494 records | 160 unique hotels
SUCCESS: Royal Luxe Business Class Hotel
New hotels collected: 81/100
Total unique hotels now: 160
Total records now: 4494

------------------------------------------------------------
NEW HOTEL 82/100
Hotel: Redstone Hotel
Hotel ID: ChoIjrXbjfu61IjnARoNL2cvMTFzNm00anlfNBAB
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4524 records | 161 unique hotels
SUCCESS: Redstone Hotel
New hotels collected: 82/100
Total unique hotels now: 161
Total records now: 4524

------------------------------------------------------------
NEW HOTEL 83/100
Hotel: Pharos Hotels
Hotel ID: ChoI0IiTmePmrqjmARoNL2cvMTFzNGd6bjg1dhAB
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4554 records | 162 unique hotels
SUCCESS: Pharos Hotels
New hotels collected: 83/100
Total unique hotels now: 162
Total records now: 4554

------------------------------------------------------------
NEW HOTEL 84/100
Hotel: Gulnaar Inn
Hotel ID: ChkIuaSSz5Ckm4dOGg0vZy8xMWdoZmdfbW1fEAE
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4584 records | 163 unique hotels
SUCCESS: Gulnaar Inn
New hotels collected: 84/100
Total unique hotels now: 163
Total records now: 4584

------------------------------------------------------------
NEW HOTEL 85/100
Hotel: Taj Coromandel, Chennai
Hotel ID: ChcI8fT3oo2YudLCARoKL20vMGhocWxudhAB
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4614 records | 164 unique hotels
SUCCESS: Taj Coromandel, Chennai
New hotels collected: 85/100
Total unique hotels now: 164
Total records now: 4614

------------------------------------------------------------
NEW HOTEL 86/100
Hotel: FabExpress B Zone
Hotel ID: ChkInvPazf6y-NQsGg0vZy8xMWo4Ynl2bDR2EAE
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4644 records | 165 unique hotels
SUCCESS: FabExpress B Zone
New hotels collected: 86/100
Total unique hotels now: 165
Total records now: 4644

------------------------------------------------------------
NEW HOTEL 87/100
Hotel: Sweet Memories stay
Hotel ID: ChkI2O7Ghu614v0_Gg0vZy8xMWpxc25iNHdsEAE
Area: Nungambakkam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 4674 records | 166 unique hotels
SUCCESS: Sweet Memories stay
New hotels collected: 87/100
Total unique hotels now: 166
Total records now: 4674

------------------------------------------------------------
NEW HOTEL 88/100
Hotel: The Belstead Hotel
Hotel ID: ChkIyqe8hYKInMY8Gg0vZy8xMWR4bGdjc2dfEAE
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkIyqe8hYKInMY8Gg0vZy8xMWR4bGdjc2dfEAE&hl=en&sort_by=2&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58
No reviews found.
Hotel information saved.

/tmp/ipykernel_1058/654340771.py:1242: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

Dataset saved: 4674 records | 166 unique hotels
SUCCESS: The Belstead Hotel
New hotels collected: 88/100
Total unique hotels now: 166
Total records now: 4674

------------------------------------------------------------
NEW HOTEL 89/100
Hotel: Sweet Memories- Perfect home stay - Superior Double Room
Hotel ID: ChkQwZjQqO6bmoYtGg0vZy8xMXRnZ3ByNDJmEAI
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkQwZjQqO6bmoYtGg0vZy8xMXRnZ3ByNDJmEAI&hl=en&sort_by=2&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58
No reviews found.
Hotel information saved.

/tmp/ipykernel_1058/654340771.py:1242: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

Dataset saved: 4674 records | 166 unique hotels
SUCCESS: Sweet Memories- Perfect home stay - Superior Double Room
New hotels collected: 89/100
Total unique hotels now: 166
Total records now: 4674

------------------------------------------------------------
NEW HOTEL 90/100
Hotel: Redstone Service Apartment-TNagar Near UsConsulate
Hotel ID: ChkQuLGsoPXditd_Gg0vZy8xMXpoNHg2cWQ2EAI
Area: Nungambakkam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkQuLGsoPXditd_Gg0vZy8xMXpoNHg2cWQ2EAI&hl=en&sort_by=2&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58
No reviews found.
Hotel information saved.

/tmp/ipykernel_1058/654340771.py:1242: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

Dataset saved: 4674 records | 166 unique hotels
SUCCESS: Redstone Service Apartment-TNagar Near UsConsulate
New hotels collected: 90/100
Total unique hotels now: 166
Total records now: 4674


======================================================================
SEARCHING: Egmore
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Egmore%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Mylapore
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Mylapore%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Alwarpet
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Alwarpet%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Royapettah
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Royapettah%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Triplicane
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Triplicane%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Chetpet
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Chetpet%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Kilpauk
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Kilpauk%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Purasawalkam
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Purasawalkam%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Saidapet
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Saidapet%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Anna Nagar
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Anna+Nagar%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Mogappair
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Mogappair%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Ambattur
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Ambattur%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Avadi
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Avadi%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Poonamallee
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Poonamallee%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Porur
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Porur%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Ramapuram
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Ramapuram%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Manapakkam
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Manapakkam%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Vadapalani
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Vadapalani%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Kodambakkam
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Kodambakkam%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Ashok Nagar
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Ashok+Nagar%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Koyambedu
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Koyambedu%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Guindy
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Guindy%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Adyar
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Adyar%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Besant Nagar
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Besant+Nagar%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Thiruvanmiyur
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Thiruvanmiyur%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Kotturpuram
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Kotturpuram%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Madhya Kailash
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Madhya+Kailash%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Velachery
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Velachery%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Pallikaranai
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Pallikaranai%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Medavakkam
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Medavakkam%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Perumbakkam
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Perumbakkam%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: OMR
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+OMR%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Perungudi
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Perungudi%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Thoraipakkam
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Thoraipakkam%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Karapakkam
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Karapakkam%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Sholinganallur
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Sholinganallur%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Navalur
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Navalur%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Siruseri
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Siruseri%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: ECR
NEW HOTEL PROGRESS: 90/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+ECR%2C+Chennai&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=419c18d17a96824ec591c0b5e0c2b73a83c0f66a38e0f68f53e7ecb61997fa58


======================================================================
SEARCHING: Neelankarai
NEW HOTEL PROGRESS: 90/100
======================================================================

In [ ]:
from google.colab import files

files.download("chennai_hotel_dataset.csv")

In [ ]:
import os
import time
import requests
import pandas as pd

# ============================================================
# CONFIGURATION
# ============================================================

API_KEY = input("Enter your SerpApi API key: ").strip()

# IMPORTANT:
# Rename your current file to this exact name in Colab:
# andhra_pradesh_hotel_dataset.csv

OUTPUT_FILE = "andhra_pradesh_hotel_dataset.csv"

# NEW checkpoint for this batch
CHECKPOINT_FILE = "andhra_pradesh_next_100_checkpoint.csv"

STATE = "Andhra Pradesh"

# Collect 100 NEW hotels
TARGET_NEW_HOTELS = 100

# Maximum review pages per hotel
MAX_REVIEW_PAGES = 3

BASE_URL = "https://serpapi.com/search.json"


# ============================================================
# ANDHRA PRADESH SEARCH AREAS
# ============================================================

AP_AREAS = [

    # --------------------------------------------------------
    # VISAKHAPATNAM
    # --------------------------------------------------------

    "Visakhapatnam",
    "Vizag",
    "Dwaraka Nagar Visakhapatnam",
    "MVP Colony Visakhapatnam",
    "Siripuram Visakhapatnam",
    "Madhurawada Visakhapatnam",
    "Gajuwaka Visakhapatnam",
    "Rushikonda Visakhapatnam",
    "Beach Road Visakhapatnam",
    "RK Beach Visakhapatnam",
    "Waltair Visakhapatnam",
    "Visakhapatnam Airport",
    "Seethammadhara Visakhapatnam",
    "Akkayyapalem Visakhapatnam",
    "Dabagardens Visakhapatnam",
    "Kurmannapalem Visakhapatnam",

    # --------------------------------------------------------
    # VIJAYAWADA
    # --------------------------------------------------------

    "Vijayawada",
    "Benz Circle Vijayawada",
    "Governorpet Vijayawada",
    "Moghalrajpuram Vijayawada",
    "Labbipet Vijayawada",
    "Bhavanipuram Vijayawada",
    "Poranki Vijayawada",
    "Gollapudi Vijayawada",
    "Patamata Vijayawada",
    "Auto Nagar Vijayawada",

    # --------------------------------------------------------
    # TIRUPATI
    # --------------------------------------------------------

    "Tirupati",
    "Tirumala",
    "Renigunta",
    "Tiruchanur",
    "Kapila Theertham Tirupati",
    "Alipiri Tirupati",
    "Tirupati Railway Station",

    # --------------------------------------------------------
    # GUNTUR
    # --------------------------------------------------------

    "Guntur",
    "Brodipet Guntur",
    "Arundelpet Guntur",
    "Lakshmipuram Guntur",
    "Mangalagiri",
    "Amaravati",
    "Tadepalli",

    # --------------------------------------------------------
    # NELLORE
    # --------------------------------------------------------

    "Nellore",
    "Magunta Layout Nellore",
    "Dargamitta Nellore",
    "Vedayapalem Nellore",

    # --------------------------------------------------------
    # KAKINADA
    # --------------------------------------------------------

    "Kakinada",
    "Kakinada Beach",
    "Sarpavaram Kakinada",

    # --------------------------------------------------------
    # RAJAHMUNDRY
    # --------------------------------------------------------

    "Rajahmundry",
    "Rajamahendravaram",
    "Danavaipeta Rajahmundry",
    "Morampudi Rajahmundry",

    # --------------------------------------------------------
    # KURNOOL
    # --------------------------------------------------------

    "Kurnool",
    "Nandyal",
    "Kurnool Railway Station",

    # --------------------------------------------------------
    # ANANTAPUR
    # --------------------------------------------------------

    "Anantapur",
    "Anantapur Railway Station",

    # --------------------------------------------------------
    # KADAPA
    # --------------------------------------------------------

    "Kadapa",
    "Proddatur",
    "Rajampet",

    # --------------------------------------------------------
    # SRIKAKULAM
    # --------------------------------------------------------

    "Srikakulam",
    "Arasavalli",

    # --------------------------------------------------------
    # VIZIANAGARAM
    # --------------------------------------------------------

    "Vizianagaram",

    # --------------------------------------------------------
    # ELURU
    # --------------------------------------------------------

    "Eluru",

    # --------------------------------------------------------
    # MACHILIPATNAM
    # --------------------------------------------------------

    "Machilipatnam",

    # --------------------------------------------------------
    # BHIMAVARAM
    # --------------------------------------------------------

    "Bhimavaram",

    # --------------------------------------------------------
    # ONGOLE
    # --------------------------------------------------------

    "Ongole",

    # --------------------------------------------------------
    # BAPATLA / CHIRALA
    # --------------------------------------------------------

    "Bapatla",
    "Suryalanka",
    "Chirala",
    "Vodarevu",

    # --------------------------------------------------------
    # TOURIST / PILGRIMAGE LOCATIONS
    # --------------------------------------------------------

    "Kondapalli",
    "Lepakshi",
    "Srisailam",
    "Ahobilam",
    "Simhachalam",
    "Araku Valley",
    "Lambasingi",
    "Papikondalu",
    "Dwaraka Tirumala",

    # --------------------------------------------------------
    # OTHER AP LOCATIONS
    # --------------------------------------------------------

    "Narasaraopet",
    "Tenali",
    "Gudivada",
    "Nuzvid",
    "Tadepalligudem",
    "Tanuku",
    "Palakollu",
    "Amalapuram",
    "Mandapeta",
    "Samalkota",
    "Pithapuram",
    "Anakapalle",
    "Bobbili",
    "Parvathipuram",
    "Palasa",
    "Tekkali",
    "Markapur",
    "Chittoor",
    "Madanapalle",
    "Puttur",
    "Hindupur"
]

# Remove duplicate search areas
AP_AREAS = list(
    dict.fromkeys(AP_AREAS)
)


# ============================================================
# LOAD EXISTING DATASET
# ============================================================

if os.path.exists(OUTPUT_FILE):

    df = pd.read_csv(
        OUTPUT_FILE
    )

    print("\n" + "=" * 70)
    print("EXISTING ANDHRA PRADESH DATASET")
    print("=" * 70)

    print(
        f"Existing records: {len(df)}"
    )

else:

    print(
        f"\nERROR: {OUTPUT_FILE} not found."
    )

    print(
        "Upload/rename your existing Andhra Pradesh CSV "
        "to andhra_pradesh_hotel_dataset.csv"
    )

    raise FileNotFoundError(
        OUTPUT_FILE
    )


# ============================================================
# CHECK HOTEL_ID
# ============================================================

if "hotel_id" not in df.columns:

    raise ValueError(
        "The dataset does not contain a 'hotel_id' column."
    )


# ============================================================
# GET EXISTING UNIQUE HOTEL IDS
# ============================================================

df["hotel_id"] = (
    df["hotel_id"]
    .astype(str)
)

existing_hotel_ids = set(
    df["hotel_id"]
    .dropna()
    .astype(str)
)

# Remove invalid IDs
existing_hotel_ids.discard(
    "nan"
)

print(
    f"Existing unique hotels: "
    f"{len(existing_hotel_ids)}"
)

print(
    f"New hotels required: "
    f"{TARGET_NEW_HOTELS}"
)

print(
    f"Expected final unique hotels: "
    f"{len(existing_hotel_ids) + TARGET_NEW_HOTELS}"
)

print("=" * 70)


# ============================================================
# LOAD CHECKPOINT
# ============================================================

if os.path.exists(
    CHECKPOINT_FILE
):

    checkpoint = pd.read_csv(
        CHECKPOINT_FILE
    )

    if not checkpoint.empty:

        completed_hotels = set(
            checkpoint.loc[
                checkpoint["status"] == "completed",
                "hotel_id"
            ]
            .astype(str)
        )

    else:

        completed_hotels = set()

    print(
        f"Previously completed in this batch: "
        f"{len(completed_hotels)}"
    )

else:

    checkpoint = pd.DataFrame(
        columns=[
            "hotel_id",
            "hotel_name",
            "search_area",
            "status"
        ]
    )

    completed_hotels = set()

    print(
        "Starting a fresh batch."
    )


# ============================================================
# KNOWN HOTEL IDS
# ============================================================

known_hotel_ids = (
    existing_hotel_ids |
    completed_hotels
)


# ============================================================
# SAVE CHECKPOINT
# ============================================================

def save_checkpoint(
    hotel_id,
    hotel_name,
    search_area,
    status
):

    global checkpoint

    hotel_id = str(
        hotel_id
    )

    checkpoint = checkpoint[
        checkpoint["hotel_id"].astype(str)
        != hotel_id
    ]

    new_row = pd.DataFrame([
        {
            "hotel_id":
                hotel_id,

            "hotel_name":
                hotel_name,

            "search_area":
                search_area,

            "status":
                status
        }
    ])

    checkpoint = pd.concat(
        [
            checkpoint,
            new_row
        ],
        ignore_index=True
    )

    checkpoint.to_csv(
        CHECKPOINT_FILE,
        index=False
    )


# ============================================================
# SAVE DATASET
# ============================================================

def save_dataset():

    global df

    if "hotel_id" in df.columns:

        df["hotel_id"] = (
            df["hotel_id"]
            .astype(str)
        )

    # Remove duplicate reviews only when review_id exists
    if "review_id" in df.columns:

        valid_review_ids = (
            df["review_id"]
            .fillna("")
            .astype(str)
            .str.strip()
            != ""
        )

        df_with_ids = df[
            valid_review_ids
        ].drop_duplicates(
            subset=["review_id"]
        )

        df_without_ids = df[
            ~valid_review_ids
        ]

        df = pd.concat(
            [
                df_with_ids,
                df_without_ids
            ],
            ignore_index=True
        )

    else:

        df = df.drop_duplicates()

    df.to_csv(
        OUTPUT_FILE,
        index=False
    )

    print(
        f"Dataset saved: "
        f"{len(df)} records | "
        f"{df['hotel_id'].nunique()} unique hotels"
    )


# ============================================================
# SEARCH HOTELS
# ============================================================

def search_hotels(
    search_area
):

    params = {

        "engine":
            "google_hotels",

        "q":
            f"Hotels in {search_area}, Andhra Pradesh",

        "check_in_date":
            "2026-10-15",

        "check_out_date":
            "2026-10-16",

        "adults":
            "2",

        "currency":
            "INR",

        "gl":
            "in",

        "hl":
            "en",

        "api_key":
            API_KEY
    }

    response = requests.get(
        BASE_URL,
        params=params,
        timeout=60
    )

    response.raise_for_status()

    data = response.json()

    if "error" in data:

        print(
            f"SerpApi error: "
            f"{data['error']}"
        )

        return []

    return data.get(
        "properties",
        []
    )


# ============================================================
# EXTRACT LOCATION
# ============================================================

def extract_location(
    hotel
):

    gps = hotel.get(
        "gps_coordinates"
    )

    if gps:

        latitude = gps.get(
            "latitude"
        )

        longitude = gps.get(
            "longitude"
        )

        if (
            latitude is not None
            and
            longitude is not None
        ):

            return (
                f"Latitude: {latitude}, "
                f"Longitude: {longitude}"
            )

    return hotel.get(
        "address",
        ""
    )


# ============================================================
# EXTRACT AMENITIES
# ============================================================

def extract_amenities(
    hotel
):

    amenities = []

    for amenity in hotel.get(
        "amenities",
        []
    ):

        if isinstance(
            amenity,
            str
        ):

            amenities.append(
                amenity
            )

        elif isinstance(
            amenity,
            dict
        ):

            name = (
                amenity.get("name")
                or
                amenity.get("title")
            )

            if name:

                amenities.append(
                    str(name)
                )

    amenities = list(
        dict.fromkeys(
            amenities
        )
    )

    return " | ".join(
        amenities
    )


# ============================================================
# EXTRACT PRICE
# ============================================================

def extract_price(
    hotel
):

    price = hotel.get(
        "rate_per_night",
        {}
    )

    if isinstance(
        price,
        dict
    ):

        value = (
            price.get("lowest")
            or
            price.get("extracted_lowest")
        )

        if value is not None:

            return value

    if hotel.get(
        "price"
    ) is not None:

        return hotel.get(
            "price"
        )

    return None


# ============================================================
# CREATE HOTEL ROW
# ============================================================

def make_hotel_row(
    hotel,
    search_area
):

    hotel_id = (
        hotel.get(
            "property_token"
        )
        or
        hotel.get(
            "hotel_id"
        )
    )

    hotel_name = hotel.get(
        "name",
        "Unknown Hotel"
    )

    gps = hotel.get(
        "gps_coordinates",
        {}
    )

    latitude = gps.get(
        "latitude"
    )

    longitude = gps.get(
        "longitude"
    )

    return {

        "hotel_name":
            hotel_name,

        "hotel_id":
            str(hotel_id),

        "state":
            STATE,

        "location":
            extract_location(
                hotel
            ),

        "latitude":
            latitude,

        "longitude":
            longitude,

        "price_per_night":
            extract_price(
                hotel
            ),

        "hotel_category":
            hotel.get(
                "hotel_class"
            ),

        "customer_rating":
            hotel.get(
                "overall_rating"
            ),

        "review_count":
            hotel.get(
                "reviews"
            ),

        "amenities":
            extract_amenities(
                hotel
            ),

        "review_text":
            "",

        "individual_review_rating":
            None,

        "review_date":
            "",

        "review_source":
            "Google Hotels via SerpApi",

        "search_area":
            search_area,

        "review_id":
            ""
    }


# ============================================================
# FETCH REVIEWS
# ============================================================

def fetch_reviews(
    hotel,
    search_area
):

    hotel_id = (
        hotel.get(
            "property_token"
        )
        or
        hotel.get(
            "hotel_id"
        )
    )

    hotel_name = hotel.get(
        "name",
        "Unknown Hotel"
    )

    if not hotel_id:

        return []

    hotel_id = str(
        hotel_id
    )

    all_reviews = []

    next_page_token = None


    for page in range(
        1,
        MAX_REVIEW_PAGES + 1
    ):

        params = {

            "engine":
                "google_hotels_reviews",

            "property_token":
                hotel_id,

            "hl":
                "en",

            "sort_by":
                "2",

            "api_key":
                API_KEY
        }


        if next_page_token:

            params[
                "next_page_token"
            ] = next_page_token


        try:

            response = requests.get(
                BASE_URL,
                params=params,
                timeout=60
            )

            response.raise_for_status()

            data = response.json()

        except Exception as e:

            print(
                f"Review request failed: {e}"
            )

            break


        if "error" in data:

            print(
                f"Review API error: "
                f"{data['error']}"
            )

            break


        reviews = data.get(
            "reviews",
            []
        )


        if not reviews:

            break


        # ====================================================
        # PROCESS REVIEWS
        # ====================================================

        for index, review in enumerate(
            reviews
        ):

            review_id = (
                review.get(
                    "review_id"
                )
                or
                review.get(
                    "id"
                )
            )

            if not review_id:

                review_id = (
                    f"{hotel_id}_"
                    f"{page}_"
                    f"{index}"
                )


            review_rating = (
                review.get(
                    "rating"
                )
                or
                review.get(
                    "overall_rating"
                )
            )


            review_text = (

                review.get(
                    "snippet"
                )

                or

                review.get(
                    "text"
                )

                or

                review.get(
                    "review_text"
                )

                or
                ""
            )


            review_date = (

                review.get(
                    "date"
                )

                or

                review.get(
                    "relative_date"
                )

                or
                ""
            )


            row = {

                "hotel_name":
                    hotel_name,

                "hotel_id":
                    hotel_id,

                "state":
                    STATE,

                "location":
                    extract_location(
                        hotel
                    ),

                "latitude":
                    hotel.get(
                        "gps_coordinates",
                        {}
                    ).get(
                        "latitude"
                    ),

                "longitude":
                    hotel.get(
                        "gps_coordinates",
                        {}
                    ).get(
                        "longitude"
                    ),

                "price_per_night":
                    extract_price(
                        hotel
                    ),

                "hotel_category":
                    hotel.get(
                        "hotel_class"
                    ),

                "customer_rating":
                    hotel.get(
                        "overall_rating"
                    ),

                "review_count":
                    hotel.get(
                        "reviews"
                    ),

                "amenities":
                    extract_amenities(
                        hotel
                    ),

                "review_text":
                    review_text,

                "individual_review_rating":
                    review_rating,

                "review_date":
                    review_date,

                "review_source":
                    "Google Hotels Reviews via SerpApi",

                "search_area":
                    search_area,

                "review_id":
                    review_id
            }

            all_reviews.append(
                row
            )


        # ====================================================
        # NEXT PAGE
        # ====================================================

        next_page_token = (
            data.get(
                "serpapi_pagination",
                {}
            )
            .get(
                "next_page_token"
            )
        )


        if not next_page_token:

            break


        time.sleep(1)


    return all_reviews


# ============================================================
# MAIN SCRAPING PROCESS
# ============================================================

new_hotel_ids = set()

new_hotels_collected = 0


print("\n")
print("=" * 70)
print("ANDHRA PRADESH - NEXT 100 NEW HOTELS")
print("=" * 70)

print(
    f"Existing unique hotels: "
    f"{len(existing_hotel_ids)}"
)

print(
    f"New hotels required: "
    f"{TARGET_NEW_HOTELS}"
)

print(
    f"Final target: "
    f"{len(existing_hotel_ids) + TARGET_NEW_HOTELS}"
)

print("=" * 70)


# ============================================================
# LOOP THROUGH SEARCH AREAS
# ============================================================

for search_area in AP_AREAS:


    if (
        new_hotels_collected
        >=
        TARGET_NEW_HOTELS
    ):

        break


    print("\n")
    print("=" * 70)

    print(
        f"SEARCHING: {search_area}"
    )

    print(
        f"NEW HOTEL PROGRESS: "
        f"{new_hotels_collected}/"
        f"{TARGET_NEW_HOTELS}"
    )

    print("=" * 70)


    # ========================================================
    # SEARCH HOTELS
    # ========================================================

    try:

        hotels = search_hotels(
            search_area
        )

    except Exception as e:

        print(
            f"Hotel search failed: {e}"
        )

        continue


    print(
        f"Hotels returned: "
        f"{len(hotels)}"
    )


    # ========================================================
    # PROCESS EACH HOTEL
    # ========================================================

    for hotel in hotels:


        if (
            new_hotels_collected
            >=
            TARGET_NEW_HOTELS
        ):

            break


        # ====================================================
        # HOTEL ID
        # ====================================================

        hotel_id = (
            hotel.get(
                "property_token"
            )
            or
            hotel.get(
                "hotel_id"
            )
        )

        hotel_name = hotel.get(
            "name",
            "Unknown Hotel"
        )


        if not hotel_id:

            print(
                f"SKIP: {hotel_name} "
                f"- no hotel ID"
            )

            continue


        hotel_id = str(
            hotel_id
        )


        # ====================================================
        # SKIP EXISTING HOTEL
        # ====================================================

        if hotel_id in known_hotel_ids:

            print(
                f"SKIP EXISTING: "
                f"{hotel_name}"
            )

            continue


        # ====================================================
        # SKIP DUPLICATE FROM THIS RUN
        # ====================================================

        if hotel_id in new_hotel_ids:

            continue


        print("\n" + "-" * 60)

        print(
            f"NEW HOTEL "
            f"{new_hotels_collected + 1}/"
            f"{TARGET_NEW_HOTELS}"
        )

        print(
            f"Hotel: {hotel_name}"
        )

        print(
            f"Hotel ID: {hotel_id}"
        )

        print(
            f"Area: {search_area}"
        )

        print("-" * 60)


        # ====================================================
        # FETCH REVIEWS
        # ====================================================

        try:

            reviews = fetch_reviews(
                hotel,
                search_area
            )

        except Exception as e:

            print(
                f"Review collection failed: "
                f"{e}"
            )

            reviews = []


        # ====================================================
        # ADD REVIEW DATA
        # ====================================================

        if reviews:

            new_df = pd.DataFrame(
                reviews
            )

            df = pd.concat(
                [
                    df,
                    new_df
                ],
                ignore_index=True
            )

            print(
                f"Reviews collected: "
                f"{len(reviews)}"
            )


        # ====================================================
        # IF NO REVIEWS
        # ====================================================

        else:

            hotel_row = make_hotel_row(
                hotel,
                search_area
            )

            df = pd.concat(
                [
                    df,
                    pd.DataFrame([
                        hotel_row
                    ])
                ],
                ignore_index=True
            )

            print(
                "No reviews found."
            )

            print(
                "Hotel information saved."
            )


        # ====================================================
        # SAVE DATASET
        # ====================================================

        save_dataset()


        # ====================================================
        # UPDATE TRACKING
        # ====================================================

        new_hotel_ids.add(
            hotel_id
        )

        existing_hotel_ids.add(
            hotel_id
        )

        known_hotel_ids.add(
            hotel_id
        )

        new_hotels_collected += 1


        # ====================================================
        # SAVE CHECKPOINT
        # ====================================================

        save_checkpoint(
            hotel_id,
            hotel_name,
            search_area,
            "completed"
        )


        # ====================================================
        # PROGRESS
        # ====================================================

        print(
            f"SUCCESS: {hotel_name}"
        )

        print(
            f"New hotels: "
            f"{new_hotels_collected}/"
            f"{TARGET_NEW_HOTELS}"
        )

        print(
            f"Total unique hotels: "
            f"{df['hotel_id'].nunique()}"
        )

        print(
            f"Total records: "
            f"{len(df)}"
        )


        # ====================================================
        # DELAY
        # ====================================================

        time.sleep(2)


# ============================================================
# FINAL SAVE
# ============================================================

save_dataset()


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("ANDHRA PRADESH SCRAPING COMPLETED")
print("=" * 70)

print(
    f"New hotels collected: "
    f"{new_hotels_collected}"
)

print(
    f"Total unique hotels: "
    f"{df['hotel_id'].nunique()}"
)

print(
    f"Total dataset records: "
    f"{len(df)}"
)

print(
    f"Output file: "
    f"{OUTPUT_FILE}"
)

print(
    f"Checkpoint file: "
    f"{CHECKPOINT_FILE}"
)

print("=" * 70)


# ============================================================
# FINAL STATISTICS
# ============================================================

print("\nFINAL DATASET STATISTICS")

print(
    f"Unique hotels: "
    f"{df['hotel_id'].nunique()}"
)

print(
    f"Total records: "
    f"{len(df)}"
)


if "review_text" in df.columns:

    review_text_count = (
        df["review_text"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
        .sum()
    )

    print(
        f"Records with review text: "
        f"{review_text_count}"
    )


if "individual_review_rating" in df.columns:

    rating_count = (
        df[
            "individual_review_rating"
        ]
        .notna()
        .sum()
    )

    print(
        f"Records with individual review rating: "
        f"{rating_count}"
    )


if "price_per_night" in df.columns:

    price_count = (
        df[
            "price_per_night"
        ]
        .notna()
        .sum()
    )

    print(
        f"Records with price: "
        f"{price_count}"
    )


if "amenities" in df.columns:

    amenities_count = (
        df["amenities"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
        .sum()
    )

    print(
        f"Records with amenities: "
        f"{amenities_count}"
    )


print("\n")
print("=" * 70)
print("DATASET READY")
print("=" * 70)

Enter your SerpApi API key: c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763

======================================================================
EXISTING ANDHRA PRADESH DATASET
======================================================================
Existing records: 1126
Existing unique hotels: 72
New hotels required: 100
Expected final unique hotels: 172
======================================================================
Starting a fresh batch.


======================================================================
ANDHRA PRADESH - NEXT 100 NEW HOTELS
======================================================================
Existing unique hotels: 72
New hotels required: 100
Final target: 172
======================================================================


======================================================================
SEARCHING: Visakhapatnam
NEW HOTEL PROGRESS: 0/100
======================================================================
Hotels returned: 20
SKIP EXISTING: The Butterfly Luxury Serviced Apartments

------------------------------------------------------------
NEW HOTEL 1/100
Hotel: FabHotel Gita Residency
Hotel ID: ChkIiPjvnbTqrrE9Gg0vZy8xMW1zNm12Y2pyEAE
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 22
Dataset saved: 1148 records | 73 unique hotels
SUCCESS: FabHotel Gita Residency
New hotels: 1/100
Total unique hotels: 73
Total records: 1148

------------------------------------------------------------
NEW HOTEL 2/100
Hotel: MAPLE COMFORT HOTEL
Hotel ID: ChoIpdSdvaiUvcvDARoNL2cvMTF3cDFjeTI1axAB
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1178 records | 74 unique hotels
SUCCESS: MAPLE COMFORT HOTEL
New hotels: 2/100
Total unique hotels: 74
Total records: 1178

------------------------------------------------------------
NEW HOTEL 3/100
Hotel: Hotel Bsquare
Hotel ID: ChoIxJSb2P7y3O6tARoNL2cvMTFnMG12OGs5YhAB
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1208 records | 75 unique hotels
SUCCESS: Hotel Bsquare
New hotels: 3/100
Total unique hotels: 75
Total records: 1208

------------------------------------------------------------
NEW HOTEL 4/100
Hotel: Hotel Valley Vista
Hotel ID: ChkIhr3Aite1uO4VGg0vZy8xMXdoNmRkMXp6EAE
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1238 records | 76 unique hotels
SUCCESS: Hotel Valley Vista
New hotels: 4/100
Total unique hotels: 76
Total records: 1238
SKIP EXISTING: The Port Hotel

------------------------------------------------------------
NEW HOTEL 5/100
Hotel: Treebo Sriz Cozy Seethamadhara
Hotel ID: ChoI4LuC2szzjtugARoNL2cvMTFwXzdjXzZ3eRAB
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1268 records | 77 unique hotels
SUCCESS: Treebo Sriz Cozy Seethamadhara
New hotels: 5/100
Total unique hotels: 77
Total records: 1268

------------------------------------------------------------
NEW HOTEL 6/100
Hotel: Hotel Nebo Suites
Hotel ID: ChkImOKU0Jjv6vtiGg0vZy8xMXZxbXZtZF80EAE
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1298 records | 78 unique hotels
SUCCESS: Hotel Nebo Suites
New hotels: 6/100
Total unique hotels: 78
Total records: 1298
SKIP EXISTING: Northway Hotel
SKIP EXISTING: Treebo Marina Grand
SKIP EXISTING: Hotel BUDHIL PARK

------------------------------------------------------------
NEW HOTEL 7/100
Hotel: OYO Townhouse Visakhapatnam
Hotel ID: ChoIoNP-hcrkxarsARoNL2cvMTFybXE5NTNsahAB
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1328 records | 79 unique hotels
SUCCESS: OYO Townhouse Visakhapatnam
New hotels: 7/100
Total unique hotels: 79
Total records: 1328

------------------------------------------------------------
NEW HOTEL 8/100
Hotel: Rainbow Grand Sri Balaji Hotels
Hotel ID: ChkIyKinqvKN0LJnGg0vZy8xMXFtbXltYjI5EAE
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 17
Dataset saved: 1345 records | 80 unique hotels
SUCCESS: Rainbow Grand Sri Balaji Hotels
New hotels: 8/100
Total unique hotels: 80
Total records: 1345

------------------------------------------------------------
NEW HOTEL 9/100
Hotel: Hotel Lakshmi Grand
Hotel ID: ChoIh6Gq7o6pso-1ARoNL2cvMTFiYnd3c3pnZxAB
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1375 records | 81 unique hotels
SUCCESS: Hotel Lakshmi Grand
New hotels: 9/100
Total unique hotels: 81
Total records: 1375
SKIP EXISTING: Hotel Rockdale
SKIP EXISTING: Zora Park Hotel
SKIP EXISTING: Treebo Premium The Regal Park

------------------------------------------------------------
NEW HOTEL 10/100
Hotel: Treebo Raga
Hotel ID: ChoIxseh7pmulqKBARoNL2cvMTFyX3B5YmdncRAB
Area: Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1405 records | 82 unique hotels
SUCCESS: Treebo Raga
New hotels: 10/100
Total unique hotels: 82
Total records: 1405

------------------------------------------------------------
NEW HOTEL 11/100
Hotel: Swagan Home Stays NON AC 1 BHK Deluxe Flat - Two-Bedroom Apartment
Hotel ID: ChkQhdflkfyk4OEuGg0vZy8xMXp3ejZkNmQzEAI
Area: Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 1406 records | 83 unique hotels
SUCCESS: Swagan Home Stays NON AC 1 BHK Deluxe Flat - Two-Bedroom Apartment
New hotels: 11/100
Total unique hotels: 83
Total records: 1406

/tmp/ipykernel_1058/393633700.py:1328: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 12/100
Hotel: AkSHARAINNOTEL
Hotel ID: ChoQ4cOm9IfStt-jARoNL2cvMTFudGhqYzRiORAC
Area: Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 1407 records | 84 unique hotels
SUCCESS: AkSHARAINNOTEL
New hotels: 12/100
Total unique hotels: 84
Total records: 1407


======================================================================
SEARCHING: Vizag
NEW HOTEL PROGRESS: 12/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Northway Hotel
SKIP EXISTING: The Port Hotel
SKIP EXISTING: Keys Select By Lemon Tree Hotel, Visakhapatnam
SKIP EXISTING: Hotel Rockdale
SKIP EXISTING: Treebo Raga
SKIP EXISTING: HOTEL TOUCHWOOD
SKIP EXISTING: Treebo Marina Grand

------------------------------------------------------------
NEW HOTEL 13/100
Hotel: Vibe Vacation Hotels
Hotel ID: ChkIt9DRz9vDvLUKGg0vZy8xMXczbW56em5xEAE
Area: Vizag
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1437 records | 85 unique hotels
SUCCESS: Vibe Vacation Hotels
New hotels: 13/100
Total unique hotels: 85
Total records: 1437
SKIP EXISTING: Hotel BUDHIL PARK
SKIP EXISTING: Olive Hotel Visakhapatnam by Embassy Group
SKIP EXISTING: LJ Dadi's Grand
SKIP EXISTING: Waltair Abode
SKIP EXISTING: The Pioneer

------------------------------------------------------------
NEW HOTEL 14/100
Hotel: Hotel Emerald
Hotel ID: ChkI_sf3wvKhpd8kGg0vZy8xMXduNGowdmxrEAE
Area: Vizag
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1467 records | 86 unique hotels
SUCCESS: Hotel Emerald
New hotels: 14/100
Total unique hotels: 86
Total records: 1467
SKIP EXISTING: MAPLE COMFORT HOTEL
SKIP EXISTING: Hotel Five Elements

------------------------------------------------------------
NEW HOTEL 15/100
Hotel: Quality Inn Bez Krishnaa
Hotel ID: ChgIvZ_3q6ncvbGjARoLL2cvMXRoNTVkcXQQAQ
Area: Vizag
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1497 records | 87 unique hotels
SUCCESS: Quality Inn Bez Krishnaa
New hotels: 15/100
Total unique hotels: 87
Total records: 1497
SKIP EXISTING: Hotel Anantha Suites
SKIP EXISTING: Coastal Horizon Suites
SKIP EXISTING: Magnolia Villa Luxury 3 Bedroom Apartments - Three-Bedroom Apartment


======================================================================
SEARCHING: Dwaraka Nagar Visakhapatnam
NEW HOTEL PROGRESS: 15/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Hotel BUDHIL PARK

------------------------------------------------------------
NEW HOTEL 16/100
Hotel: Treebo Rainbow Grand
Hotel ID: ChkIl9yw9KeOu9IHGg0vZy8xMW41ZDZqc2Q5EAE
Area: Dwaraka Nagar Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1527 records | 88 unique hotels
SUCCESS: Treebo Rainbow Grand
New hotels: 16/100
Total unique hotels: 88
Total records: 1527
SKIP EXISTING: HOTEL TOUCHWOOD
SKIP EXISTING: Dwaraka Inn
SKIP EXISTING: Quality Inn Bez Krishnaa
SKIP EXISTING: OYO Townhouse Visakhapatnam
SKIP EXISTING: Rainbow Grand Sri Balaji Hotels
SKIP EXISTING: Hotel Diamond's Pearl
SKIP EXISTING: Hotel Lakshmi Residency

------------------------------------------------------------
NEW HOTEL 17/100
Hotel: Hotel Lemon Park
Hotel ID: ChoInv7n8-m0-onsARoNL2cvMTF3bmZrY21maxAB
Area: Dwaraka Nagar Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1557 records | 89 unique hotels
SUCCESS: Hotel Lemon Park
New hotels: 17/100
Total unique hotels: 89
Total records: 1557

------------------------------------------------------------
NEW HOTEL 18/100
Hotel: VHOTEL
Hotel ID: ChoI4vyP2PrHkajXARoNL2cvMTFjNTc1MzVndBAB
Area: Dwaraka Nagar Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1587 records | 90 unique hotels
SUCCESS: VHOTEL
New hotels: 18/100
Total unique hotels: 90
Total records: 1587
SKIP EXISTING: Vibe Vacation Hotels
SKIP EXISTING: Hotel Akshaya
SKIP EXISTING: Treebo Marina Grand
SKIP EXISTING: Olive Hotel Visakhapatnam by Embassy Group

------------------------------------------------------------
NEW HOTEL 19/100
Hotel: ROHHOTEL
Hotel ID: ChkIg-G-0LqIhNIjGg0vZy8xMWY5enl0cTA0EAE
Area: Dwaraka Nagar Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1617 records | 91 unique hotels
SUCCESS: ROHHOTEL
New hotels: 19/100
Total unique hotels: 91
Total records: 1617

------------------------------------------------------------
NEW HOTEL 20/100
Hotel: Supine Comfort
Hotel ID: ChkIq7Oyn4SR7JMzGg0vZy8xMWgzY3N4bnI5EAE
Area: Dwaraka Nagar Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1647 records | 92 unique hotels
SUCCESS: Supine Comfort
New hotels: 20/100
Total unique hotels: 92
Total records: 1647
SKIP EXISTING: Royal Fort Hotel
SKIP EXISTING: Coastal Horizon Suites
SKIP EXISTING: Premium Home Stay at VIP Road


======================================================================
SEARCHING: MVP Colony Visakhapatnam
NEW HOTEL PROGRESS: 20/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Treebo MVP Grand
SKIP EXISTING: MAPLE COMFORT HOTEL

------------------------------------------------------------
NEW HOTEL 21/100
Hotel: The Royal Inn
Hotel ID: ChkI3urcku2O6J53Gg0vZy8xMXRnNnk3andfEAE
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1677 records | 93 unique hotels
SUCCESS: The Royal Inn
New hotels: 21/100
Total unique hotels: 93
Total records: 1677

------------------------------------------------------------
NEW HOTEL 22/100
Hotel: Super Hotel O by OYO MVP Double Road
Hotel ID: ChkIn9Ge9MTV35s0Gg0vZy8xMW01X3B6d3p2EAE
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1707 records | 94 unique hotels
SUCCESS: Super Hotel O by OYO MVP Double Road
New hotels: 22/100
Total unique hotels: 94
Total records: 1707

------------------------------------------------------------
NEW HOTEL 23/100
Hotel: Suncrisp Studio Rooms MVP
Hotel ID: ChoIyY-17-He1rqMARoNL2cvMTF5ejdybjlzZhAB
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1737 records | 95 unique hotels
SUCCESS: Suncrisp Studio Rooms MVP
New hotels: 23/100
Total unique hotels: 95
Total records: 1737
SKIP EXISTING: Treebo Raga
SKIP EXISTING: Lotus Park Hotel

------------------------------------------------------------
NEW HOTEL 24/100
Hotel: Homey Meadows - Vizag Beach
Hotel ID: ChkIvomWx5LTwowOGg0vZy8xMXBkMGhubmtnEAE
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1767 records | 96 unique hotels
SUCCESS: Homey Meadows - Vizag Beach
New hotels: 24/100
Total unique hotels: 96
Total records: 1767

------------------------------------------------------------
NEW HOTEL 25/100
Hotel: beestay Hotels MVP Colony
Hotel ID: ChoI8uqr-8Sh07r_ARoNL2cvMTF3aHg2MmM2YxAB
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 24
Dataset saved: 1791 records | 97 unique hotels
SUCCESS: beestay Hotels MVP Colony
New hotels: 25/100
Total unique hotels: 97
Total records: 1791
SKIP EXISTING: Oviya Hotels
SKIP EXISTING: Rosee Wood

------------------------------------------------------------
NEW HOTEL 26/100
Hotel: sri krishna residency mvp vizag
Hotel ID: ChoIgvzXoMHXuMOvARoNL2cvMTFscGR6czhnORAB
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1821 records | 98 unique hotels
SUCCESS: sri krishna residency mvp vizag
New hotels: 26/100
Total unique hotels: 98
Total records: 1821

------------------------------------------------------------
NEW HOTEL 27/100
Hotel: Collection O Hotel MVP CHECK INN
Hotel ID: ChkItOiqxJX7maJiGg0vZy8xMWhfd3Q0MGRiEAE
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1851 records | 99 unique hotels
SUCCESS: Collection O Hotel MVP CHECK INN
New hotels: 27/100
Total unique hotels: 99
Total records: 1851
SKIP EXISTING: Las Vegas

------------------------------------------------------------
NEW HOTEL 28/100
Hotel: SKYLINE LUXURY HOTEL | Best Hotel In MVP | Best Hotel in Vishakhapatnam
Hotel ID: ChkIr-WPhsSJ7rAhGg0vZy8xMXpmdHRqZG44EAE
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 6
Dataset saved: 1857 records | 100 unique hotels
SUCCESS: SKYLINE LUXURY HOTEL | Best Hotel In MVP | Best Hotel in Vishakhapatnam
New hotels: 28/100
Total unique hotels: 100
Total records: 1857
SKIP EXISTING: Gadiraju Palace Convention Center & Hotel

------------------------------------------------------------
NEW HOTEL 29/100
Hotel: MVP Cultural Homestay
Hotel ID: ChoI_bPS1fvo3cCpARoNL2cvMTF6NjFocXJ5NhAB
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 2
Dataset saved: 1859 records | 101 unique hotels
SUCCESS: MVP Cultural Homestay
New hotels: 29/100
Total unique hotels: 101
Total records: 1859

------------------------------------------------------------
NEW HOTEL 30/100
Hotel: BacPac Monkey Home Stay
Hotel ID: ChkIh4eMjKHjspUEGg0vZy8xMW01bmxieXJwEAE
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1889 records | 102 unique hotels
SUCCESS: BacPac Monkey Home Stay
New hotels: 30/100
Total unique hotels: 102
Total records: 1889

------------------------------------------------------------
NEW HOTEL 31/100
Hotel: Elegant 3BHK Villa Stay - Kailasagiri & Beach Road
Hotel ID: ChgQoeL795SBrXcaDS9nLzExbnBweWIzeXAQAg
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 1890 records | 103 unique hotels
SUCCESS: Elegant 3BHK Villa Stay - Kailasagiri & Beach Road
New hotels: 31/100
Total unique hotels: 103
Total records: 1890

/tmp/ipykernel_1058/393633700.py:1328: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 32/100
Hotel: Servostay 5 Fully Furnished 2 BHK Flats in MVP Colony, Vizag
Hotel ID: ChoQ-v_urMjf8-G7ARoNL2cvMTF6eHRneWxqNBAC
Area: MVP Colony Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 1891 records | 104 unique hotels
SUCCESS: Servostay 5 Fully Furnished 2 BHK Flats in MVP Colony, Vizag
New hotels: 32/100
Total unique hotels: 104
Total records: 1891


======================================================================
SEARCHING: Siripuram Visakhapatnam
NEW HOTEL PROGRESS: 32/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Hotel Vivana
SKIP EXISTING: Waltair Abode
SKIP EXISTING: Hotel Rockdale
SKIP EXISTING: Zostel Visakhapatnam (Vizag)
SKIP EXISTING: Hotel Five Elements
SKIP EXISTING: Zora Park Hotel
SKIP EXISTING: HOTEL TOUCHWOOD
SKIP EXISTING: OYO Townhouse Visakhapatnam
SKIP EXISTING: Treebo Rainbow Grand
SKIP EXISTING: The Pioneer
SKIP EXISTING: Olive Hotel Visakhapatnam by Embassy Group
SKIP EXISTING: Rainbow Grand Sri Balaji Hotels
SKIP EXISTING: Treebo Premium Pl Grand, Visakhapatnam

------------------------------------------------------------
NEW HOTEL 33/100
Hotel: Treebo Seaesta Rk Beach
Hotel ID: ChkIpKPttbKJmscQGg0vZy8xMXFwanB5ZmRuEAE
Area: Siripuram Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1921 records | 105 unique hotels
SUCCESS: Treebo Seaesta Rk Beach
New hotels: 33/100
Total unique hotels: 105
Total records: 1921

------------------------------------------------------------
NEW HOTEL 34/100
Hotel: OYO Flagship Hotel Gayatri
Hotel ID: ChgItKSD68nHnNr3ARoLL2cvMXRrbWt6anEQAQ
Area: Siripuram Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1951 records | 106 unique hotels
SUCCESS: OYO Flagship Hotel Gayatri
New hotels: 34/100
Total unique hotels: 106
Total records: 1951
SKIP EXISTING: Hotel BUDHIL PARK
SKIP EXISTING: Hotel Anantha Suites

------------------------------------------------------------
NEW HOTEL 35/100
Hotel: Open Hotel by Olive - Oceanic Vibes
Hotel ID: ChkIiKLMm_Sc9bNSGg0vZy8xMXlqcnR0aHMwEAE
Area: Siripuram Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1981 records | 107 unique hotels
SUCCESS: Open Hotel by Olive - Oceanic Vibes
New hotels: 35/100
Total unique hotels: 107
Total records: 1981

------------------------------------------------------------
NEW HOTEL 36/100
Hotel: aakruthiinn - One-Bedroom Apartment
Hotel ID: ChoQhOTHwNvuzP-iARoNL2cvMTF5dHA0MjdkYxAC
Area: Siripuram Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 1982 records | 108 unique hotels
SUCCESS: aakruthiinn - One-Bedroom Apartment
New hotels: 36/100
Total unique hotels: 108
Total records: 1982

/tmp/ipykernel_1058/393633700.py:1328: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

SKIP EXISTING: Magnolia Villa Luxury 3 Bedroom Apartments - Three-Bedroom Apartment


======================================================================
SEARCHING: Madhurawada Visakhapatnam
NEW HOTEL PROGRESS: 36/100
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 37/100
Hotel: Aariv Home Stay
Hotel ID: ChoI5q6dro3dlY3ZARoNL2cvMTF5NW5tMm55dhAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2012 records | 109 unique hotels
SUCCESS: Aariv Home Stay
New hotels: 37/100
Total unique hotels: 109
Total records: 2012

------------------------------------------------------------
NEW HOTEL 38/100
Hotel: Treebo Imperia, Kommadi
Hotel ID: ChoInPCi_uuwq5yGARoNL2cvMTF5N3RjeXA1axAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2042 records | 110 unique hotels
SUCCESS: Treebo Imperia, Kommadi
New hotels: 38/100
Total unique hotels: 110
Total records: 2042

------------------------------------------------------------
NEW HOTEL 39/100
Hotel: The Capital Hotel
Hotel ID: ChoI1sXp4dnc6YvaARoNL2cvMTFwcGZkaF90cxAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2072 records | 111 unique hotels
SUCCESS: The Capital Hotel
New hotels: 39/100
Total unique hotels: 111
Total records: 2072

------------------------------------------------------------
NEW HOTEL 40/100
Hotel: DVR GRAND - AC HALL AND AC ROOMS
Hotel ID: ChoI5pSw2-y0wbqNARoNL2cvMTF5N2MwM3M5MBAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2102 records | 112 unique hotels
SUCCESS: DVR GRAND - AC HALL AND AC ROOMS
New hotels: 40/100
Total unique hotels: 112
Total records: 2102

------------------------------------------------------------
NEW HOTEL 41/100
Hotel: FabHotel The Sunrise Inn
Hotel ID: ChkI0qrj17usmYUPGg0vZy8xMXNiOWJucjBkEAE
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2132 records | 113 unique hotels
SUCCESS: FabHotel The Sunrise Inn
New hotels: 41/100
Total unique hotels: 113
Total records: 2132

------------------------------------------------------------
NEW HOTEL 42/100
Hotel: Hotel Ram Way
Hotel ID: ChoIjt2n2bilpvKiARoNL2cvMTF6Nm5jMXF3MxAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 28
Dataset saved: 2160 records | 114 unique hotels
SUCCESS: Hotel Ram Way
New hotels: 42/100
Total unique hotels: 114
Total records: 2160

------------------------------------------------------------
NEW HOTEL 43/100
Hotel: The Invitation 365 Hotel
Hotel ID: ChkI0JqSyJ_Mv8l7Gg0vZy8xMWtiNzR0MTczEAE
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2190 records | 115 unique hotels
SUCCESS: The Invitation 365 Hotel
New hotels: 43/100
Total unique hotels: 115
Total records: 2190

------------------------------------------------------------
NEW HOTEL 44/100
Hotel: Collection O
Hotel ID: ChoI67ntgOu5_5fJARoNL2cvMTF2MTh4eWo3OBAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2220 records | 116 unique hotels
SUCCESS: Collection O
New hotels: 44/100
Total unique hotels: 116
Total records: 2220

------------------------------------------------------------
NEW HOTEL 45/100
Hotel: EPIC ROOMS
Hotel ID: ChkIhurcjIDpsdBSGg0vZy8xMXh6MnZrd2YyEAE
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2250 records | 117 unique hotels
SUCCESS: EPIC ROOMS
New hotels: 45/100
Total unique hotels: 117
Total records: 2250

------------------------------------------------------------
NEW HOTEL 46/100
Hotel: Super Hotel O by OYO Vizag IT Hill Rushikonda
Hotel ID: ChoIz-Prjo3wuLzLARoNL2cvMTFqMDI3d2xrcxAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2280 records | 118 unique hotels
SUCCESS: Super Hotel O by OYO Vizag IT Hill Rushikonda
New hotels: 46/100
Total unique hotels: 118
Total records: 2280

------------------------------------------------------------
NEW HOTEL 47/100
Hotel: HOTEL ROCKPORT INN
Hotel ID: ChoImq3HqOyg1JPcARoNL2cvMTFuOXYzal81chAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 25
Dataset saved: 2305 records | 119 unique hotels
SUCCESS: HOTEL ROCKPORT INN
New hotels: 47/100
Total unique hotels: 119
Total records: 2305

------------------------------------------------------------
NEW HOTEL 48/100
Hotel: Treebo Rushi Grand
Hotel ID: ChkIh5m4n5T6-88QGg0vZy8xMWtiMW04emttEAE
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2335 records | 120 unique hotels
SUCCESS: Treebo Rushi Grand
New hotels: 48/100
Total unique hotels: 120
Total records: 2335

------------------------------------------------------------
NEW HOTEL 49/100
Hotel: G Square The Premium Hotel
Hotel ID: ChkIxqqh8dj31p8sGg0vZy8xMXl2amJiMTJuEAE
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2365 records | 121 unique hotels
SUCCESS: G Square The Premium Hotel
New hotels: 49/100
Total unique hotels: 121
Total records: 2365

------------------------------------------------------------
NEW HOTEL 50/100
Hotel: Housr Rushikonda 30
Hotel ID: ChoI2pLe9rrFr-aTARoNL2cvMTF3MXBfcXBkMxAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2395 records | 122 unique hotels
SUCCESS: Housr Rushikonda 30
New hotels: 50/100
Total unique hotels: 122
Total records: 2395

------------------------------------------------------------
NEW HOTEL 51/100
Hotel: Treebo Breeze Way Rushikonda With Swimming Pool
Hotel ID: ChoIvZyGwILsrsDfARoNL2cvMTFtY2Y3dmdmdBAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2425 records | 123 unique hotels
SUCCESS: Treebo Breeze Way Rushikonda With Swimming Pool
New hotels: 51/100
Total unique hotels: 123
Total records: 2425

------------------------------------------------------------
NEW HOTEL 52/100
Hotel: Mj Stay Inn Premium Rooms
Hotel ID: ChoI2test52-xNKHARoNL2cvMTF5ZGcyNWJmeBAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2455 records | 124 unique hotels
SUCCESS: Mj Stay Inn Premium Rooms
New hotels: 52/100
Total unique hotels: 124
Total records: 2455

------------------------------------------------------------
NEW HOTEL 53/100
Hotel: Via The Sunrise Inn
Hotel ID: ChoIvYSqmsG8xYzeARoNL2cvMTFuamN4bnMxZxAB
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 1
Dataset saved: 2456 records | 125 unique hotels
SUCCESS: Via The Sunrise Inn
New hotels: 53/100
Total unique hotels: 125
Total records: 2456

------------------------------------------------------------
NEW HOTEL 54/100
Hotel: Super Hotel O by OYO Rushikonda Beach
Hotel ID: ChkIk63kgdC6iew-Gg0vZy8xMWozdjhkNXQwEAE
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2486 records | 126 unique hotels
SUCCESS: Super Hotel O by OYO Rushikonda Beach
New hotels: 54/100
Total unique hotels: 126
Total records: 2486

------------------------------------------------------------
NEW HOTEL 55/100
Hotel: Prashant Homes - One-Bedroom Apartment
Hotel ID: ChoQ5aLpg5-__M_YARoNL2cvMTF5Y2dxNnA3NRAC
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 2487 records | 127 unique hotels
SUCCESS: Prashant Homes - One-Bedroom Apartment
New hotels: 55/100
Total unique hotels: 127
Total records: 2487

/tmp/ipykernel_1058/393633700.py:1328: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 56/100
Hotel: Visakha Waves Residences
Hotel ID: ChoQkKqv9I6flIncARoNL2cvMTF6eW1uc3RmeBAC
Area: Madhurawada Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 2488 records | 128 unique hotels
SUCCESS: Visakha Waves Residences
New hotels: 56/100
Total unique hotels: 128
Total records: 2488

/tmp/ipykernel_1058/393633700.py:1328: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCHING: Gajuwaka Visakhapatnam
NEW HOTEL PROGRESS: 56/100
======================================================================
Hotels returned: 18

------------------------------------------------------------
NEW HOTEL 57/100
Hotel: hotels
Hotel ID: ChoI2deg2viT-6WaARoNL2cvMTF6OGtzX3R0chAB
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 2489 records | 129 unique hotels
SUCCESS: hotels
New hotels: 57/100
Total unique hotels: 129
Total records: 2489

/tmp/ipykernel_1058/393633700.py:1328: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 58/100
Hotel: Hotel SM PARADISE
Hotel ID: ChoInb2Z7JD7u_fLARoNL2cvMTFqc2RmMzM4NBAB
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2519 records | 130 unique hotels
SUCCESS: Hotel SM PARADISE
New hotels: 58/100
Total unique hotels: 130
Total records: 2519

------------------------------------------------------------
NEW HOTEL 59/100
Hotel: Treebo Ar Grand, Gajuwaka
Hotel ID: ChgImPXjjMDPgoQlGgwvZy8xaGY3ZjI2ajQQAQ
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2549 records | 131 unique hotels
SUCCESS: Treebo Ar Grand, Gajuwaka
New hotels: 59/100
Total unique hotels: 131
Total records: 2549

------------------------------------------------------------
NEW HOTEL 60/100
Hotel: OYO Townhouse Gajuwaka Centre
Hotel ID: ChoI66mOhuuk36fUARoNL2cvMTF3dHdjMXkycRAB
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2579 records | 132 unique hotels
SUCCESS: OYO Townhouse Gajuwaka Centre
New hotels: 60/100
Total unique hotels: 132
Total records: 2579

------------------------------------------------------------
NEW HOTEL 61/100
Hotel: CannyStay G V Inn
Hotel ID: ChoIkMnP8KWvq7GwARoNL2cvMTFqMmxmOGJzeRAB
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2609 records | 133 unique hotels
SUCCESS: CannyStay G V Inn
New hotels: 61/100
Total unique hotels: 133
Total records: 2609

------------------------------------------------------------
NEW HOTEL 62/100
Hotel: Hotel Meghalaya - Gajuwaka
Hotel ID: ChkIxbGLytrx9-w3Gg0vZy8xMXZ5Y2J6ZHAxEAE
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2639 records | 134 unique hotels
SUCCESS: Hotel Meghalaya - Gajuwaka
New hotels: 62/100
Total unique hotels: 134
Total records: 2639

------------------------------------------------------------
NEW HOTEL 63/100
Hotel: My space Kenilworth
Hotel ID: ChkI0_S8t6PL2J8yGg0vZy8xMXc4c3Roam1jEAE
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2669 records | 135 unique hotels
SUCCESS: My space Kenilworth
New hotels: 63/100
Total unique hotels: 135
Total records: 2669

------------------------------------------------------------
NEW HOTEL 64/100
Hotel: Hotel O
Hotel ID: ChkIjP7BnuXJ4oBBGg0vZy8xMWoybDdkc3FoEAE
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2699 records | 136 unique hotels
SUCCESS: Hotel O
New hotels: 64/100
Total unique hotels: 136
Total records: 2699

------------------------------------------------------------
NEW HOTEL 65/100
Hotel: Hotel Green Apple
Hotel ID: ChoIz5Kl4sXuk7fgARoNL2cvMTFiN2w2emN4dBAB
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2729 records | 137 unique hotels
SUCCESS: Hotel Green Apple
New hotels: 65/100
Total unique hotels: 137
Total records: 2729
SKIP EXISTING: FabHotel Gita Residency

------------------------------------------------------------
NEW HOTEL 66/100
Hotel: Keys Lite by Lemon Tree Hotels, Sreekanya, Visakhapatnam
Hotel ID: ChoIo4_vzLb2nYz0ARoNL2cvMTF0aGp0azdyaxAB
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2759 records | 138 unique hotels
SUCCESS: Keys Lite by Lemon Tree Hotels, Sreekanya, Visakhapatnam
New hotels: 66/100
Total unique hotels: 138
Total records: 2759

------------------------------------------------------------
NEW HOTEL 67/100
Hotel: Hotel O Pedagantyada Gajuwaka
Hotel ID: ChkIrofry9DdnfRYGg0vZy8xMXpoOTdsN3M5EAE
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 2760 records | 139 unique hotels
SUCCESS: Hotel O Pedagantyada Gajuwaka
New hotels: 67/100
Total unique hotels: 139
Total records: 2760

/tmp/ipykernel_1058/393633700.py:1328: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 68/100
Hotel: Hotel Meena Paradise
Hotel ID: ChoI6ZK67t2imc_ZARoNL2cvMTFiYnJneGx0YhAB
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2790 records | 140 unique hotels
SUCCESS: Hotel Meena Paradise
New hotels: 68/100
Total unique hotels: 140
Total records: 2790

------------------------------------------------------------
NEW HOTEL 69/100
Hotel: OYO Townhouse Gajuwaka Near CMR Mall
Hotel ID: ChkI153ApuOwzIMjGg0vZy8xMWI1eXRnOV9xEAE
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2820 records | 141 unique hotels
SUCCESS: OYO Townhouse Gajuwaka Near CMR Mall
New hotels: 69/100
Total unique hotels: 141
Total records: 2820

------------------------------------------------------------
NEW HOTEL 70/100
Hotel: Hotel Phoenix Grand
Hotel ID: ChkI8bWf9Nja9c49Gg0vZy8xMW01Y3poaHRrEAE
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 28
Dataset saved: 2848 records | 142 unique hotels
SUCCESS: Hotel Phoenix Grand
New hotels: 70/100
Total unique hotels: 142
Total records: 2848

------------------------------------------------------------
NEW HOTEL 71/100
Hotel: Seasons Comfort
Hotel ID: ChkIi9bHv-G4uN8UGg0vZy8xMWo0OTF6bHFtEAE
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2878 records | 143 unique hotels
SUCCESS: Seasons Comfort
New hotels: 71/100
Total unique hotels: 143
Total records: 2878

------------------------------------------------------------
NEW HOTEL 72/100
Hotel: 7 Apple Hotel - Vishakhapatnam
Hotel ID: ChoIyqe2j5jNj8PuARoNL2cvMTFtNWdzNzQzaBAB
Area: Gajuwaka Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2908 records | 144 unique hotels
SUCCESS: 7 Apple Hotel - Vishakhapatnam
New hotels: 72/100
Total unique hotels: 144
Total records: 2908
SKIP EXISTING: Best Western Plus Ramachandra Hotel


======================================================================
SEARCHING: Rushikonda Visakhapatnam
NEW HOTEL PROGRESS: 72/100
======================================================================
Hotels returned: 18

------------------------------------------------------------
NEW HOTEL 73/100
Hotel: Sai Priya Beach Resort
Hotel ID: ChgIs8D2iu-2tru2ARoLL2cvMXRrMjFicXgQAQ
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2938 records | 145 unique hotels
SUCCESS: Sai Priya Beach Resort
New hotels: 73/100
Total unique hotels: 145
Total records: 2938
SKIP EXISTING: The Capital Hotel
SKIP EXISTING: Treebo Rushi Grand

------------------------------------------------------------
NEW HOTEL 74/100
Hotel: Shore Front Resort
Hotel ID: ChoI2o7o8r3Dl4TYARoNL2cvMTFmazVyaHkwZhAB
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2968 records | 146 unique hotels
SUCCESS: Shore Front Resort
New hotels: 74/100
Total unique hotels: 146
Total records: 2968

------------------------------------------------------------
NEW HOTEL 75/100
Hotel: Treebo Premium Ocean Echo, Rushikonda
Hotel ID: ChoI3Iez7c2l9rT6ARoNL2cvMTF5YjY2ODg5OBAB
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2998 records | 147 unique hotels
SUCCESS: Treebo Premium Ocean Echo, Rushikonda
New hotels: 75/100
Total unique hotels: 147
Total records: 2998
SKIP EXISTING: Housr Rushikonda 30

------------------------------------------------------------
NEW HOTEL 76/100
Hotel: Hotel Wave Rock
Hotel ID: ChkI-KHc_OPko4xBGg0vZy8xMXpmYzUza3ZtEAE
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 19
Dataset saved: 3017 records | 148 unique hotels
SUCCESS: Hotel Wave Rock
New hotels: 76/100
Total unique hotels: 148
Total records: 3017
SKIP EXISTING: Treebo Breeze Way Rushikonda With Swimming Pool
SKIP EXISTING: DVR GRAND - AC HALL AND AC ROOMS

------------------------------------------------------------
NEW HOTEL 77/100
Hotel: The 36 Inn Yendada
Hotel ID: ChoI-6HekOyHrLTLARoNL2cvMTFuY2hqcmtzeRAB
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3047 records | 149 unique hotels
SUCCESS: The 36 Inn Yendada
New hotels: 77/100
Total unique hotels: 149
Total records: 3047

------------------------------------------------------------
NEW HOTEL 78/100
Hotel: Hotel Serene Praia
Hotel ID: ChkI0dHgu5XJ15ttGg0vZy8xMXh0bHoxazNnEAE
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3077 records | 150 unique hotels
SUCCESS: Hotel Serene Praia
New hotels: 78/100
Total unique hotels: 150
Total records: 3077

------------------------------------------------------------
NEW HOTEL 79/100
Hotel: Hotel Ocean View
Hotel ID: ChkIlvXgn__YquMSGg0vZy8xMXRtcnJiMmJzEAE
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3107 records | 151 unique hotels
SUCCESS: Hotel Ocean View
New hotels: 79/100
Total unique hotels: 151
Total records: 3107

------------------------------------------------------------
NEW HOTEL 80/100
Hotel: Vizag cruise hotel
Hotel ID: ChoIqbv5_J65zM7KARoNL2cvMTFsY252M3k0axAB
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3137 records | 152 unique hotels
SUCCESS: Vizag cruise hotel
New hotels: 80/100
Total unique hotels: 152
Total records: 3137

------------------------------------------------------------
NEW HOTEL 81/100
Hotel: Pema Wellness Resort
Hotel ID: ChgIt5OTtPePkfR-GgwvZy8xaG01bHcwOWgQAQ
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3167 records | 153 unique hotels
SUCCESS: Pema Wellness Resort
New hotels: 81/100
Total unique hotels: 153
Total records: 3167

------------------------------------------------------------
NEW HOTEL 82/100
Hotel: SIERA BEACH HOTEL
Hotel ID: ChoIyL-gi5m0y5DoARoNL2cvMTFydDdtOGR0MhAB
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3197 records | 154 unique hotels
SUCCESS: SIERA BEACH HOTEL
New hotels: 82/100
Total unique hotels: 154
Total records: 3197

------------------------------------------------------------
NEW HOTEL 83/100
Hotel: Treebo Trend Sea Breeze - Rushikonda
Hotel ID: ChkIwtavlIqVwdFMGg0vZy8xMWxkMmhzMzk3EAE
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 2
Dataset saved: 3199 records | 155 unique hotels
SUCCESS: Treebo Trend Sea Breeze - Rushikonda
New hotels: 83/100
Total unique hotels: 155
Total records: 3199

------------------------------------------------------------
NEW HOTEL 84/100
Hotel: The HIVE
Hotel ID: ChkI2qn3sfrFpt19Gg0vZy8xMXk2YjZ4eG10EAE
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3229 records | 156 unique hotels
SUCCESS: The HIVE
New hotels: 84/100
Total unique hotels: 156
Total records: 3229

------------------------------------------------------------
NEW HOTEL 85/100
Hotel: Collection O Beach Road Near GITAM
Hotel ID: ChkI18SFi4iVwsdFGg0vZy8xMW42cV9mY2RwEAE
Area: Rushikonda Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3259 records | 157 unique hotels
SUCCESS: Collection O Beach Road Near GITAM
New hotels: 85/100
Total unique hotels: 157
Total records: 3259


======================================================================
SEARCHING: Beach Road Visakhapatnam
NEW HOTEL PROGRESS: 85/100
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 86/100
Hotel: Lumis Beach Hotel
Hotel ID: ChkInJiwie2dl9l-Gg0vZy8xMXo4M3J4Z2NxEAE
Area: Beach Road Visakhapatnam
------------------------------------------------------------
Reviews collected: 26
Dataset saved: 3285 records | 158 unique hotels
SUCCESS: Lumis Beach Hotel
New hotels: 86/100
Total unique hotels: 158
Total records: 3285

------------------------------------------------------------
NEW HOTEL 87/100
Hotel: Penthouse RK Beach - Three-Bedroom Apartment
Hotel ID: ChoQrLyFypqB85mrARoNL2cvMTF4ZnN5cjN5NRAC
Area: Beach Road Visakhapatnam
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 3286 records | 159 unique hotels
SUCCESS: Penthouse RK Beach - Three-Bedroom Apartment
New hotels: 87/100
Total unique hotels: 159
Total records: 3286

/tmp/ipykernel_1058/393633700.py:1328: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

SKIP EXISTING: The Port Hotel
SKIP EXISTING: Hotel Rockdale

------------------------------------------------------------
NEW HOTEL 88/100
Hotel: Beach stay guest house
Hotel ID: ChoI8q_5hrW9yaiHARoNL2cvMTFwYms1anZyMRAB
Area: Beach Road Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3316 records | 160 unique hotels
SUCCESS: Beach stay guest house
New hotels: 88/100
Total unique hotels: 160
Total records: 3316
SKIP EXISTING: Hotel Emerald
SKIP EXISTING: Hotel Five Elements

------------------------------------------------------------
NEW HOTEL 89/100
Hotel: Sky Mountains Guest House
Hotel ID: ChoIruTl3qXp1eONARoNL2cvMTF4bmhoOXdwcxAB
Area: Beach Road Visakhapatnam
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 3346 records | 161 unique hotels
SUCCESS: Sky Mountains Guest House
New hotels: 89/100
Total unique hotels: 161
Total records: 3346

------------------------------------------------------------
NEW HOTEL 90/100
Hotel: Bay View Hotel Vizag
Hotel ID: ChoIl_-TuMisqq70ARoNL2cvMTFoN2Z6OHBychAB
Area: Beach Road Visakhapatnam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChoIl_-TuMisqq70ARoNL2cvMTFoN2Z6OHBychAB&hl=en&sort_by=2&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763&next_page_token=Ci8IARInCgoAP72F-I1UeD__EhAPQng1HeYLGiBoNbEAAAAAGgf_Al-I1UeDGAAiAA%3A10
Reviews collected: 10
Dataset saved: 3356 records | 162 unique hotels
SUCCESS: Bay View Hotel Vizag
New hotels: 90/100
Total unique hotels: 162
Total records: 3356
SKIP EXISTING: Hotel Leela Imperial
SKIP EXISTING: Open Hotel by Olive - Oceanic Vibes
SKIP EXISTING: Treebo Seaesta Rk Beach

------------------------------------------------------------
NEW HOTEL 91/100
Hotel: Dolphin Hotel
Hotel ID: ChcIhI_ThoSdy7p-GgsvZy8xdGs0cGt6axAB
Area: Beach Road Visakhapatnam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChcIhI_ThoSdy7p-GgsvZy8xdGs0cGt6axAB&hl=en&sort_by=2&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763
No reviews found.
Hotel information saved.
Dataset saved: 3357 records | 163 unique hotels
SUCCESS: Dolphin Hotel
New hotels: 91/100
Total unique hotels: 163
Total records: 3357

------------------------------------------------------------
NEW HOTEL 92/100
Hotel: Akshaya Grand
Hotel ID: ChkIgom6k9b61OdpGg0vZy8xMXdtamhtOXkzEAE
Area: Beach Road Visakhapatnam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkIgom6k9b61OdpGg0vZy8xMXdtamhtOXkzEAE&hl=en&sort_by=2&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763
No reviews found.
Hotel information saved.
Dataset saved: 3358 records | 164 unique hotels
SUCCESS: Akshaya Grand
New hotels: 92/100
Total unique hotels: 164
Total records: 3358

------------------------------------------------------------
NEW HOTEL 93/100
Hotel: 6 Beach facing Hotel Suites in Lovely R.K. Beach, Visakhapatnam, with AC, WiFi
Hotel ID: ChkQ4pmd1rCr5LtKGg0vZy8xMW1reTdtejM2EAI
Area: Beach Road Visakhapatnam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkQ4pmd1rCr5LtKGg0vZy8xMW1reTdtejM2EAI&hl=en&sort_by=2&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763
No reviews found.
Hotel information saved.

/tmp/ipykernel_1058/393633700.py:1328: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

Dataset saved: 3359 records | 165 unique hotels
SUCCESS: 6 Beach facing Hotel Suites in Lovely R.K. Beach, Visakhapatnam, with AC, WiFi
New hotels: 93/100
Total unique hotels: 165
Total records: 3359
SKIP EXISTING: Northway Hotel
SKIP EXISTING: Treebo Premium The Regal Park
SKIP EXISTING: Hotel Kinnera Comforts
SKIP EXISTING: Gadiraju Palace Convention Center & Hotel

------------------------------------------------------------
NEW HOTEL 94/100
Hotel: Blue Moon Hotel
Hotel ID: ChkI-_aboMeZ-p9UGg0vZy8xMWd2MDc0YnAzEAE
Area: Beach Road Visakhapatnam
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkI-_aboMeZ-p9UGg0vZy8xMWd2MDc0YnAzEAE&hl=en&sort_by=2&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763
No reviews found.
Hotel information saved.
Dataset saved: 3360 records | 166 unique hotels
SUCCESS: Blue Moon Hotel
New hotels: 94/100
Total unique hotels: 166
Total records: 3360


======================================================================
SEARCHING: RK Beach Visakhapatnam
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+RK+Beach+Visakhapatnam%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Waltair Visakhapatnam
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Waltair+Visakhapatnam%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Visakhapatnam Airport
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Visakhapatnam+Airport%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Seethammadhara Visakhapatnam
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Seethammadhara+Visakhapatnam%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Akkayyapalem Visakhapatnam
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Akkayyapalem+Visakhapatnam%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Dabagardens Visakhapatnam
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Dabagardens+Visakhapatnam%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Kurmannapalem Visakhapatnam
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Kurmannapalem+Visakhapatnam%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Benz Circle Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Benz+Circle+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Governorpet Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Governorpet+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Moghalrajpuram Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Moghalrajpuram+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Labbipet Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Labbipet+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Bhavanipuram Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Bhavanipuram+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Poranki Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Poranki+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Gollapudi Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Gollapudi+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Patamata Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Patamata+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Auto Nagar Vijayawada
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Auto+Nagar+Vijayawada%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Tirupati
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Tirupati%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Tirumala
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Tirumala%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Renigunta
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Renigunta%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Tiruchanur
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Tiruchanur%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Kapila Theertham Tirupati
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Kapila+Theertham+Tirupati%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Alipiri Tirupati
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Alipiri+Tirupati%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Tirupati Railway Station
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Tirupati+Railway+Station%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Guntur
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Guntur%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Brodipet Guntur
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Brodipet+Guntur%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Arundelpet Guntur
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Arundelpet+Guntur%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Lakshmipuram Guntur
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Lakshmipuram+Guntur%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Mangalagiri
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Mangalagiri%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Amaravati
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Amaravati%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Tadepalli
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Tadepalli%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Nellore
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Nellore%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Magunta Layout Nellore
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Magunta+Layout+Nellore%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Dargamitta Nellore
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Dargamitta+Nellore%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Vedayapalem Nellore
NEW HOTEL PROGRESS: 94/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Vedayapalem+Nellore%2C+Andhra+Pradesh&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=c83390bd00bccbdebe7a00eee8b8d36bd529e9a9b553635a05f81dbee4d29763


======================================================================
SEARCHING: Kakinada
NEW HOTEL PROGRESS: 94/100
======================================================================

In [ ]:
from google.colab import files

files.download("andhra_pradesh_hotel_dataset.csv")

In [ ]:
import os
import time
import requests
import pandas as pd

# ============================================================
# CONFIGURATION
# ============================================================

API_KEY = input("Enter your SerpApi API key: ").strip()

OUTPUT_FILE = "jaipur_hotel_dataset.csv"

# Separate checkpoint for Jaipur
CHECKPOINT_FILE = "jaipur_100_checkpoint.csv"

CITY = "Jaipur"
STATE = "Rajasthan"

# Number of UNIQUE Jaipur hotels required
TARGET_NEW_HOTELS = 100

# Maximum review pages per hotel
MAX_REVIEW_PAGES = 3

BASE_URL = "https://serpapi.com/search.json"


# ============================================================
# JAIPUR SEARCH AREAS
# ============================================================

JAIPUR_AREAS = [

    # --------------------------------------------------------
    # CENTRAL / BUSINESS AREAS
    # --------------------------------------------------------

    "C Scheme Jaipur",
    "MI Road Jaipur",
    "Ashok Nagar Jaipur",
    "Panch Batti Jaipur",
    "Statue Circle Jaipur",
    "Civil Lines Jaipur",
    "Bais Godam Jaipur",
    "22 Godam Jaipur",
    "Sodala Jaipur",
    "Hawa Sadak Jaipur",

    # --------------------------------------------------------
    # BANI PARK / RAILWAY STATION
    # --------------------------------------------------------

    "Bani Park Jaipur",
    "Jaipur Railway Station",
    "Gopalbari Jaipur",
    "Sindhi Camp Jaipur",
    "Station Road Jaipur",
    "Khatipura Jaipur",
    "Hasanpura Jaipur",
    "Shastri Nagar Jaipur",

    # --------------------------------------------------------
    # OLD CITY / HERITAGE AREAS
    # --------------------------------------------------------

    "Pink City Jaipur",
    "Old City Jaipur",
    "Hawa Mahal Jaipur",
    "City Palace Jaipur",
    "Johari Bazaar Jaipur",
    "Bapu Bazaar Jaipur",
    "Tripolia Bazaar Jaipur",
    "Chandpole Jaipur",
    "Ramganj Jaipur",
    "Choura Rasta Jaipur",

    # --------------------------------------------------------
    # RAJA PARK / ADARSH NAGAR
    # --------------------------------------------------------

    "Raja Park Jaipur",
    "Adarsh Nagar Jaipur",
    "Jawahar Nagar Jaipur",
    "Tilak Nagar Jaipur",
    "Moti Doongri Jaipur",

    # --------------------------------------------------------
    # MALVIYA NAGAR
    # --------------------------------------------------------

    "Malviya Nagar Jaipur",
    "JLN Marg Jaipur",
    "Jawahar Circle Jaipur",
    "Durgapura Jaipur",
    "Jagatpura Jaipur",
    "Sanganer Jaipur",

    # --------------------------------------------------------
    # AIRPORT AREA
    # --------------------------------------------------------

    "Jaipur Airport",
    "Jaipur International Airport",
    "Airport Road Jaipur",
    "Tonk Road Jaipur",
    "Pratap Nagar Jaipur",

    # --------------------------------------------------------
    # TONK ROAD
    # --------------------------------------------------------

    "Tonk Road Jaipur",
    "Gopalpura Jaipur",
    "Gopalpura Bypass Jaipur",
    "Triveni Nagar Jaipur",
    "Mahesh Nagar Jaipur",

    # --------------------------------------------------------
    # VAISHALI NAGAR / WEST JAIPUR
    # --------------------------------------------------------

    "Vaishali Nagar Jaipur",
    "Gandhi Path Jaipur",
    "Ajmer Road Jaipur",
    "Nirman Nagar Jaipur",
    "Shyam Nagar Jaipur",
    "Sodala Jaipur",
    "Dharam Nagar Jaipur",

    # --------------------------------------------------------
    # VIDHYADHAR NAGAR / NORTH JAIPUR
    # --------------------------------------------------------

    "Vidhyadhar Nagar Jaipur",
    "Murlipura Jaipur",
    "Jhotwara Jaipur",
    "Vishwakarma Industrial Area Jaipur",
    "Sikar Road Jaipur",

    # --------------------------------------------------------
    # MANSAROVAR
    # --------------------------------------------------------

    "Mansarovar Jaipur",
    "New Sanganer Road Jaipur",
    "Patrakar Colony Jaipur",
    "Madhyam Marg Jaipur",
    "Shipra Path Jaipur",

    # --------------------------------------------------------
    # AMER / HERITAGE BELT
    # --------------------------------------------------------

    "Amer Jaipur",
    "Amer Fort Jaipur",
    "Kukas Jaipur",
    "Delhi Road Jaipur",
    "Kunda Jaipur",
    "Jaigarh Fort Jaipur",
    "Nahargarh Jaipur",

    # --------------------------------------------------------
    # DELHI ROAD
    # --------------------------------------------------------

    "Delhi Road Jaipur",
    "Kukas",
    "Achrol Jaipur",
    "Chomu Jaipur",

    # --------------------------------------------------------
    # OUTER JAIPUR / TOURISM
    # --------------------------------------------------------

    "Kanak Vrindavan Jaipur",
    "Jaisinghpura Jaipur",
    "Sawai Jai Singh Highway Jaipur",
    "Agra Road Jaipur",
    "Ramgarh Road Jaipur",

    # --------------------------------------------------------
    # IMPORTANT LOCALITIES
    # --------------------------------------------------------

    "Crown Plaza Jaipur",
    "Rambagh Jaipur",
    "Bhawani Singh Road Jaipur",
    "Sawai Ram Singh Road Jaipur",
    "Prithviraj Road Jaipur",
    "Bhankrota Jaipur",
    "Mahapura Jaipur",
    "Mansarovar Extension Jaipur"
]

# Remove duplicate areas
JAIPUR_AREAS = list(
    dict.fromkeys(JAIPUR_AREAS)
)


# ============================================================
# LOAD EXISTING JAIPUR DATASET
# ============================================================

if os.path.exists(OUTPUT_FILE):

    df = pd.read_csv(
        OUTPUT_FILE
    )

    print("\n" + "=" * 70)
    print("EXISTING JAIPUR DATASET")
    print("=" * 70)

    print(
        f"Existing records: {len(df)}"
    )

else:

    df = pd.DataFrame()

    print(
        "No existing Jaipur dataset found."
    )

    print(
        "Starting a fresh Jaipur dataset."
    )


# ============================================================
# GET EXISTING HOTEL IDS
# ============================================================

if (
    not df.empty
    and
    "hotel_id" in df.columns
):

    df["hotel_id"] = (
        df["hotel_id"]
        .astype(str)
    )

    existing_hotel_ids = set(
        df["hotel_id"]
        .dropna()
        .astype(str)
    )

    existing_hotel_ids.discard(
        "nan"
    )

else:

    existing_hotel_ids = set()


print(
    f"Existing unique hotels: "
    f"{len(existing_hotel_ids)}"
)

print(
    f"New hotels required: "
    f"{TARGET_NEW_HOTELS}"
)

print(
    f"Expected final unique hotels: "
    f"{len(existing_hotel_ids) + TARGET_NEW_HOTELS}"
)

print("=" * 70)


# ============================================================
# LOAD CHECKPOINT
# ============================================================

if os.path.exists(
    CHECKPOINT_FILE
):

    checkpoint = pd.read_csv(
        CHECKPOINT_FILE
    )

    if not checkpoint.empty:

        completed_hotels = set(
            checkpoint.loc[
                checkpoint["status"] == "completed",
                "hotel_id"
            ]
            .astype(str)
        )

    else:

        completed_hotels = set()

    print(
        f"Previously completed in this batch: "
        f"{len(completed_hotels)}"
    )

else:

    checkpoint = pd.DataFrame(
        columns=[
            "hotel_id",
            "hotel_name",
            "search_area",
            "status"
        ]
    )

    completed_hotels = set()

    print(
        "No Jaipur checkpoint found."
    )

    print(
        "Starting fresh."
    )


# ============================================================
# KNOWN HOTEL IDS
# ============================================================

known_hotel_ids = (
    existing_hotel_ids |
    completed_hotels
)


# ============================================================
# SAVE CHECKPOINT
# ============================================================

def save_checkpoint(
    hotel_id,
    hotel_name,
    search_area,
    status
):

    global checkpoint

    hotel_id = str(
        hotel_id
    )

    # Remove previous entry
    checkpoint = checkpoint[
        checkpoint["hotel_id"].astype(str)
        != hotel_id
    ]

    new_row = pd.DataFrame([
        {
            "hotel_id":
                hotel_id,

            "hotel_name":
                hotel_name,

            "search_area":
                search_area,

            "status":
                status
        }
    ])

    checkpoint = pd.concat(
        [
            checkpoint,
            new_row
        ],
        ignore_index=True
    )

    checkpoint.to_csv(
        CHECKPOINT_FILE,
        index=False
    )


# ============================================================
# SAVE DATASET
# ============================================================

def save_dataset():

    global df

    # Ensure hotel ID is string
    if "hotel_id" in df.columns:

        df["hotel_id"] = (
            df["hotel_id"]
            .astype(str)
        )

    # Remove duplicate review IDs
    if "review_id" in df.columns:

        valid_review_ids = (
            df["review_id"]
            .fillna("")
            .astype(str)
            .str.strip()
            != ""
        )

        df_with_ids = df[
            valid_review_ids
        ].drop_duplicates(
            subset=["review_id"]
        )

        df_without_ids = df[
            ~valid_review_ids
        ]

        df = pd.concat(
            [
                df_with_ids,
                df_without_ids
            ],
            ignore_index=True
        )

    else:

        df = df.drop_duplicates()

    # Save
    df.to_csv(
        OUTPUT_FILE,
        index=False
    )

    print(
        f"Dataset saved: "
        f"{len(df)} records | "
        f"{df['hotel_id'].nunique()} unique hotels"
    )


# ============================================================
# SEARCH HOTELS USING SERPAPI
# ============================================================

def search_hotels(
    search_area
):

    params = {

        "engine":
            "google_hotels",

        "q":
            f"Hotels in {search_area}, Jaipur, Rajasthan",

        "check_in_date":
            "2026-10-15",

        "check_out_date":
            "2026-10-16",

        "adults":
            "2",

        "currency":
            "INR",

        "gl":
            "in",

        "hl":
            "en",

        "api_key":
            API_KEY
    }

    response = requests.get(
        BASE_URL,
        params=params,
        timeout=60
    )

    response.raise_for_status()

    data = response.json()

    if "error" in data:

        print(
            f"SerpApi error: "
            f"{data['error']}"
        )

        return []

    return data.get(
        "properties",
        []
    )


# ============================================================
# EXTRACT LOCATION
# ============================================================

def extract_location(
    hotel
):

    gps = hotel.get(
        "gps_coordinates"
    )

    if gps:

        latitude = gps.get(
            "latitude"
        )

        longitude = gps.get(
            "longitude"
        )

        if (
            latitude is not None
            and
            longitude is not None
        ):

            return (
                f"Latitude: {latitude}, "
                f"Longitude: {longitude}"
            )

    return hotel.get(
        "address",
        ""
    )


# ============================================================
# EXTRACT AMENITIES
# ============================================================

def extract_amenities(
    hotel
):

    amenities = []

    for amenity in hotel.get(
        "amenities",
        []
    ):

        if isinstance(
            amenity,
            str
        ):

            amenities.append(
                amenity
            )

        elif isinstance(
            amenity,
            dict
        ):

            name = (
                amenity.get("name")
                or
                amenity.get("title")
            )

            if name:

                amenities.append(
                    str(name)
                )

    # Remove duplicate amenities
    amenities = list(
        dict.fromkeys(
            amenities
        )
    )

    return " | ".join(
        amenities
    )


# ============================================================
# EXTRACT PRICE
# ============================================================

def extract_price(
    hotel
):

    price = hotel.get(
        "rate_per_night",
        {}
    )

    if isinstance(
        price,
        dict
    ):

        value = (
            price.get("lowest")
            or
            price.get("extracted_lowest")
        )

        if value is not None:

            return value

    if hotel.get(
        "price"
    ) is not None:

        return hotel.get(
            "price"
        )

    return None


# ============================================================
# CREATE HOTEL ROW
# ============================================================

def make_hotel_row(
    hotel,
    search_area
):

    hotel_id = (
        hotel.get(
            "property_token"
        )
        or
        hotel.get(
            "hotel_id"
        )
    )

    hotel_name = hotel.get(
        "name",
        "Unknown Hotel"
    )

    gps = hotel.get(
        "gps_coordinates",
        {}
    )

    latitude = gps.get(
        "latitude"
    )

    longitude = gps.get(
        "longitude"
    )

    return {

        "hotel_name":
            hotel_name,

        "hotel_id":
            str(hotel_id),

        "city":
            CITY,

        "state":
            STATE,

        "location":
            extract_location(
                hotel
            ),

        "latitude":
            latitude,

        "longitude":
            longitude,

        "price_per_night":
            extract_price(
                hotel
            ),

        "hotel_category":
            hotel.get(
                "hotel_class"
            ),

        "customer_rating":
            hotel.get(
                "overall_rating"
            ),

        "review_count":
            hotel.get(
                "reviews"
            ),

        "amenities":
            extract_amenities(
                hotel
            ),

        "review_text":
            "",

        "individual_review_rating":
            None,

        "review_date":
            "",

        "review_source":
            "Google Hotels via SerpApi",

        "search_area":
            search_area,

        "review_id":
            ""
    }


# ============================================================
# FETCH REVIEWS
# ============================================================

def fetch_reviews(
    hotel,
    search_area
):

    hotel_id = (
        hotel.get(
            "property_token"
        )
        or
        hotel.get(
            "hotel_id"
        )
    )

    hotel_name = hotel.get(
        "name",
        "Unknown Hotel"
    )

    if not hotel_id:

        return []

    hotel_id = str(
        hotel_id
    )

    all_reviews = []

    next_page_token = None


    # ========================================================
    # REVIEW PAGES
    # ========================================================

    for page in range(
        1,
        MAX_REVIEW_PAGES + 1
    ):

        params = {

            "engine":
                "google_hotels_reviews",

            "property_token":
                hotel_id,

            "hl":
                "en",

            "sort_by":
                "2",

            "api_key":
                API_KEY
        }


        if next_page_token:

            params[
                "next_page_token"
            ] = next_page_token


        try:

            response = requests.get(
                BASE_URL,
                params=params,
                timeout=60
            )

            response.raise_for_status()

            data = response.json()

        except Exception as e:

            print(
                f"Review request failed: "
                f"{e}"
            )

            break


        if "error" in data:

            print(
                f"Review API error: "
                f"{data['error']}"
            )

            break


        reviews = data.get(
            "reviews",
            []
        )


        if not reviews:

            break


        # ====================================================
        # PROCESS REVIEWS
        # ====================================================

        for index, review in enumerate(
            reviews
        ):

            # ------------------------------------------------
            # REVIEW ID
            # ------------------------------------------------

            review_id = (
                review.get(
                    "review_id"
                )
                or
                review.get(
                    "id"
                )
            )

            if not review_id:

                review_id = (
                    f"{hotel_id}_"
                    f"{page}_"
                    f"{index}"
                )


            # ------------------------------------------------
            # REVIEW RATING
            # ------------------------------------------------

            review_rating = (
                review.get(
                    "rating"
                )
                or
                review.get(
                    "overall_rating"
                )
            )


            # ------------------------------------------------
            # REVIEW TEXT
            # ------------------------------------------------

            review_text = (

                review.get(
                    "snippet"
                )

                or

                review.get(
                    "text"
                )

                or

                review.get(
                    "review_text"
                )

                or
                ""
            )


            # ------------------------------------------------
            # REVIEW DATE
            # ------------------------------------------------

            review_date = (

                review.get(
                    "date"
                )

                or

                review.get(
                    "relative_date"
                )

                or
                ""
            )


            # ------------------------------------------------
            # CREATE REVIEW ROW
            # ------------------------------------------------

            row = {

                "hotel_name":
                    hotel_name,

                "hotel_id":
                    hotel_id,

                "city":
                    CITY,

                "state":
                    STATE,

                "location":
                    extract_location(
                        hotel
                    ),

                "latitude":
                    hotel.get(
                        "gps_coordinates",
                        {}
                    ).get(
                        "latitude"
                    ),

                "longitude":
                    hotel.get(
                        "gps_coordinates",
                        {}
                    ).get(
                        "longitude"
                    ),

                "price_per_night":
                    extract_price(
                        hotel
                    ),

                "hotel_category":
                    hotel.get(
                        "hotel_class"
                    ),

                "customer_rating":
                    hotel.get(
                        "overall_rating"
                    ),

                "review_count":
                    hotel.get(
                        "reviews"
                    ),

                "amenities":
                    extract_amenities(
                        hotel
                    ),

                "review_text":
                    review_text,

                "individual_review_rating":
                    review_rating,

                "review_date":
                    review_date,

                "review_source":
                    "Google Hotels Reviews via SerpApi",

                "search_area":
                    search_area,

                "review_id":
                    review_id
            }

            all_reviews.append(
                row
            )


        # ====================================================
        # NEXT REVIEW PAGE
        # ====================================================

        next_page_token = (
            data.get(
                "serpapi_pagination",
                {}
            )
            .get(
                "next_page_token"
            )
        )


        if not next_page_token:

            break


        time.sleep(1)


    return all_reviews


# ============================================================
# MAIN SCRAPING PROCESS
# ============================================================

new_hotel_ids = set()

new_hotels_collected = 0


print("\n")
print("=" * 70)
print("STARTING JAIPUR HOTEL SCRAPING")
print("=" * 70)

print(
    f"Existing unique hotels: "
    f"{len(existing_hotel_ids)}"
)

print(
    f"New hotels required: "
    f"{TARGET_NEW_HOTELS}"
)

print(
    f"Target after completion: "
    f"{len(existing_hotel_ids) + TARGET_NEW_HOTELS}"
)

print("=" * 70)


# ============================================================
# LOOP THROUGH JAIPUR AREAS
# ============================================================

for search_area in JAIPUR_AREAS:


    # Stop at 100 NEW hotels
    if (
        new_hotels_collected
        >=
        TARGET_NEW_HOTELS
    ):

        break


    print("\n")
    print("=" * 70)

    print(
        f"SEARCHING: {search_area}"
    )

    print(
        f"NEW HOTEL PROGRESS: "
        f"{new_hotels_collected}/"
        f"{TARGET_NEW_HOTELS}"
    )

    print("=" * 70)


    # ========================================================
    # SEARCH HOTELS
    # ========================================================

    try:

        hotels = search_hotels(
            search_area
        )

    except Exception as e:

        print(
            f"Hotel search failed: "
            f"{e}"
        )

        continue


    print(
        f"Hotels returned: "
        f"{len(hotels)}"
    )


    # ========================================================
    # PROCESS EACH HOTEL
    # ========================================================

    for hotel in hotels:


        # Stop at 100
        if (
            new_hotels_collected
            >=
            TARGET_NEW_HOTELS
        ):

            break


        # ====================================================
        # HOTEL ID
        # ====================================================

        hotel_id = (
            hotel.get(
                "property_token"
            )
            or
            hotel.get(
                "hotel_id"
            )
        )

        hotel_name = hotel.get(
            "name",
            "Unknown Hotel"
        )


        if not hotel_id:

            print(
                f"SKIP: {hotel_name} "
                f"- no hotel ID"
            )

            continue


        hotel_id = str(
            hotel_id
        )


        # ====================================================
        # SKIP EXISTING HOTEL
        # ====================================================

        if hotel_id in known_hotel_ids:

            print(
                f"SKIP EXISTING: "
                f"{hotel_name}"
            )

            continue


        # ====================================================
        # SKIP DUPLICATE IN CURRENT RUN
        # ====================================================

        if hotel_id in new_hotel_ids:

            continue


        # ====================================================
        # NEW HOTEL
        # ====================================================

        print("\n" + "-" * 60)

        print(
            f"NEW HOTEL "
            f"{new_hotels_collected + 1}/"
            f"{TARGET_NEW_HOTELS}"
        )

        print(
            f"Hotel: {hotel_name}"
        )

        print(
            f"Hotel ID: {hotel_id}"
        )

        print(
            f"Area: {search_area}"
        )

        print("-" * 60)


        # ====================================================
        # FETCH REVIEWS
        # ====================================================

        try:

            reviews = fetch_reviews(
                hotel,
                search_area
            )

        except Exception as e:

            print(
                f"Review collection failed: "
                f"{e}"
            )

            reviews = []


        # ====================================================
        # ADD REVIEW DATA
        # ====================================================

        if reviews:

            new_df = pd.DataFrame(
                reviews
            )

            df = pd.concat(
                [
                    df,
                    new_df
                ],
                ignore_index=True
            )

            print(
                f"Reviews collected: "
                f"{len(reviews)}"
            )


        # ====================================================
        # NO REVIEWS
        # ====================================================

        else:

            hotel_row = make_hotel_row(
                hotel,
                search_area
            )

            df = pd.concat(
                [
                    df,
                    pd.DataFrame([
                        hotel_row
                    ])
                ],
                ignore_index=True
            )

            print(
                "No reviews found."
            )

            print(
                "Hotel information saved."
            )


        # ====================================================
        # SAVE DATASET IMMEDIATELY
        # ====================================================

        save_dataset()


        # ====================================================
        # UPDATE TRACKING
        # ====================================================

        new_hotel_ids.add(
            hotel_id
        )

        existing_hotel_ids.add(
            hotel_id
        )

        known_hotel_ids.add(
            hotel_id
        )

        new_hotels_collected += 1


        # ====================================================
        # SAVE CHECKPOINT
        # ====================================================

        save_checkpoint(
            hotel_id,
            hotel_name,
            search_area,
            "completed"
        )


        # ====================================================
        # SHOW PROGRESS
        # ====================================================

        print(
            f"SUCCESS: {hotel_name}"
        )

        print(
            f"New hotels collected: "
            f"{new_hotels_collected}/"
            f"{TARGET_NEW_HOTELS}"
        )

        print(
            f"Total unique hotels now: "
            f"{df['hotel_id'].nunique()}"
        )

        print(
            f"Total records now: "
            f"{len(df)}"
        )


        # ====================================================
        # DELAY
        # ====================================================

        time.sleep(2)


# ============================================================
# FINAL SAVE
# ============================================================

save_dataset()


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("JAIPUR SCRAPING COMPLETED")
print("=" * 70)

print(
    f"New hotels collected: "
    f"{new_hotels_collected}"
)

print(
    f"Total unique hotels: "
    f"{df['hotel_id'].nunique()}"
)

print(
    f"Total dataset records: "
    f"{len(df)}"
)

print(
    f"Output file: "
    f"{OUTPUT_FILE}"
)

print(
    f"Checkpoint file: "
    f"{CHECKPOINT_FILE}"
)

print("=" * 70)


# ============================================================
# FINAL HOTEL COUNT
# ============================================================

print("\nFINAL HOTEL COUNT")

hotel_counts = (
    df.groupby(
        "hotel_id"
    )
    .size()
    .reset_index(
        name="review_rows"
    )
)

print(
    f"Unique hotels: "
    f"{len(hotel_counts)}"
)

print(
    f"Total review/data rows: "
    f"{len(df)}"
)


# ============================================================
# REVIEW STATISTICS
# ============================================================

if "review_text" in df.columns:

    review_text_count = (
        df["review_text"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
        .sum()
    )

    print(
        f"Records with review text: "
        f"{review_text_count}"
    )


if "individual_review_rating" in df.columns:

    rating_count = (
        df[
            "individual_review_rating"
        ]
        .notna()
        .sum()
    )

    print(
        f"Records with individual review rating: "
        f"{rating_count}"
    )


if "price_per_night" in df.columns:

    price_count = (
        df[
            "price_per_night"
        ]
        .notna()
        .sum()
    )

    print(
        f"Records with price: "
        f"{price_count}"
    )


if "amenities" in df.columns:

    amenities_count = (
        df["amenities"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
        .sum()
    )

    print(
        f"Records with amenities: "
        f"{amenities_count}"
    )


print("\n")
print("=" * 70)
print("JAIPUR DATASET READY")
print("=" * 70)

Enter your SerpApi API key: 91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6
No existing Jaipur dataset found.
Starting a fresh Jaipur dataset.
Existing unique hotels: 0
New hotels required: 100
Expected final unique hotels: 100
======================================================================
No Jaipur checkpoint found.
Starting fresh.


======================================================================
STARTING JAIPUR HOTEL SCRAPING
======================================================================
Existing unique hotels: 0
New hotels required: 100
Target after completion: 100
======================================================================


======================================================================
SEARCHING: C Scheme Jaipur
NEW HOTEL PROGRESS: 0/100
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 1/100
Hotel: Blue Beds Jaipur
Hotel ID: ChoI-YWyjJWBvaS7ARoNL2cvMTFjNnp3enF0aBAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 30 records | 1 unique hotels
SUCCESS: Blue Beds Jaipur
New hotels collected: 1/100
Total unique hotels now: 1
Total records now: 30

------------------------------------------------------------
NEW HOTEL 2/100
Hotel: Flute Boutique By Hotel 91
Hotel ID: ChkI-cT6nM-51qlsGg0vZy8xMWdtOXpkMmN4EAE
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 60 records | 2 unique hotels
SUCCESS: Flute Boutique By Hotel 91
New hotels collected: 2/100
Total unique hotels now: 2
Total records now: 60

------------------------------------------------------------
NEW HOTEL 3/100
Hotel: Ferozi House, C-Scheme
Hotel ID: ChkIkZ_vg4mylcxaGg0vZy8xMXo0dnEwZm1uEAE
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 13
Dataset saved: 73 records | 3 unique hotels
SUCCESS: Ferozi House, C-Scheme
New hotels collected: 3/100
Total unique hotels now: 3
Total records now: 73

------------------------------------------------------------
NEW HOTEL 4/100
Hotel: Hotel Indo Prime
Hotel ID: ChkIwdnzjerfq-NQGg0vZy8xMWZuNjVmNXp4EAE
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 103 records | 4 unique hotels
SUCCESS: Hotel Indo Prime
New hotels collected: 4/100
Total unique hotels now: 4
Total records now: 103

------------------------------------------------------------
NEW HOTEL 5/100
Hotel: Townhouse by OYO C Scheme Ahinsa Circle
Hotel ID: ChoI56OZz4yG1JWqARoNL2cvMTFnanY3Zm45eRAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 133 records | 5 unique hotels
SUCCESS: Townhouse by OYO C Scheme Ahinsa Circle
New hotels collected: 5/100
Total unique hotels now: 5
Total records now: 133

------------------------------------------------------------
NEW HOTEL 6/100
Hotel: Park Prime
Hotel ID: ChoIxNLvko3S86rcARoNL2cvMTFiNjdteXY5MRAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 163 records | 6 unique hotels
SUCCESS: Park Prime
New hotels collected: 6/100
Total unique hotels now: 6
Total records now: 163

------------------------------------------------------------
NEW HOTEL 7/100
Hotel: Vesta Maurya Palace
Hotel ID: ChgIkarftuaL98K8ARoLL2cvMXRobm01anAQAQ
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 193 records | 7 unique hotels
SUCCESS: Vesta Maurya Palace
New hotels collected: 7/100
Total unique hotels now: 7
Total records now: 193

------------------------------------------------------------
NEW HOTEL 8/100
Hotel: Hotel Shikha Jaipur City Centre
Hotel ID: ChgImeKOsfmo8LnTARoLL2cvMXRnY3dnZm0QAQ
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 223 records | 8 unique hotels
SUCCESS: Hotel Shikha Jaipur City Centre
New hotels collected: 8/100
Total unique hotels now: 8
Total records now: 223

------------------------------------------------------------
NEW HOTEL 9/100
Hotel: Anandmai - Sustainable Living Spaces
Hotel ID: ChoI64P6suT4_eOgARoNL2cvMTF0M2t6cGxqMxAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 253 records | 9 unique hotels
SUCCESS: Anandmai - Sustainable Living Spaces
New hotels collected: 9/100
Total unique hotels now: 9
Total records now: 253

------------------------------------------------------------
NEW HOTEL 10/100
Hotel: Leisure Inn Grand Chanakya
Hotel ID: ChgImu2_y4LHyrxKGgwvZy8xMnFmX2RyMzAQAQ
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 283 records | 10 unique hotels
SUCCESS: Leisure Inn Grand Chanakya
New hotels collected: 10/100
Total unique hotels now: 10
Total records now: 283

------------------------------------------------------------
NEW HOTEL 11/100
Hotel: The Wall Street Beacon Hotel, Jaipur
Hotel ID: ChcInOXc_Mq874U5GgsvZy8xdGRjZHNqMRAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 313 records | 11 unique hotels
SUCCESS: The Wall Street Beacon Hotel, Jaipur
New hotels collected: 11/100
Total unique hotels now: 11
Total records now: 313

------------------------------------------------------------
NEW HOTEL 12/100
Hotel: Diggi Palace – A Heritage Hotel
Hotel ID: ChYI2qaDle7V6PssGgovbS8wajI0ZmMyEAE
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 343 records | 12 unique hotels
SUCCESS: Diggi Palace – A Heritage Hotel
New hotels collected: 12/100
Total unique hotels now: 12
Total records now: 343

------------------------------------------------------------
NEW HOTEL 13/100
Hotel: Hotel Tourist Inn Jaipur City Center
Hotel ID: ChoIj9uomPq1-dXQARoNL2cvMTFoenhsdHdjNhAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 373 records | 13 unique hotels
SUCCESS: Hotel Tourist Inn Jaipur City Center
New hotels collected: 13/100
Total unique hotels now: 13
Total records now: 373

------------------------------------------------------------
NEW HOTEL 14/100
Hotel: Raj Bagh
Hotel ID: ChoI9LL939G26sGrARoNL2cvMTFuNjJsczR0chAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 7
Dataset saved: 380 records | 14 unique hotels
SUCCESS: Raj Bagh
New hotels collected: 14/100
Total unique hotels now: 14
Total records now: 380

------------------------------------------------------------
NEW HOTEL 15/100
Hotel: Avalon - Hotel in C-Scheme Jaipur
Hotel ID: ChoImZ2BmLHPua-1ARoNL2cvMTFnaDZidmZ5bRAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 410 records | 15 unique hotels
SUCCESS: Avalon - Hotel in C-Scheme Jaipur
New hotels collected: 15/100
Total unique hotels now: 15
Total records now: 410

------------------------------------------------------------
NEW HOTEL 16/100
Hotel: goSTOPS Lite Jaipur
Hotel ID: ChkI-4DT5sX2mI5fGg0vZy8xMWJ3enl5cHcyEAE
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 440 records | 16 unique hotels
SUCCESS: goSTOPS Lite Jaipur
New hotels collected: 16/100
Total unique hotels now: 16
Total records now: 440

------------------------------------------------------------
NEW HOTEL 17/100
Hotel: Hotel Evergreen Guest House
Hotel ID: ChcI25zKzqC6_6IbGgsvZy8xdHYyMmtnahAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 470 records | 17 unique hotels
SUCCESS: Hotel Evergreen Guest House
New hotels collected: 17/100
Total unique hotels now: 17
Total records now: 470

------------------------------------------------------------
NEW HOTEL 18/100
Hotel: hotel angel paradise
Hotel ID: ChoI2qGD7Ky3x7KNARoNL2cvMTF2cHI0NHkyMRAB
Area: C Scheme Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 500 records | 18 unique hotels
SUCCESS: hotel angel paradise
New hotels collected: 18/100
Total unique hotels now: 18
Total records now: 500

------------------------------------------------------------
NEW HOTEL 19/100
Hotel: European Style GlassHouse(1BHK) Jaipur
Hotel ID: ChoQhsz2-tu8h7iTARoNL2cvMTFudGhsNTJodxAC
Area: C Scheme Jaipur
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 501 records | 19 unique hotels
SUCCESS: European Style GlassHouse(1BHK) Jaipur
New hotels collected: 19/100
Total unique hotels now: 19
Total records now: 501

/tmp/ipykernel_1058/801334368.py:1332: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 20/100
Hotel: Welcome to Pinterest Inspired Villa in center of the city.
Hotel ID: ChoQh4Wq8_WCho7pARoNL2cvMTF5MWMzZDl5MRAC
Area: C Scheme Jaipur
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 502 records | 20 unique hotels
SUCCESS: Welcome to Pinterest Inspired Villa in center of the city.
New hotels collected: 20/100
Total unique hotels now: 20
Total records now: 502

/tmp/ipykernel_1058/801334368.py:1332: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCHING: MI Road Jaipur
NEW HOTEL PROGRESS: 20/100
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 21/100
Hotel: Fairfield by Marriott Jaipur
Hotel ID: ChkIjo6Ouq_Dv5skGg0vZy8xMXN2cjl4emp5EAE
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 532 records | 21 unique hotels
SUCCESS: Fairfield by Marriott Jaipur
New hotels collected: 21/100
Total unique hotels now: 21
Total records now: 532

------------------------------------------------------------
NEW HOTEL 22/100
Hotel: ITC Rajputana, a Luxury Collection Hotel, Jaipur
Hotel ID: ChcIxvn2z9fmz8coGgsvZy8xdGR2bjQzdBAB
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 562 records | 22 unique hotels
SUCCESS: ITC Rajputana, a Luxury Collection Hotel, Jaipur
New hotels collected: 22/100
Total unique hotels now: 22
Total records now: 562
SKIP EXISTING: Hotel Indo Prime
SKIP EXISTING: Vesta Maurya Palace
SKIP EXISTING: The Wall Street Beacon Hotel, Jaipur

------------------------------------------------------------
NEW HOTEL 23/100
Hotel: Jaipur Hotel New - A heritage hotel
Hotel ID: ChoI5ujAvbqxu9r5ARoNL2cvMTFnMDF2NjZoZxAB
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 592 records | 23 unique hotels
SUCCESS: Jaipur Hotel New - A heritage hotel
New hotels collected: 23/100
Total unique hotels now: 23
Total records now: 592

------------------------------------------------------------
NEW HOTEL 24/100
Hotel: Golden Tulip Essential
Hotel ID: ChkI98nS5p2iyp2wARoML2cvMXB0d2d6ZHJzEAE
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 622 records | 24 unique hotels
SUCCESS: Golden Tulip Essential
New hotels collected: 24/100
Total unique hotels now: 24
Total records now: 622
SKIP EXISTING: Leisure Inn Grand Chanakya

------------------------------------------------------------
NEW HOTEL 25/100
Hotel: Baramasi
Hotel ID: ChoItIKElueiwLeYARoNL2cvMTF0aGY2eHFoNxAB
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 652 records | 25 unique hotels
SUCCESS: Baramasi
New hotels collected: 25/100
Total unique hotels now: 25
Total records now: 652

------------------------------------------------------------
NEW HOTEL 26/100
Hotel: Radisson Hotel Jaipur City Center
Hotel ID: ChkIsLmejqDvr_AgGg0vZy8xMWc4MHRnYm5rEAE
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 682 records | 26 unique hotels
SUCCESS: Radisson Hotel Jaipur City Center
New hotels collected: 26/100
Total unique hotels now: 26
Total records now: 682

------------------------------------------------------------
NEW HOTEL 27/100
Hotel: Keys Lite by Lemon Tree Hotels, Jaipur
Hotel ID: ChoIlLrPgfrLnL-6ARoNL2cvMTF4bWtybmduOBAB
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 712 records | 27 unique hotels
SUCCESS: Keys Lite by Lemon Tree Hotels, Jaipur
New hotels collected: 27/100
Total unique hotels now: 27
Total records now: 712

------------------------------------------------------------
NEW HOTEL 28/100
Hotel: Nirbana Palace - A Heritage Hotel
Hotel ID: ChkIqMmWusWyx7tIGg0vZy8xMWY2MTIzdmQ1EAE
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 26
Dataset saved: 738 records | 28 unique hotels
SUCCESS: Nirbana Palace - A Heritage Hotel
New hotels collected: 28/100
Total unique hotels now: 28
Total records now: 738

------------------------------------------------------------
NEW HOTEL 29/100
Hotel: Hotel Classic Inn Jaipur
Hotel ID: ChgIv-eH75n-16rPARoLL2cvMXRkY2tjY3EQAQ
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 768 records | 29 unique hotels
SUCCESS: Hotel Classic Inn Jaipur
New hotels collected: 29/100
Total unique hotels now: 29
Total records now: 768

------------------------------------------------------------
NEW HOTEL 30/100
Hotel: Click Collection Jaipur
Hotel ID: ChkIpobR8qqZ__0NGg0vZy8xMXA1eHpiZzY3EAE
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 798 records | 30 unique hotels
SUCCESS: Click Collection Jaipur
New hotels collected: 30/100
Total unique hotels now: 30
Total records now: 798

------------------------------------------------------------
NEW HOTEL 31/100
Hotel: Moustache Jaipur
Hotel ID: ChoI18WP1KSB3qeaARoNL2cvMTFiNzJxcTNjXxAB
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 828 records | 31 unique hotels
SUCCESS: Moustache Jaipur
New hotels collected: 31/100
Total unique hotels now: 31
Total records now: 828

------------------------------------------------------------
NEW HOTEL 32/100
Hotel: Anantam Stays Jaipur
Hotel ID: ChkIiMj1-aWy_-w-Gg0vZy8xMW5yMWhfa3gyEAE
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 18
Dataset saved: 846 records | 32 unique hotels
SUCCESS: Anantam Stays Jaipur
New hotels collected: 32/100
Total unique hotels now: 32
Total records now: 846

------------------------------------------------------------
NEW HOTEL 33/100
Hotel: Golden Tulip Jaipur City Center
Hotel ID: ChoI84z6rKnahLP0ARoNL2cvMTFyZDNsemhxORAB
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 876 records | 33 unique hotels
SUCCESS: Golden Tulip Jaipur City Center
New hotels collected: 33/100
Total unique hotels now: 33
Total records now: 876

------------------------------------------------------------
NEW HOTEL 34/100
Hotel: Nirwana Hometel Jaipur
Hotel ID: ChkItt-jkLmq9ITjARoML2cvMXB0X2JoemNxEAE
Area: MI Road Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 906 records | 34 unique hotels
SUCCESS: Nirwana Hometel Jaipur
New hotels collected: 34/100
Total unique hotels now: 34
Total records now: 906

------------------------------------------------------------
NEW HOTEL 35/100
Hotel: Ardra Studio Apartment Compact Stay with Workspace MI Road Jaipur
Hotel ID: ChoQy6yKydbG7v3sARoNL2cvMTF6N19zZ2x2cRAC
Area: MI Road Jaipur
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 907 records | 35 unique hotels
SUCCESS: Ardra Studio Apartment Compact Stay with Workspace MI Road Jaipur
New hotels collected: 35/100
Total unique hotels now: 35
Total records now: 907

/tmp/ipykernel_1058/801334368.py:1332: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

------------------------------------------------------------
NEW HOTEL 36/100
Hotel: Ardra 1BHK Apartment Stylish Tropical Stay MI Road Jaipur
Hotel ID: ChoQ0-7Ugf2W7ryeARoNL2cvMTF6Yl9mZzk1bBAC
Area: MI Road Jaipur
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 908 records | 36 unique hotels
SUCCESS: Ardra 1BHK Apartment Stylish Tropical Stay MI Road Jaipur
New hotels collected: 36/100
Total unique hotels now: 36
Total records now: 908

/tmp/ipykernel_1058/801334368.py:1332: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCHING: Ashok Nagar Jaipur
NEW HOTEL PROGRESS: 36/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Blue Beds Jaipur

------------------------------------------------------------
NEW HOTEL 37/100
Hotel: Hotel Royal Primes
Hotel ID: ChoI8KWF_dLX5ciUARoNL2cvMTF5aGtiMHN3ZBAB
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 938 records | 37 unique hotels
SUCCESS: Hotel Royal Primes
New hotels collected: 37/100
Total unique hotels now: 37
Total records now: 938

------------------------------------------------------------
NEW HOTEL 38/100
Hotel: Hotel Kalyan
Hotel ID: ChgIv_bomqi8iKrBARoLL2cvMXY3NXE5ZjIQAQ
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 968 records | 38 unique hotels
SUCCESS: Hotel Kalyan
New hotels collected: 38/100
Total unique hotels now: 38
Total records now: 968

------------------------------------------------------------
NEW HOTEL 39/100
Hotel: Hotel Silver Stay 04
Hotel ID: ChkIqKfthITwhasNGg0vZy8xMXgxeW5kZGpnEAE
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 998 records | 39 unique hotels
SUCCESS: Hotel Silver Stay 04
New hotels collected: 39/100
Total unique hotels now: 39
Total records now: 998
SKIP EXISTING: Townhouse by OYO C Scheme Ahinsa Circle
SKIP EXISTING: Hotel Shikha Jaipur City Centre

------------------------------------------------------------
NEW HOTEL 40/100
Hotel: PALM RESIDENCES AND SUITES
Hotel ID: ChkI2YmcobOjxvFUGg0vZy8xMXh2cHcwc3M2EAE
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1028 records | 40 unique hotels
SUCCESS: PALM RESIDENCES AND SUITES
New hotels collected: 40/100
Total unique hotels now: 40
Total records now: 1028

------------------------------------------------------------
NEW HOTEL 41/100
Hotel: Hotel Jaisingh Palace
Hotel ID: ChgIyq-mqYaqhf6aARoLL2cvMXRmcHNwNHEQAQ
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1058 records | 41 unique hotels
SUCCESS: Hotel Jaisingh Palace
New hotels collected: 41/100
Total unique hotels now: 41
Total records now: 1058
SKIP EXISTING: Hotel Indo Prime
SKIP EXISTING: Flute Boutique By Hotel 91
SKIP EXISTING: Park Prime
SKIP EXISTING: hotel angel paradise

------------------------------------------------------------
NEW HOTEL 42/100
Hotel: FabHotel Connect
Hotel ID: ChkIraC476iRksYXGg0vZy8xMXhzcndxdDE5EAE
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1088 records | 42 unique hotels
SUCCESS: FabHotel Connect
New hotels collected: 42/100
Total unique hotels now: 42
Total records now: 1088

------------------------------------------------------------
NEW HOTEL 43/100
Hotel: Lords Plaza Jaipur
Hotel ID: ChkI6Jjn29S5wI7wARoML2cvMWhtMXcxcTM5EAE
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 27
Dataset saved: 1115 records | 43 unique hotels
SUCCESS: Lords Plaza Jaipur
New hotels collected: 43/100
Total unique hotels now: 43
Total records now: 1115

------------------------------------------------------------
NEW HOTEL 44/100
Hotel: goSTOPS Jaipur, Civil Lines
Hotel ID: ChkI5-KYj_uthKElGg0vZy8xMXpoOWhzdGd4EAE
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1145 records | 44 unique hotels
SUCCESS: goSTOPS Jaipur, Civil Lines
New hotels collected: 44/100
Total unique hotels now: 44
Total records now: 1145

------------------------------------------------------------
NEW HOTEL 45/100
Hotel: Chitra Katha - A Story Per Stay
Hotel ID: ChkIu4XxnqWzzcyIARoML2cvMTF5OGRodzMzEAE
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1175 records | 45 unique hotels
SUCCESS: Chitra Katha - A Story Per Stay
New hotels collected: 45/100
Total unique hotels now: 45
Total records now: 1175

------------------------------------------------------------
NEW HOTEL 46/100
Hotel: Shaan hotel
Hotel ID: ChoIv67JkdvXzMfGARoNL2cvMTFmZmh3MTg1NBAB
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 24
Dataset saved: 1199 records | 46 unique hotels
SUCCESS: Shaan hotel
New hotels collected: 46/100
Total unique hotels now: 46
Total records now: 1199
SKIP EXISTING: Hotel Tourist Inn Jaipur City Center

------------------------------------------------------------
NEW HOTEL 47/100
Hotel: Mojo house jaipur
Hotel ID: ChoQnZWm3s2Oy5DeARoNL2cvMTF6NmI0M242aBAC
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Reviews collected: 3
Dataset saved: 1202 records | 47 unique hotels
SUCCESS: Mojo house jaipur
New hotels collected: 47/100
Total unique hotels now: 47
Total records now: 1202

------------------------------------------------------------
NEW HOTEL 48/100
Hotel: MeeRa'Z house(1BHK) in Jaipur
Hotel ID: ChgQk9WTgPPihlUaDS9nLzExemQ3Mjg0dHIQAg
Area: Ashok Nagar Jaipur
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 1203 records | 48 unique hotels
SUCCESS: MeeRa'Z house(1BHK) in Jaipur
New hotels collected: 48/100
Total unique hotels now: 48
Total records now: 1203

/tmp/ipykernel_1058/801334368.py:1332: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCHING: Panch Batti Jaipur
NEW HOTEL PROGRESS: 48/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Shaan hotel
SKIP EXISTING: Hotel Jaisingh Palace
SKIP EXISTING: Hotel Silver Stay 04
SKIP EXISTING: Hotel Royal Primes

------------------------------------------------------------
NEW HOTEL 49/100
Hotel: Hotel Rangoli
Hotel ID: ChgInqX4nd6KvJDIARoLL2cvMXRkbjJoZjIQAQ
Area: Panch Batti Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1233 records | 49 unique hotels
SUCCESS: Hotel Rangoli
New hotels collected: 49/100
Total unique hotels now: 49
Total records now: 1233

------------------------------------------------------------
NEW HOTEL 50/100
Hotel: Jaipur The Lodge B&B
Hotel ID: ChoIk4iO-J_Pu9rbARoNL2cvMTFjMnEwNXMybRAB
Area: Panch Batti Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1263 records | 50 unique hotels
SUCCESS: Jaipur The Lodge B&B
New hotels collected: 50/100
Total unique hotels now: 50
Total records now: 1263

------------------------------------------------------------
NEW HOTEL 51/100
Hotel: Hotel Purohit
Hotel ID: ChgI76LT_4jihLLqARoLL2cvMXRkY2RzZ3AQAQ
Area: Panch Batti Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1293 records | 51 unique hotels
SUCCESS: Hotel Purohit
New hotels collected: 51/100
Total unique hotels now: 51
Total records now: 1293
SKIP EXISTING: Hotel Tourist Inn Jaipur City Center

------------------------------------------------------------
NEW HOTEL 52/100
Hotel: HOTEL GRANDE RESIDENCY
Hotel ID: ChkIg_Gv1Mrh1bExGg0vZy8xMWI2Z2dyeGRyEAE
Area: Panch Batti Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1323 records | 52 unique hotels
SUCCESS: HOTEL GRANDE RESIDENCY
New hotels collected: 52/100
Total unique hotels now: 52
Total records now: 1323
SKIP EXISTING: Vesta Maurya Palace

------------------------------------------------------------
NEW HOTEL 53/100
Hotel: Hotel Kanchandeep
Hotel ID: ChcIxKP4k8PLsvpjGgsvZy8xdjVfN3YyMxAB
Area: Panch Batti Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1353 records | 53 unique hotels
SUCCESS: Hotel Kanchandeep
New hotels collected: 53/100
Total unique hotels now: 53
Total records now: 1353

------------------------------------------------------------
NEW HOTEL 54/100
Hotel: Hotel O Shan
Hotel ID: ChoIgZC2z_zEnKS0ARoNL2cvMTF0azUxbGY2NhAB
Area: Panch Batti Jaipur
------------------------------------------------------------
Reviews collected: 22
Dataset saved: 1375 records | 54 unique hotels
SUCCESS: Hotel O Shan
New hotels collected: 54/100
Total unique hotels now: 54
Total records now: 1375
SKIP EXISTING: Hotel Indo Prime
SKIP EXISTING: Townhouse by OYO C Scheme Ahinsa Circle

------------------------------------------------------------
NEW HOTEL 55/100
Hotel: THE PINK NEST
Hotel ID: ChoI766AiMe13cWxARoNL2cvMTF3ODF5a3p2cBAB
Area: Panch Batti Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1405 records | 55 unique hotels
SUCCESS: THE PINK NEST
New hotels collected: 55/100
Total unique hotels now: 55
Total records now: 1405
SKIP EXISTING: PALM RESIDENCES AND SUITES
SKIP EXISTING: Hotel Evergreen Guest House

------------------------------------------------------------
NEW HOTEL 56/100
Hotel: Jungle by sturmfrei Jaipur | Smart Stays
Hotel ID: ChoIgtz66Jfu-vn_ARoNL2cvMTF3bmpuOW5fOBAB
Area: Panch Batti Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1435 records | 56 unique hotels
SUCCESS: Jungle by sturmfrei Jaipur | Smart Stays
New hotels collected: 56/100
Total unique hotels now: 56
Total records now: 1435
SKIP EXISTING: Ardra Studio Apartment Compact Stay with Workspace MI Road Jaipur

------------------------------------------------------------
NEW HOTEL 57/100
Hotel: Shanti Villas - Luxury Home Stay Apartment - Three-Bedroom Apartment
Hotel ID: ChkQ46XIoMrE079WGg0vZy8xMW1reTI3a3p0EAI
Area: Panch Batti Jaipur
------------------------------------------------------------
Reviews collected: 8
Dataset saved: 1443 records | 57 unique hotels
SUCCESS: Shanti Villas - Luxury Home Stay Apartment - Three-Bedroom Apartment
New hotels collected: 57/100
Total unique hotels now: 57
Total records now: 1443


======================================================================
SEARCHING: Statue Circle Jaipur
NEW HOTEL PROGRESS: 57/100
======================================================================
Hotels returned: 20
SKIP EXISTING: Hotel Kalyan
SKIP EXISTING: Blue Beds Jaipur

------------------------------------------------------------
NEW HOTEL 58/100
Hotel: Hotel Ratangarh Palace
Hotel ID: ChoIra2Oj8m5mrPkARoNL2cvMTFoX2NwODdtMBAB
Area: Statue Circle Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1473 records | 58 unique hotels
SUCCESS: Hotel Ratangarh Palace
New hotels collected: 58/100
Total unique hotels now: 58
Total records now: 1473
SKIP EXISTING: Park Prime
SKIP EXISTING: Flute Boutique By Hotel 91

------------------------------------------------------------
NEW HOTEL 59/100
Hotel: Hotel Myriad Inn
Hotel ID: ChkI4ZOH--yiv6UGGg0vZy8xMWgxa25xZ2Z4EAE
Area: Statue Circle Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1503 records | 59 unique hotels
SUCCESS: Hotel Myriad Inn
New hotels collected: 59/100
Total unique hotels now: 59
Total records now: 1503
SKIP EXISTING: Hotel Indo Prime
SKIP EXISTING: Lords Plaza Jaipur
SKIP EXISTING: Townhouse by OYO C Scheme Ahinsa Circle
SKIP EXISTING: The Wall Street Beacon Hotel, Jaipur
SKIP EXISTING: Vesta Maurya Palace

------------------------------------------------------------
NEW HOTEL 60/100
Hotel: Hotel Aashish
Hotel ID: ChYIqoG2387axEgaCy9nLzF2M2dxOXBoEAE
Area: Statue Circle Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1533 records | 60 unique hotels
SUCCESS: Hotel Aashish
New hotels collected: 60/100
Total unique hotels now: 60
Total records now: 1533

------------------------------------------------------------
NEW HOTEL 61/100
Hotel: Hotel Imperial
Hotel ID: ChoIlYOruICmmszwARoNL2cvMTFnNnh3OWI1XxAB
Area: Statue Circle Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1563 records | 61 unique hotels
SUCCESS: Hotel Imperial
New hotels collected: 61/100
Total unique hotels now: 61
Total records now: 1563
SKIP EXISTING: Chitra Katha - A Story Per Stay

------------------------------------------------------------
NEW HOTEL 62/100
Hotel: Hotel Om Tower
Hotel ID: ChgIkO-sjaXmp57jARoLL2cvMXRfaHhkMmQQAQ
Area: Statue Circle Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1593 records | 62 unique hotels
SUCCESS: Hotel Om Tower
New hotels collected: 62/100
Total unique hotels now: 62
Total records now: 1593
SKIP EXISTING: Hotel Shikha Jaipur City Centre
SKIP EXISTING: Hotel Tourist Inn Jaipur City Center
SKIP EXISTING: Hotel Evergreen Guest House
SKIP EXISTING: MeeRa'Z house(1BHK) in Jaipur

------------------------------------------------------------
NEW HOTEL 63/100
Hotel: Studio 808 luxury 1BR with skyline view +pool
Hotel ID: ChgQ_LKLqZGhmhIaDS9nLzExbXNfbjFzNnQQAg
Area: Statue Circle Jaipur
------------------------------------------------------------
Review API error: Google Hotels hasn't returned any results for this query.
No reviews found.
Hotel information saved.
Dataset saved: 1594 records | 63 unique hotels
SUCCESS: Studio 808 luxury 1BR with skyline view +pool
New hotels collected: 63/100
Total unique hotels now: 63
Total records now: 1594

/tmp/ipykernel_1058/801334368.py:1332: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

======================================================================
SEARCHING: Civil Lines Jaipur
NEW HOTEL PROGRESS: 63/100
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 64/100
Hotel: Hari Mahal Palace by Pachar Group
Hotel ID: ChcI0emEysKxmIN4GgsvZy8xdGg1NWQ2ZxAB
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1624 records | 64 unique hotels
SUCCESS: Hari Mahal Palace by Pachar Group
New hotels collected: 64/100
Total unique hotels now: 64
Total records now: 1624

------------------------------------------------------------
NEW HOTEL 65/100
Hotel: Hotel Shahar Palace
Hotel ID: ChcI8433pPjqpeI-GgsvZy8xdGYwMHdweBAB
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1654 records | 65 unique hotels
SUCCESS: Hotel Shahar Palace
New hotels collected: 65/100
Total unique hotels now: 65
Total records now: 1654
SKIP EXISTING: goSTOPS Jaipur, Civil Lines

------------------------------------------------------------
NEW HOTEL 66/100
Hotel: Ginger Jaipur
Hotel ID: ChkIjPCyxpTs7PP2ARoML2cvMXE2Mm02X3Z4EAE
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1684 records | 66 unique hotels
SUCCESS: Ginger Jaipur
New hotels collected: 66/100
Total unique hotels now: 66
Total records now: 1684

------------------------------------------------------------
NEW HOTEL 67/100
Hotel: The Pink Villa Civil Lines
Hotel ID: ChoI4L2nk9CyjsGgARoNL2cvMTFuaHl5ajNnZhAB
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 9
Dataset saved: 1693 records | 67 unique hotels
SUCCESS: The Pink Villa Civil Lines
New hotels collected: 67/100
Total unique hotels now: 67
Total records now: 1693

------------------------------------------------------------
NEW HOTEL 68/100
Hotel: Hotel Moon Light Palace Jaipur
Hotel ID: ChoIi6vY1vzH8veQARoNL2cvMTFjbF9sOGQwYxAB
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1723 records | 68 unique hotels
SUCCESS: Hotel Moon Light Palace Jaipur
New hotels collected: 68/100
Total unique hotels now: 68
Total records now: 1723

------------------------------------------------------------
NEW HOTEL 69/100
Hotel: The Social Stays Jaipur
Hotel ID: ChkIm9Xho4DsktVyGg0vZy8xMXR4bmRqMjEwEAE
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1753 records | 69 unique hotels
SUCCESS: The Social Stays Jaipur
New hotels collected: 69/100
Total unique hotels now: 69
Total records now: 1753

------------------------------------------------------------
NEW HOTEL 70/100
Hotel: The Harmony Circle - Jaipur
Hotel ID: ChkItPGQlKKD85lFGg0vZy8xMXhsNDA5ZmRoEAE
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1783 records | 70 unique hotels
SUCCESS: The Harmony Circle - Jaipur
New hotels collected: 70/100
Total unique hotels now: 70
Total records now: 1783

------------------------------------------------------------
NEW HOTEL 71/100
Hotel: ibis Jaipur City Centre
Hotel ID: ChgI1un0382GlrJWGgwvZy8xaGh3cGwxZ2gQAQ
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1813 records | 71 unique hotels
SUCCESS: ibis Jaipur City Centre
New hotels collected: 71/100
Total unique hotels now: 71
Total records now: 1813

------------------------------------------------------------
NEW HOTEL 72/100
Hotel: Ved A Boutique Stay
Hotel ID: ChkIpoGMlMrJgfpSGg0vZy8xMXk2N25fdmIyEAE
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1843 records | 72 unique hotels
SUCCESS: Ved A Boutique Stay
New hotels collected: 72/100
Total unique hotels now: 72
Total records now: 1843

------------------------------------------------------------
NEW HOTEL 73/100
Hotel: Hotel Jaipur Homestay Hawa Sadak
Hotel ID: ChkIgqDShPPn9u8eGg0vZy8xMWxndDQwd3RzEAE
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1873 records | 73 unique hotels
SUCCESS: Hotel Jaipur Homestay Hawa Sadak
New hotels collected: 73/100
Total unique hotels now: 73
Total records now: 1873

------------------------------------------------------------
NEW HOTEL 74/100
Hotel: The 66 Residency
Hotel ID: ChgIrqqHyraF5cIMGgwvZy8xaGhoc2dtbHMQAQ
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1903 records | 74 unique hotels
SUCCESS: The 66 Residency
New hotels collected: 74/100
Total unique hotels now: 74
Total records now: 1903

------------------------------------------------------------
NEW HOTEL 75/100
Hotel: Namli Haus - A Boutique Luxury Stay Jaipur
Hotel ID: ChkIiLz4u-fspdEfGg0vZy8xMXg3eTJ2MV95EAE
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1933 records | 75 unique hotels
SUCCESS: Namli Haus - A Boutique Luxury Stay Jaipur
New hotels collected: 75/100
Total unique hotels now: 75
Total records now: 1933

------------------------------------------------------------
NEW HOTEL 76/100
Hotel: PALM 34 "A Luxury Stay" Homestay, Jaipur
Hotel ID: ChoIobTCto7R4f7DARoNL2cvMTFjMHZ4d3JucRAB
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1963 records | 76 unique hotels
SUCCESS: PALM 34 "A Luxury Stay" Homestay, Jaipur
New hotels collected: 76/100
Total unique hotels now: 76
Total records now: 1963

------------------------------------------------------------
NEW HOTEL 77/100
Hotel: Pachamama
Hotel ID: ChoI8viNqbPIrJrjARoNL2cvMTFuczBrcjF4cBAB
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 1993 records | 77 unique hotels
SUCCESS: Pachamama
New hotels collected: 77/100
Total unique hotels now: 77
Total records now: 1993

------------------------------------------------------------
NEW HOTEL 78/100
Hotel: Hotel kuhu place
Hotel ID: ChoI3__16LuH7LaWARoNL2cvMTFwYjc2eDNndBAB
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2023 records | 78 unique hotels
SUCCESS: Hotel kuhu place
New hotels collected: 78/100
Total unique hotels now: 78
Total records now: 2023

------------------------------------------------------------
NEW HOTEL 79/100
Hotel: Ferozi House
Hotel ID: ChkIoNP-wKyf2oUQGg0vZy8xMXY5bXFyenJfEAE
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2053 records | 79 unique hotels
SUCCESS: Ferozi House
New hotels collected: 79/100
Total unique hotels now: 79
Total records now: 2053

------------------------------------------------------------
NEW HOTEL 80/100
Hotel: 28 Kothi
Hotel ID: ChkI76mSgfXgsa1EGg0vZy8xMWJfMXIyY3Q3EAE
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2083 records | 80 unique hotels
SUCCESS: 28 Kothi
New hotels collected: 80/100
Total unique hotels now: 80
Total records now: 2083

------------------------------------------------------------
NEW HOTEL 81/100
Hotel: Teal Elegance 1BHK Suite, Civil Lines
Hotel ID: ChoQtcrR2drCtMD8ARoNL2cvMTF6YmQyd3AxdxAC
Area: Civil Lines Jaipur
------------------------------------------------------------
Reviews collected: 1
Dataset saved: 2084 records | 81 unique hotels
SUCCESS: Teal Elegance 1BHK Suite, Civil Lines
New hotels collected: 81/100
Total unique hotels now: 81
Total records now: 2084
SKIP EXISTING: Mojo house jaipur


======================================================================
SEARCHING: Bais Godam Jaipur
NEW HOTEL PROGRESS: 81/100
======================================================================
Hotels returned: 20

------------------------------------------------------------
NEW HOTEL 82/100
Hotel: RANI MAHAL
Hotel ID: ChgI9NSHm6yg99TEARoLL2cvMXRnOGg0MGwQAQ
Area: Bais Godam Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2114 records | 82 unique hotels
SUCCESS: RANI MAHAL
New hotels collected: 82/100
Total unique hotels now: 82
Total records now: 2114
SKIP EXISTING: Ginger Jaipur
SKIP EXISTING: Blue Beds Jaipur

------------------------------------------------------------
NEW HOTEL 83/100
Hotel: Hotel Grand Sky
Hotel ID: ChkIpuOzv-yG0OxjGg0vZy8xMXZ4anNzNmdkEAE
Area: Bais Godam Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2144 records | 83 unique hotels
SUCCESS: Hotel Grand Sky
New hotels collected: 83/100
Total unique hotels now: 83
Total records now: 2144
SKIP EXISTING: goSTOPS Jaipur, Civil Lines

------------------------------------------------------------
NEW HOTEL 84/100
Hotel: Sunday Hotel Jaipur
Hotel ID: ChoI_qqe74ei5Nb7ARoNL2cvMTFmcndiY2Z2bBAB
Area: Bais Godam Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2174 records | 84 unique hotels
SUCCESS: Sunday Hotel Jaipur
New hotels collected: 84/100
Total unique hotels now: 84
Total records now: 2174

------------------------------------------------------------
NEW HOTEL 85/100
Hotel: Divine Heritage Hotel
Hotel ID: ChkIraPO1oX32IVNGg0vZy8xMW5iOGZxMjBzEAE
Area: Bais Godam Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2204 records | 85 unique hotels
SUCCESS: Divine Heritage Hotel
New hotels collected: 85/100
Total unique hotels now: 85
Total records now: 2204
SKIP EXISTING: The Social Stays Jaipur

------------------------------------------------------------
NEW HOTEL 86/100
Hotel: Hilton Jaipur
Hotel ID: ChgI-byz492umMRsGgwvZy8xcTZjbHIzNTcQAQ
Area: Bais Godam Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2234 records | 86 unique hotels
SUCCESS: Hilton Jaipur
New hotels collected: 86/100
Total unique hotels now: 86
Total records now: 2234
SKIP EXISTING: The Harmony Circle - Jaipur

------------------------------------------------------------
NEW HOTEL 87/100
Hotel: HOTEL D7
Hotel ID: ChkI3On08KjJ6_gaGg0vZy8xMXhya3p2OWczEAE
Area: Bais Godam Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2264 records | 87 unique hotels
SUCCESS: HOTEL D7
New hotels collected: 87/100
Total unique hotels now: 87
Total records now: 2264

------------------------------------------------------------
NEW HOTEL 88/100
Hotel: Hotel Las Vegas
Hotel ID: ChcIkP6vjqLf5KkuGgsvZy8xdGRrcTVfcBAB
Area: Bais Godam Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2294 records | 88 unique hotels
SUCCESS: Hotel Las Vegas
New hotels collected: 88/100
Total unique hotels now: 88
Total records now: 2294
SKIP EXISTING: Hotel Jaipur Homestay Hawa Sadak

------------------------------------------------------------
NEW HOTEL 89/100
Hotel: Jobner Haus
Hotel ID: ChoI0sv7mcui3LnkARoNL2cvMTF5c3E5bTMyZBAB
Area: Bais Godam Jaipur
------------------------------------------------------------
Reviews collected: 30
Dataset saved: 2324 records | 89 unique hotels
SUCCESS: Jobner Haus
New hotels collected: 89/100
Total unique hotels now: 89
Total records now: 2324
SKIP EXISTING: Namli Haus - A Boutique Luxury Stay Jaipur
SKIP EXISTING: ibis Jaipur City Centre

------------------------------------------------------------
NEW HOTEL 90/100
Hotel: Winter Garden
Hotel ID: ChkIsPHro-WgnYR3Gg0vZy8xMWh6bXFsX3RqEAE
Area: Bais Godam Jaipur
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkIsPHro-WgnYR3Gg0vZy8xMWh6bXFsX3RqEAE&hl=en&sort_by=2&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6&next_page_token=Ci8IARInCgoAP72GqzH9pP__EhAgpMyneMVrahNipqkAAAAAGgf_AmqzH9pPGAAiAA%3A10
Reviews collected: 10
Dataset saved: 2334 records | 90 unique hotels
SUCCESS: Winter Garden
New hotels collected: 90/100
Total unique hotels now: 90
Total records now: 2334
SKIP EXISTING: Hotel Shikha Jaipur City Centre

------------------------------------------------------------
NEW HOTEL 91/100
Hotel: Jaipur 1727 Homestay
Hotel ID: ChoQtvmvtbCq-4q1ARoNL2cvMTFuYnp6a3A5axAC
Area: Bais Godam Jaipur
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChoQtvmvtbCq-4q1ARoNL2cvMTFuYnp6a3A5axAC&hl=en&sort_by=2&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6
No reviews found.
Hotel information saved.
Dataset saved: 2335 records | 91 unique hotels
SUCCESS: Jaipur 1727 Homestay
New hotels collected: 91/100
Total unique hotels now: 91
Total records now: 2335

------------------------------------------------------------
NEW HOTEL 92/100
Hotel: The Collectors Loft-A Luxury Private Suit Near Jaipur City Center - Two-Bedroom Apartment
Hotel ID: ChkQmYHA8Nfc_No_Gg0vZy8xMXpjMGR5NHM1EAI
Area: Bais Godam Jaipur
------------------------------------------------------------
Review request failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels_reviews&property_token=ChkQmYHA8Nfc_No_Gg0vZy8xMXpjMGR5NHM1EAI&hl=en&sort_by=2&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6
No reviews found.
Hotel information saved.
Dataset saved: 2336 records | 92 unique hotels
SUCCESS: The Collectors Loft-A Luxury Private Suit Near Jaipur City Center - Two-Bedroom Apartment
New hotels collected: 92/100
Total unique hotels now: 92
Total records now: 2336


======================================================================
SEARCHING: 22 Godam Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+22+Godam+Jaipur%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Sodala Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Sodala+Jaipur%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Hawa Sadak Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Hawa+Sadak+Jaipur%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Bani Park Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Bani+Park+Jaipur%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Jaipur Railway Station
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Jaipur+Railway+Station%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Gopalbari Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Gopalbari+Jaipur%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Sindhi Camp Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Sindhi+Camp+Jaipur%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Station Road Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Station+Road+Jaipur%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Khatipura Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Khatipura+Jaipur%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Hasanpura Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================
Hotel search failed: 429 Client Error: Too Many Requests for url: https://serpapi.com/search.json?engine=google_hotels&q=Hotels+in+Hasanpura+Jaipur%2C+Jaipur%2C+Rajasthan&check_in_date=2026-10-15&check_out_date=2026-10-16&adults=2&currency=INR&gl=in&hl=en&api_key=91e58b9815a6b81599b5a81053c867df1c631a144f8439d494ea7b46261a71c6


======================================================================
SEARCHING: Shastri Nagar Jaipur
NEW HOTEL PROGRESS: 92/100
======================================================================

In [ ]:
from google.colab import files

files.download("jaipur_hotel_dataset.csv")

In [ ]:
import requests
import pandas as pd
import getpass
import time
import os

# ============================================================
# 1. CONFIGURATION
# ============================================================

API_KEY = getpass.getpass("Enter your SerpApi API key: ")

CITY = "Hyderabad"
STATE = "Telangana"
COUNTRY_CODE = "in"

CHECK_IN = "2026-10-15"
CHECK_OUT = "2026-10-16"

# IMPORTANT:
# We want ADDITIONAL 100 hotels, not total 100 hotels.
ADDITIONAL_HOTELS = 100

MAX_REVIEW_PAGES = 3

OUTPUT_FILE = "hyderabad_hotel_dataset.csv"

BASE_URL = "https://serpapi.com/search.json"


# ============================================================
# 2. SEARCH AREAS
# ============================================================

AREAS = [
    "Central Hyderabad",
    "HITEC City",
    "Gachibowli",
    "Madhapur",
    "Banjara Hills",
    "Jubilee Hills",
    "Secunderabad",
    "Begumpet",
    "Kondapur",
    "Shamshabad",
    "Abids",
    "Ameerpet",
    "Kukatpally",
    "Miyapur",
    "LB Nagar",
    "Manikonda",
    "Nampally",
    "Mehdipatnam",
    "Uppal",
    "Financial District",
    "Raidurg",
    "Koti",
    "Somajiguda",
    "Tolichowki",
    "Dilsukhnagar",
    "Kachiguda",
    "Charminar",
    "Lakdikapul",
    "Himayatnagar",
    "Attapur",
    "Bachupally",
    "Kompally",
    "Malkajgiri",
    "KPHB",
    "Gachibowli Financial District",
    "Kokapet",
    "Nanakramguda",
    "Chandanagar",
    "Sainikpuri",
    "Tarnaka",
    "Habsiguda",
    "Masab Tank",
    "Rajendra Nagar",
    "Shamshabad Airport",
    "Patancheru",
    "Boduppal",
    "Nagole",
    "ECIL",
    "Kondapur Botanical Garden"
]


# ============================================================
# 3. LOAD EXISTING CSV
# ============================================================

if os.path.exists(OUTPUT_FILE):

    existing_df = pd.read_csv(OUTPUT_FILE)

    print("\nExisting CSV found.")
    print("Existing rows:", len(existing_df))

    if "hotel_id" in existing_df.columns:
        existing_hotel_ids = set(
            existing_df["hotel_id"]
            .dropna()
            .astype(str)
            .str.strip()
        )
    else:
        existing_hotel_ids = set()

else:

    print("\nNo existing CSV found.")
    existing_df = pd.DataFrame()
    existing_hotel_ids = set()


print("Existing unique hotels:", len(existing_hotel_ids))


# ============================================================
# 4. HELPER FUNCTION
# ============================================================

def safe_request(params):

    params = params.copy()
    params["api_key"] = API_KEY

    try:

        response = requests.get(
            BASE_URL,
            params=params,
            timeout=60
        )

        if response.status_code != 200:

            print("API error:", response.status_code)
            print(response.text[:300])

            return {}

        data = response.json()

        if "error" in data:

            print("API error:", data["error"])

            return {}

        return data

    except requests.RequestException as e:

        print("Request failed:", e)

        return {}


# ============================================================
# 5. EXTRACT PRICE
# ============================================================

def extract_price(hotel):

    rate = hotel.get("rate_per_night", {})

    if isinstance(rate, dict):

        return (
            rate.get("extracted_lowest")
            or rate.get("extracted_before_taxes_fees")
            or rate.get("lowest")
            or rate.get("before_taxes_fees")
        )

    return rate if isinstance(rate, (int, float)) else None


# ============================================================
# 6. EXTRACT AMENITIES
# ============================================================

def extract_amenities(hotel):

    amenities = hotel.get("amenities", [])

    if isinstance(amenities, list):

        names = []

        for item in amenities:

            if isinstance(item, dict):

                name = (
                    item.get("name")
                    or item.get("title")
                )

                if name:
                    names.append(str(name))

            else:

                names.append(str(item))

        return " | ".join(names)

    return str(amenities) if amenities else None


# ============================================================
# 7. EXTRACT LOCATION
# ============================================================

def extract_location(hotel):

    address = hotel.get("address")

    if address:
        return address

    gps = hotel.get("gps_coordinates", {})

    if isinstance(gps, dict):

        lat = gps.get("latitude")
        lon = gps.get("longitude")

        if lat is not None and lon is not None:

            return f"Latitude: {lat}, Longitude: {lon}"

    return None


# ============================================================
# 8. EXTRACT REVIEW TEXT
# ============================================================

def extract_review_text(review):

    for key in ("snippet", "text"):

        value = review.get(key)

        if isinstance(value, str) and value.strip():

            return value.strip()

    return None


# ============================================================
# 9. EXTRACT REVIEW RATING
# ============================================================

def extract_review_rating(review):

    rating = review.get("rating")

    if isinstance(rating, dict):

        return (
            rating.get("value")
            or rating.get("rating")
        )

    return rating


# ============================================================
# 10. CREATE HOTEL ROW
# ============================================================

def make_hotel_row(hotel, area):

    return {

        "hotel_name": hotel.get("name"),

        "hotel_id": hotel.get("property_token"),

        "city": CITY,

        "location": extract_location(hotel),

        "price_per_night": extract_price(hotel),

        "hotel_category": hotel.get("hotel_class"),

        "customer_rating": hotel.get("overall_rating"),

        "review_count": hotel.get("reviews"),

        "amenities": extract_amenities(hotel),

        "search_area": area
    }


# ============================================================
# 11. FIND 100 NEW HOTELS
# ============================================================

new_hotels_by_id = {}

print("\n============================================================")
print("SEARCHING FOR ADDITIONAL HOTELS")
print("============================================================")

for area in AREAS:

    if len(new_hotels_by_id) >= ADDITIONAL_HOTELS:
        break

    print(
        f"\nSearching: Hotels in {area}, {CITY}"
    )

    next_page_token = None

    while len(new_hotels_by_id) < ADDITIONAL_HOTELS:

        params = {

            "engine": "google_hotels",

            "q": f"Hotels in {area}, {CITY}",

            "gl": COUNTRY_CODE,

            "hl": "en",

            "currency": "INR",

            "check_in_date": CHECK_IN,

            "check_out_date": CHECK_OUT,

            "adults": 2
        }

        if next_page_token:

            params["next_page_token"] = next_page_token

        data = safe_request(params)

        if not data:
            break

        properties = data.get("properties", [])

        if not properties:
            break

        for hotel in properties:

            hotel_id = hotel.get("property_token")

            if not hotel_id:
                continue

            # ------------------------------------------------
            # IMPORTANT:
            # SKIP HOTELS ALREADY PRESENT IN CSV
            # ------------------------------------------------

            if hotel_id in existing_hotel_ids:
                continue

            # ------------------------------------------------
            # SKIP DUPLICATES FOUND DURING THIS NEW SCRAPE
            # ------------------------------------------------

            if hotel_id in new_hotels_by_id:
                continue

            new_hotels_by_id[hotel_id] = {

                **make_hotel_row(
                    hotel,
                    area
                ),

                "_raw_hotel": hotel
            }

            print(
                f"NEW HOTEL {len(new_hotels_by_id)}/"
                f"{ADDITIONAL_HOTELS}: "
                f"{hotel.get('name')}"
            )

            if len(new_hotels_by_id) >= ADDITIONAL_HOTELS:
                break

        # ----------------------------------------------------
        # PAGINATION
        # ----------------------------------------------------

        next_page_token = (
            data.get(
                "serpapi_pagination",
                {}
            ).get("next_page_token")
        )

        if not next_page_token:
            break

        time.sleep(1)

    print(
        "New unique hotels collected so far:",
        len(new_hotels_by_id)
    )


print("\n============================================================")
print("HOTEL SEARCH COMPLETE")
print("============================================================")

print(
    "Existing unique hotels:",
    len(existing_hotel_ids)
)

print(
    "Additional unique hotels found:",
    len(new_hotels_by_id)
)

print(
    "Expected total unique hotels:",
    len(existing_hotel_ids) +
    len(new_hotels_by_id)
)


# ============================================================
# 12. FETCH REVIEWS FOR NEW HOTELS
# ============================================================

all_new_rows = []

skipped_reviews = 0

hotel_items = list(
    new_hotels_by_id.values()
)


print("\n============================================================")
print("FETCHING REVIEWS FOR NEW HOTELS")
print("============================================================")


for hotel_num, hotel_data in enumerate(
    hotel_items,
    start=1
):

    hotel = hotel_data["_raw_hotel"]

    hotel_id = hotel.get("property_token")

    print(
        f"\n[{hotel_num}/{len(hotel_items)}] "
        f"{hotel.get('name')}"
    )

    hotel_details = {

        key: value

        for key, value in hotel_data.items()

        if key != "_raw_hotel"
    }

    next_review_token = None

    review_pages = 0

    valid_reviews = 0

    while review_pages < MAX_REVIEW_PAGES:

        params = {

            "engine":
                "google_hotels_reviews",

            "property_token":
                hotel_id,

            "hl":
                "en",

            "sort_by":
                2
        }

        if next_review_token:

            params["next_page_token"] = (
                next_review_token
            )

        review_data = safe_request(
            params
        )

        if not review_data:
            break

        reviews = review_data.get(
            "reviews",
            []
        )

        if not reviews:
            break

        review_pages += 1

        for review in reviews:

            review_text = extract_review_text(
                review
            )

            if not review_text:

                skipped_reviews += 1

                continue

            row = hotel_details.copy()

            row.update({

                "review_text":
                    review_text,

                "individual_review_rating":
                    extract_review_rating(
                        review
                    ),

                "review_date":
                    review.get("date"),

                "review_source":
                    review.get("source")
            })

            all_new_rows.append(row)

            valid_reviews += 1

        next_review_token = (
            review_data
            .get(
                "serpapi_pagination",
                {}
            )
            .get(
                "next_page_token"
            )
        )

        if not next_review_token:
            break

        time.sleep(1)

    print(
        "Reviews with text:",
        valid_reviews
    )

    time.sleep(1)


# ============================================================
# 13. CREATE NEW DATAFRAME
# ============================================================

columns = [

    "hotel_name",
    "hotel_id",
    "city",
    "location",
    "price_per_night",
    "hotel_category",
    "customer_rating",
    "review_count",
    "amenities",
    "review_text",
    "individual_review_rating",
    "review_date",
    "review_source",
    "search_area"
]


new_df = pd.DataFrame(
    all_new_rows,
    columns=columns
)


# ============================================================
# 14. REMOVE EMPTY REVIEW TEXT
# ============================================================

if not new_df.empty:

    new_df = new_df[
        new_df["review_text"].notna()
        &
        new_df["review_text"]
        .astype(str)
        .str.strip()
        .ne("")
    ].copy()

    new_df.drop_duplicates(
        inplace=True
    )


# ============================================================
# 15. APPEND TO EXISTING DATASET
# ============================================================

if not existing_df.empty:

    combined_df = pd.concat(
        [
            existing_df,
            new_df
        ],
        ignore_index=True
    )

else:

    combined_df = new_df.copy()


# ============================================================
# 16. FINAL DEDUPLICATION
# ============================================================

# Remove exact duplicate rows
combined_df.drop_duplicates(
    inplace=True
)


# Remove duplicate hotel-review combinations
# if review_id is not available, hotel_id + review_text
# is used.

if (
    "hotel_id" in combined_df.columns
    and
    "review_text" in combined_df.columns
):

    combined_df.drop_duplicates(
        subset=[
            "hotel_id",
            "review_text"
        ],
        inplace=True
    )


# ============================================================
# 17. SAVE FINAL CSV
# ============================================================

combined_df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 18. FINAL SUMMARY
# ============================================================

final_unique_hotels = (
    combined_df["hotel_id"]
    .nunique()
    if not combined_df.empty
    else 0
)

print("\n")
print("============================================================")
print("FINAL SUMMARY")
print("============================================================")

print(
    "Existing unique hotels:",
    len(existing_hotel_ids)
)

print(
    "Additional hotels found:",
    len(new_hotels_by_id)
)

print(
    "Final unique hotels:",
    final_unique_hotels
)

print(
    "Final total rows:",
    len(combined_df)
)

print(
    "New review rows added:",
    len(new_df)
)

print(
    "Reviews skipped for empty text:",
    skipped_reviews
)

print(
    "CSV saved:",
    OUTPUT_FILE
)

print("============================================================")

display(
    combined_df.head(10)
)

Enter your SerpApi API key: ··········

Existing CSV found.
Existing rows: 1055
Existing unique hotels: 86

============================================================
SEARCHING FOR ADDITIONAL HOTELS
============================================================

Searching: Hotels in Central Hyderabad, Hyderabad
NEW HOTEL 1/100: Hotel Virat Inn
NEW HOTEL 2/100: Modern 2 BHK unit in the heart of Hyderabad city\n
NEW HOTEL 3/100: Hotel AA Grand
NEW HOTEL 4/100: ITC Kakatiya, a Luxury Collection Hotel, Hyderabad
NEW HOTEL 5/100: Hotel Savera Residency
NEW HOTEL 6/100: OYO Grandeur By orbit Hotels Near Chennai shopping mall
NEW HOTEL 7/100: Hotel Sitara Paradise - Ameerpet
NEW HOTEL 8/100: Taj Deccan, Hyderabad
NEW HOTEL 9/100: Via Log Inn
NEW HOTEL 10/100: Hotel Al Diyafa
NEW HOTEL 11/100: GOLDEN POINT HOTEL
NEW HOTEL 12/100: Hotel suncity
NEW HOTEL 13/100: Hotel Polo
NEW HOTEL 14/100: Metro City Hostel
NEW HOTEL 15/100: Hotel Sai Leela Residency
NEW HOTEL 16/100: SPOT ON Hotel Prince Residency
NEW HOTEL 17/100: SPOT ON 806901 Hotel Park9
NEW HOTEL 18/100: OYO Somajiguda
NEW HOTEL 19/100: OYO Flagship 78735 Hotel Virat Inn
New unique hotels collected so far: 19

Searching: Hotels in HITEC City, Hyderabad
NEW HOTEL 20/100: Deccan Serai Hotel, HITEC CITY, HYDERABAD
NEW HOTEL 21/100: Westside Hotel Hitech City
NEW HOTEL 22/100: iStay Hotels Hitec City Hyderabad
NEW HOTEL 23/100: Hotel White Fields Hitec City
NEW HOTEL 24/100: M Square Hotel
NEW HOTEL 25/100: ibis Hyderabad HITEC City
NEW HOTEL 26/100: Bloom Hotel - Cyber Towers
NEW HOTEL 27/100: Hotel Athome & Serviced Apartments By Deccan Serai Hotels
NEW HOTEL 28/100: Prowell Hotels Crown, HITEC City, Hyderabad
NEW HOTEL 29/100: SKYLA Serviced Suites, Hitech City, Hyderabad
NEW HOTEL 30/100: The Hosteller Hyderabad, HITEC City
NEW HOTEL 31/100: Sapphire Pearl
NEW HOTEL 32/100: Hotel B Plus L
NEW HOTEL 33/100: Lemon Tree Premier, HITEC City, Hyderabad
NEW HOTEL 34/100: Hotel Pearl City Jubilee
NEW HOTEL 35/100: Hotel 5 Elements
NEW HOTEL 36/100: Hotel KP Suites Hitex
NEW HOTEL 37/100: Vintage 3BHK Near Capital Park & Rameswaram-Cafe 101
NEW HOTEL 38/100: 3 Bed Room Hitech Shilparamam Guest House
NEW HOTEL 39/100: The #5 Story Hotel
NEW HOTEL 40/100: Holiday Inn Express Hyderabad Hitec City by IHG
NEW HOTEL 41/100: Treebo Sapphire Bliss
NEW HOTEL 42/100: Hitech Shilparamam Guest House
NEW HOTEL 43/100: Cloud9Homes Serviced Apartments, Hitech City, Hyderabad
NEW HOTEL 44/100: Holiday Inn Express Hyderabad Hitec City, an IHG Hotel
NEW HOTEL 45/100: The Westin Hyderabad Hitec City
NEW HOTEL 46/100: Regenta Place Hi-tech City, Hyderabad
NEW HOTEL 47/100: FabHotel Pride Inn - Hotel in Madhapur
NEW HOTEL 48/100: Hotel Kyzen - Hitech City Hyderabad
NEW HOTEL 49/100: FabHotel R3 Atmos
NEW HOTEL 50/100: Swan Suites
NEW HOTEL 51/100: Hotel Windsor Plaza
NEW HOTEL 52/100: Cloud5Studios
NEW HOTEL 53/100: Hotel Heaven75
NEW HOTEL 54/100: Hotel Athome & Serviced Apartments by Deccan Serai Hotels
NEW HOTEL 55/100: Hitech Shilparamam Guest House
NEW HOTEL 56/100: Novara Hotel Hitex
NEW HOTEL 57/100: Theo suites hotel
NEW HOTEL 58/100: Red Fox by Lemon Tree Hotels, Hyderabad
NEW HOTEL 59/100: OYO 12336 Hotel Rain Tree
NEW HOTEL 60/100: Boston Living
NEW HOTEL 61/100: Klyra Hotels
NEW HOTEL 62/100: FabHotel Prime Srishoin
NEW HOTEL 63/100: HOTEL V
NEW HOTEL 64/100: Hotel Tals Hitech
NEW HOTEL 65/100: FabHotel Prime Prowell Crown
NEW HOTEL 66/100: Townhouse Mindspace Road Gachibowli
NEW HOTEL 67/100: होटल ड्रीम नेस्ट
NEW HOTEL 68/100: Fresh Living Apartments
NEW HOTEL 69/100: HOTEL ABI RESIDENCY
NEW HOTEL 70/100: Hotel Legacy Grand
NEW HOTEL 71/100: Vintage 3BHK Near Capital Park & Rameswaram-Cafe 303
NEW HOTEL 72/100: Le Penguin Serviced Apartments
NEW HOTEL 73/100: Hotel Eminent Suites
NEW HOTEL 74/100: FabHotel Orion
NEW HOTEL 75/100: Oakline Hotels & Resorts
NEW HOTEL 76/100: Super Hotel O Madhapur VIP Hills
NEW HOTEL 77/100: OYO Athome Apartment Hotel
NEW HOTEL 78/100: Super Townhouse by OYO VIP Hills Hitech City
NEW HOTEL 79/100: Pride Inn
NEW HOTEL 80/100: Hotel O Dream Nest
NEW HOTEL 81/100: Twenty Three Urban Suites
NEW HOTEL 82/100: Urban Square Hotel
NEW HOTEL 83/100: New Prestige Hotel, Madhapur
NEW HOTEL 84/100: Treebo Trend Sapphire Hitech City
NEW HOTEL 85/100: Treebo D Consulate Fresh Living Apartments
NEW HOTEL 86/100: Newly Launched Luxury 3 BHK Near Sindhu Hospitals Hitex Exhibition Center TR - Three-Bedroom Apartment
NEW HOTEL 87/100: Le Penguin Serviced Apartments - Three-Bedroom Apartment
NEW HOTEL 88/100: Collection O Broholic Hotels 001
NEW HOTEL 89/100: OYO Townhouse 034 -Halcyon Hitech City Road
NEW HOTEL 90/100: 23 Urban Square Hotel
NEW HOTEL 91/100: OYO Apartment Near Hitech City Madhapur
NEW HOTEL 92/100: Hotel O SLN Gachibowli Formerly Laxmi Residency
NEW HOTEL 93/100: LA Hometel Hotel Hitech City Hyderabad
NEW HOTEL 94/100: FabExpress BB Suites
NEW HOTEL 95/100: Via Direct CheckIn
NEW HOTEL 96/100: Westside Studio & Apart Hotel
NEW HOTEL 97/100: The Westin Hyderabad Mindspace
NEW HOTEL 98/100: Super Collection O by OYO Madhapur
NEW HOTEL 99/100: OYO 75025 Cyber Heights Hotel
NEW HOTEL 100/100: Grand Continent Hotel, Hitec City, Hyderabad - Superior Double Room
New unique hotels collected so far: 100

============================================================
HOTEL SEARCH COMPLETE
============================================================
Existing unique hotels: 86
Additional unique hotels found: 100
Expected total unique hotels: 186

============================================================
FETCHING REVIEWS FOR NEW HOTELS
============================================================

[1/100] Hotel Virat Inn
Reviews with text: 16

[2/100] Modern 2 BHK unit in the heart of Hyderabad city\n
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[3/100] Hotel AA Grand
Reviews with text: 4

[4/100] ITC Kakatiya, a Luxury Collection Hotel, Hyderabad
Reviews with text: 15

[5/100] Hotel Savera Residency
Reviews with text: 12

[6/100] OYO Grandeur By orbit Hotels Near Chennai shopping mall
Reviews with text: 19

[7/100] Hotel Sitara Paradise - Ameerpet
Reviews with text: 22

[8/100] Taj Deccan, Hyderabad
Reviews with text: 10

[9/100] Via Log Inn
Reviews with text: 0

[10/100] Hotel Al Diyafa
Reviews with text: 17

[11/100] GOLDEN POINT HOTEL
Reviews with text: 0

[12/100] Hotel suncity
Reviews with text: 0

[13/100] Hotel Polo
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[14/100] Metro City Hostel
Reviews with text: 22

[15/100] Hotel Sai Leela Residency
Reviews with text: 4

[16/100] SPOT ON Hotel Prince Residency
Reviews with text: 7

[17/100] SPOT ON 806901 Hotel Park9
Reviews with text: 0

[18/100] OYO Somajiguda
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[19/100] OYO Flagship 78735 Hotel Virat Inn
Reviews with text: 0

[20/100] Deccan Serai Hotel, HITEC CITY, HYDERABAD
Reviews with text: 18

[21/100] Westside Hotel Hitech City
Reviews with text: 14

[22/100] iStay Hotels Hitec City Hyderabad
Reviews with text: 18

[23/100] Hotel White Fields Hitec City
Reviews with text: 18

[24/100] M Square Hotel
Reviews with text: 26

[25/100] ibis Hyderabad HITEC City
Reviews with text: 21

[26/100] Bloom Hotel - Cyber Towers
Reviews with text: 14

[27/100] Hotel Athome & Serviced Apartments By Deccan Serai Hotels
Reviews with text: 20

[28/100] Prowell Hotels Crown, HITEC City, Hyderabad
Reviews with text: 23

[29/100] SKYLA Serviced Suites, Hitech City, Hyderabad
Reviews with text: 20

[30/100] The Hosteller Hyderabad, HITEC City
Reviews with text: 23

[31/100] Sapphire Pearl
Reviews with text: 12

[32/100] Hotel B Plus L
Reviews with text: 22

[33/100] Lemon Tree Premier, HITEC City, Hyderabad
Reviews with text: 14

[34/100] Hotel Pearl City Jubilee
Reviews with text: 13

[35/100] Hotel 5 Elements
Reviews with text: 14

[36/100] Hotel KP Suites Hitex
Reviews with text: 16

[37/100] Vintage 3BHK Near Capital Park & Rameswaram-Cafe 101
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[38/100] 3 Bed Room Hitech Shilparamam Guest House
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[39/100] The #5 Story Hotel
Reviews with text: 17

[40/100] Holiday Inn Express Hyderabad Hitec City by IHG
Reviews with text: 23

[41/100] Treebo Sapphire Bliss
Reviews with text: 15

[42/100] Hitech Shilparamam Guest House
Reviews with text: 25

[43/100] Cloud9Homes Serviced Apartments, Hitech City, Hyderabad
Reviews with text: 16

[44/100] Holiday Inn Express Hyderabad Hitec City, an IHG Hotel
Reviews with text: 13

[45/100] The Westin Hyderabad Hitec City
Reviews with text: 7

[46/100] Regenta Place Hi-tech City, Hyderabad
Reviews with text: 19

[47/100] FabHotel Pride Inn - Hotel in Madhapur
Reviews with text: 22

[48/100] Hotel Kyzen - Hitech City Hyderabad
Reviews with text: 19

[49/100] FabHotel R3 Atmos
Reviews with text: 21

[50/100] Swan Suites
Reviews with text: 8

[51/100] Hotel Windsor Plaza
Reviews with text: 15

[52/100] Cloud5Studios
Reviews with text: 12

[53/100] Hotel Heaven75
Reviews with text: 26

[54/100] Hotel Athome & Serviced Apartments by Deccan Serai Hotels
Reviews with text: 7

[55/100] Hitech Shilparamam Guest House
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[56/100] Novara Hotel Hitex
Reviews with text: 12

[57/100] Theo suites hotel
Reviews with text: 15

[58/100] Red Fox by Lemon Tree Hotels, Hyderabad
Reviews with text: 15

[59/100] OYO 12336 Hotel Rain Tree
Reviews with text: 14

[60/100] Boston Living
Reviews with text: 12

[61/100] Klyra Hotels
Reviews with text: 17

[62/100] FabHotel Prime Srishoin
Reviews with text: 18

[63/100] HOTEL V
Reviews with text: 16

[64/100] Hotel Tals Hitech
Reviews with text: 14

[65/100] FabHotel Prime Prowell Crown
Reviews with text: 3

[66/100] Townhouse Mindspace Road Gachibowli
Reviews with text: 22

[67/100] होटल ड्रीम नेस्ट
Reviews with text: 22

[68/100] Fresh Living Apartments
Reviews with text: 6

[69/100] HOTEL ABI RESIDENCY
Reviews with text: 13

[70/100] Hotel Legacy Grand
Reviews with text: 18

[71/100] Vintage 3BHK Near Capital Park & Rameswaram-Cafe 303
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[72/100] Le Penguin Serviced Apartments
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[73/100] Hotel Eminent Suites
Reviews with text: 24

[74/100] FabHotel Orion
Reviews with text: 23

[75/100] Oakline Hotels & Resorts
Reviews with text: 22

[76/100] Super Hotel O Madhapur VIP Hills
Reviews with text: 19

[77/100] OYO Athome Apartment Hotel
Reviews with text: 12

[78/100] Super Townhouse by OYO VIP Hills Hitech City
Reviews with text: 23

[79/100] Pride Inn
Reviews with text: 11

[80/100] Hotel O Dream Nest
Reviews with text: 7

[81/100] Twenty Three Urban Suites
Reviews with text: 2

[82/100] Urban Square Hotel
Reviews with text: 19

[83/100] New Prestige Hotel, Madhapur
Reviews with text: 10

[84/100] Treebo Trend Sapphire Hitech City
Reviews with text: 3

[85/100] Treebo D Consulate Fresh Living Apartments
Reviews with text: 6

[86/100] Newly Launched Luxury 3 BHK Near Sindhu Hospitals Hitex Exhibition Center TR - Three-Bedroom Apartment
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[87/100] Le Penguin Serviced Apartments - Three-Bedroom Apartment
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[88/100] Collection O Broholic Hotels 001
Reviews with text: 16

[89/100] OYO Townhouse 034 -Halcyon Hitech City Road
Reviews with text: 11

[90/100] 23 Urban Square Hotel
Reviews with text: 4

[91/100] OYO Apartment Near Hitech City Madhapur
Reviews with text: 2

[92/100] Hotel O SLN Gachibowli Formerly Laxmi Residency
Reviews with text: 4

[93/100] LA Hometel Hotel Hitech City Hyderabad
Reviews with text: 18

[94/100] FabExpress BB Suites
Reviews with text: 4

[95/100] Via Direct CheckIn
Reviews with text: 20

[96/100] Westside Studio & Apart Hotel
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[97/100] The Westin Hyderabad Mindspace
Reviews with text: 12

[98/100] Super Collection O by OYO Madhapur
Reviews with text: 11

[99/100] OYO 75025 Cyber Heights Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0

[100/100] Grand Continent Hotel, Hitec City, Hyderabad - Superior Double Room
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0


============================================================
FINAL SUMMARY
============================================================
Existing unique hotels: 86
Additional hotels found: 100
Final unique hotels: 168
Final total rows: 2251
New review rows added: 1214
Reviews skipped for empty text: 941
CSV saved: hyderabad_hotel_dataset.csv
============================================================

,hotel_name,hotel_id,city,location,price_per_night,hotel_category,customer_rating,review_count,amenities,review_text,individual_review_rating,review_date,review_source,search_area
0,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Booked last minute after seeing some negative ...,5,2 weeks ago,Google,Central Hyderabad
1,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Begumpet,5,2 weeks ago,Google,Central Hyderabad
2,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Complete Disaster of a Stay. Avoid If You Valu...,1,a month ago,Google,Central Hyderabad
3,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Good,5,a month ago,Google,Central Hyderabad
4,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Food and acamidation good an quality hygnice s...,5,a month ago,Google,Central Hyderabad
5,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Well maintained room's and all good,5,a month ago,Google,Central Hyderabad
6,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Good location,5,a month ago,Google,Central Hyderabad
7,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,**Very Disappointing Experience – Not Recommen...,1,a month ago,Google,Central Hyderabad
8,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Very Disappointing Stay\nThe room had a very b...,1,a month ago,Google,Central Hyderabad
9,RCC Hotels Elite - Begumpet,ChkIwfHNgbqXvqtfGg0vZy8xMXJtcDNzMWcwEAE,Hyderabad,"Latitude: 17.4318882, Longitude: 78.4573388",1466.0,NaN,4.9,2337,Breakfast ($) | Free Wi-Fi | Free parking | Ai...,Very Worst Hotel – Not Recommended\nVery disap...,1,a month ago,Google,Central Hyderabad

In [ ]:
from google.colab import files

files.download("hyderabad_hotel_dataset.csv")

In [ ]:
import requests
import pandas as pd
import getpass
import time
import os


# ============================================================
# 1. CONFIGURATION
# ============================================================

API_KEY = getpass.getpass("Enter your SerpApi API key: ")

CITY = "Delhi"
STATE = "Delhi"
COUNTRY_CODE = "in"

# Google Hotels requires stay dates
CHECK_IN = "2026-10-15"
CHECK_OUT = "2026-10-16"

# IMPORTANT:
# We want 100 ADDITIONAL hotels
ADDITIONAL_HOTELS = 100

MAX_REVIEW_PAGES = 3

OUTPUT_FILE = "delhi_hotel_dataset.csv"

BASE_URL = "https://serpapi.com/search.json"


# ============================================================
# 2. SEARCH AREAS
# ============================================================

AREAS = [

    "Central Delhi",
    "Connaught Place",
    "Karol Bagh",
    "Paharganj",
    "Aerocity",
    "Dwarka",
    "Rohini",
    "Saket",
    "Hauz Khas",
    "Vasant Kunj",
    "Greater Kailash",
    "South Extension",
    "Lajpat Nagar",
    "Nehru Place",
    "Chanakyapuri",
    "Kashmere Gate",
    "Civil Lines",
    "Rajouri Garden",
    "Janakpuri",
    "Pitampura",
    "Mayur Vihar",
    "Okhla",
    "Green Park",
    "Defence Colony",
    "Jasola",
    "Mahipalpur",
    "Laxmi Nagar",
    "ITO",
    "Pusa Road",
    "New Friends Colony",

    # Additional areas for better coverage
    "Shahdara",
    "Preet Vihar",
    "Anand Vihar",
    "Karkardooma",
    "Vivek Vihar",
    "Patparganj",
    "East Delhi",
    "South Delhi",
    "North Delhi",
    "West Delhi",
    "Old Delhi",
    "Daryaganj",
    "Chandni Chowk",
    "Sadar Bazaar",
    "Jama Masjid",
    "Jangpura",
    "Kailash Colony",
    "Kalkaji",
    "CR Park",
    "Govindpuri",
    "Greater Kailash 1",
    "Greater Kailash 2",
    "Malviya Nagar",
    "Chirag Delhi",
    "Panchsheel Park",
    "Safdarjung Enclave",
    "Vasant Vihar",
    "R K Puram",
    "Munirka",
    "Ber Sarai",
    "Mehrauli",
    "Chhatarpur",
    "Sultanpur",
    "Aya Nagar",
    "Sarita Vihar",
    "Madanpur Khadar",
    "Kalindi Kunj",
    "Tughlakabad",
    "Jasola Vihar",
    "Govindpuri Extension",
    "Nangloi",
    "Uttam Nagar",
    "Tilak Nagar",
    "Subhash Nagar",
    "Tagore Garden",
    "Punjabi Bagh",
    "Paschim Vihar",
    "Rajendra Place",
    "Shadipur",
    "Patel Nagar",
    "Shalimar Bagh",
    "Model Town",
    "Kamla Nagar",
    "Mukherjee Nagar",
    "GTB Nagar",
    "Vijay Nagar",
    "Ashok Vihar",
    "Wazirpur",
    "Azadpur",
    "Kashmere Gate ISBT",
    "Indira Gandhi International Airport",
    "Delhi Airport",
    "Airport Road"
]


# ============================================================
# 3. LOAD EXISTING CSV
# ============================================================

if os.path.exists(OUTPUT_FILE):

    existing_df = pd.read_csv(OUTPUT_FILE)

    print("\nExisting Delhi CSV found.")
    print(
        "Existing rows:",
        len(existing_df)
    )

    if "hotel_id" in existing_df.columns:

        existing_hotel_ids = set(
            existing_df["hotel_id"]
            .dropna()
            .astype(str)
            .str.strip()
        )

    else:

        existing_hotel_ids = set()

else:

    print("\nNo existing Delhi CSV found.")

    existing_df = pd.DataFrame()

    existing_hotel_ids = set()


print(
    "Existing unique hotels:",
    len(existing_hotel_ids)
)


# ============================================================
# 4. SAFE API REQUEST
# ============================================================

def safe_request(params):

    params = params.copy()

    params["api_key"] = API_KEY

    try:

        response = requests.get(
            BASE_URL,
            params=params,
            timeout=60
        )

        if response.status_code != 200:

            print(
                "API error:",
                response.status_code
            )

            print(
                response.text[:300]
            )

            return {}

        data = response.json()

        if "error" in data:

            print(
                "API error:",
                data["error"]
            )

            return {}

        return data

    except requests.RequestException as e:

        print(
            "Request failed:",
            e
        )

        return {}


# ============================================================
# 5. EXTRACT PRICE
# ============================================================

def extract_price(hotel):

    rate = hotel.get(
        "rate_per_night",
        {}
    )

    if isinstance(rate, dict):

        return (

            rate.get("extracted_lowest")

            or rate.get(
                "extracted_before_taxes_fees"
            )

            or rate.get("lowest")

            or rate.get(
                "before_taxes_fees"
            )
        )

    return (
        rate
        if isinstance(
            rate,
            (int, float)
        )
        else None
    )


# ============================================================
# 6. EXTRACT AMENITIES
# ============================================================

def extract_amenities(hotel):

    amenities = hotel.get(
        "amenities",
        []
    )

    if isinstance(
        amenities,
        list
    ):

        names = []

        for item in amenities:

            if isinstance(
                item,
                dict
            ):

                name = (
                    item.get("name")
                    or
                    item.get("title")
                )

                if name:

                    names.append(
                        str(name)
                    )

            else:

                names.append(
                    str(item)
                )

        return " | ".join(names)

    return (
        str(amenities)
        if amenities
        else None
    )


# ============================================================
# 7. EXTRACT LOCATION
# ============================================================

def extract_location(hotel):

    address = hotel.get(
        "address"
    )

    if address:

        return address

    gps = hotel.get(
        "gps_coordinates",
        {}
    )

    if isinstance(
        gps,
        dict
    ):

        lat = gps.get(
            "latitude"
        )

        lon = gps.get(
            "longitude"
        )

        if (
            lat is not None
            and
            lon is not None
        ):

            return (
                f"Latitude: {lat}, "
                f"Longitude: {lon}"
            )

    return None


# ============================================================
# 8. EXTRACT REVIEW TEXT
# ============================================================

def extract_review_text(review):

    for key in (
        "snippet",
        "text"
    ):

        value = review.get(
            key
        )

        if (
            isinstance(
                value,
                str
            )
            and
            value.strip()
        ):

            return value.strip()

    return None


# ============================================================
# 9. EXTRACT REVIEW RATING
# ============================================================

def extract_review_rating(review):

    rating = review.get(
        "rating"
    )

    if isinstance(
        rating,
        dict
    ):

        return (
            rating.get("value")
            or
            rating.get("rating")
        )

    return rating


# ============================================================
# 10. CREATE HOTEL ROW
# ============================================================

def make_hotel_row(
    hotel,
    area
):

    return {

        "hotel_name":
            hotel.get("name"),

        "hotel_id":
            hotel.get(
                "property_token"
            ),

        "city":
            CITY,

        "location":
            extract_location(
                hotel
            ),

        "price_per_night":
            extract_price(
                hotel
            ),

        "hotel_category":
            hotel.get(
                "hotel_class"
            ),

        "customer_rating":
            hotel.get(
                "overall_rating"
            ),

        "review_count":
            hotel.get(
                "reviews"
            ),

        "amenities":
            extract_amenities(
                hotel
            ),

        "search_area":
            area
    }


# ============================================================
# 11. SEARCH FOR 100 NEW HOTELS
# ============================================================

new_hotels_by_id = {}

print("\n")
print("=" * 60)
print("SEARCHING FOR 100 ADDITIONAL DELHI HOTELS")
print("=" * 60)

for area in AREAS:

    # Stop once 100 NEW hotels are found
    if (
        len(new_hotels_by_id)
        >= ADDITIONAL_HOTELS
    ):

        break

    print(
        f"\nSearching: Hotels in "
        f"{area}, {CITY}"
    )

    next_page_token = None

    while (
        len(new_hotels_by_id)
        < ADDITIONAL_HOTELS
    ):

        params = {

            "engine":
                "google_hotels",

            "q":
                f"Hotels in {area}, {CITY}",

            "gl":
                COUNTRY_CODE,

            "hl":
                "en",

            "currency":
                "INR",

            "check_in_date":
                CHECK_IN,

            "check_out_date":
                CHECK_OUT,

            "adults":
                2
        }

        # Add pagination token
        if next_page_token:

            params[
                "next_page_token"
            ] = next_page_token

        data = safe_request(
            params
        )

        if not data:

            break

        properties = data.get(
            "properties",
            []
        )

        if not properties:

            break

        for hotel in properties:

            hotel_id = hotel.get(
                "property_token"
            )

            if not hotel_id:

                continue

            # ==================================================
            # VERY IMPORTANT:
            # SKIP HOTELS ALREADY IN EXISTING CSV
            # ==================================================

            if (
                str(hotel_id)
                in existing_hotel_ids
            ):

                continue

            # ==================================================
            # SKIP DUPLICATES FROM CURRENT SCRAPE
            # ==================================================

            if (
                hotel_id
                in new_hotels_by_id
            ):

                continue

            # ==================================================
            # ADD NEW HOTEL
            # ==================================================

            new_hotels_by_id[
                hotel_id
            ] = {

                **make_hotel_row(
                    hotel,
                    area
                ),

                "_raw_hotel":
                    hotel
            }

            print(
                f"NEW HOTEL "
                f"{len(new_hotels_by_id)}/"
                f"{ADDITIONAL_HOTELS}: "
                f"{hotel.get('name')}"
            )

            if (
                len(new_hotels_by_id)
                >= ADDITIONAL_HOTELS
            ):

                break

        # ======================================================
        # GET NEXT HOTEL SEARCH PAGE
        # ======================================================

        next_page_token = (

            data.get(
                "serpapi_pagination",
                {}
            ).get(
                "next_page_token"
            )
        )

        if not next_page_token:

            break

        time.sleep(1)

    print(
        "New unique hotels collected:",
        len(new_hotels_by_id)
    )


# ============================================================
# 12. HOTEL SEARCH SUMMARY
# ============================================================

print("\n")
print("=" * 60)
print("HOTEL SEARCH COMPLETE")
print("=" * 60)

print(
    "Existing unique hotels:",
    len(existing_hotel_ids)
)

print(
    "Additional unique hotels found:",
    len(new_hotels_by_id)
)

print(
    "Expected final unique hotels:",
    len(existing_hotel_ids)
    +
    len(new_hotels_by_id)
)


# ============================================================
# 13. FETCH REVIEWS FOR NEW HOTELS
# ============================================================

all_new_rows = []

skipped_reviews = 0

hotel_items = list(
    new_hotels_by_id.values()
)

print("\n")
print("=" * 60)
print("FETCHING REVIEWS FOR NEW HOTELS")
print("=" * 60)


for hotel_num, hotel_data in enumerate(
    hotel_items,
    start=1
):

    hotel = hotel_data[
        "_raw_hotel"
    ]

    hotel_id = hotel.get(
        "property_token"
    )

    print(
        f"\n[{hotel_num}/"
        f"{len(hotel_items)}] "
        f"{hotel.get('name')}"
    )

    hotel_details = {

        key: value

        for key, value
        in hotel_data.items()

        if key != "_raw_hotel"
    }

    next_review_token = None

    review_pages = 0

    valid_reviews = 0

    while (
        review_pages
        < MAX_REVIEW_PAGES
    ):

        params = {

            "engine":
                "google_hotels_reviews",

            "property_token":
                hotel_id,

            "hl":
                "en",

            # Most recent reviews
            "sort_by":
                2
        }

        if next_review_token:

            params[
                "next_page_token"
            ] = next_review_token

        review_data = safe_request(
            params
        )

        if not review_data:

            break

        reviews = review_data.get(
            "reviews",
            []
        )

        if not reviews:

            break

        review_pages += 1

        for review in reviews:

            review_text = (
                extract_review_text(
                    review
                )
            )

            if not review_text:

                skipped_reviews += 1

                continue

            row = hotel_details.copy()

            row.update({

                "review_text":
                    review_text,

                "individual_review_rating":
                    extract_review_rating(
                        review
                    ),

                "review_date":
                    review.get(
                        "date"
                    ),

                "review_source":
                    review.get(
                        "source"
                    )
            })

            all_new_rows.append(
                row
            )

            valid_reviews += 1

        # ======================================================
        # NEXT REVIEW PAGE
        # ======================================================

        next_review_token = (

            review_data.get(
                "serpapi_pagination",
                {}
            ).get(
                "next_page_token"
            )
        )

        if not next_review_token:

            break

        time.sleep(1)

    print(
        "Reviews with text:",
        valid_reviews
    )

    time.sleep(1)


# ============================================================
# 14. CREATE NEW DATAFRAME
# ============================================================

columns = [

    "hotel_name",
    "hotel_id",
    "city",
    "location",
    "price_per_night",
    "hotel_category",
    "customer_rating",
    "review_count",
    "amenities",
    "review_text",
    "individual_review_rating",
    "review_date",
    "review_source",
    "search_area"
]


new_df = pd.DataFrame(
    all_new_rows,
    columns=columns
)


# ============================================================
# 15. REMOVE EMPTY REVIEW TEXT
# ============================================================

if not new_df.empty:

    new_df = new_df[
        new_df[
            "review_text"
        ].notna()
        &
        new_df[
            "review_text"
        ]
        .astype(str)
        .str.strip()
        .ne("")
    ].copy()

    new_df.drop_duplicates(
        inplace=True
    )


# ============================================================
# 16. APPEND NEW DATA TO EXISTING CSV
# ============================================================

if not existing_df.empty:

    combined_df = pd.concat(
        [
            existing_df,
            new_df
        ],
        ignore_index=True
    )

else:

    combined_df = new_df.copy()


# ============================================================
# 17. FINAL DEDUPLICATION
# ============================================================

combined_df.drop_duplicates(
    inplace=True
)


# Remove duplicate hotel + review-text combinations
if (
    "hotel_id"
    in combined_df.columns
    and
    "review_text"
    in combined_df.columns
):

    combined_df.drop_duplicates(
        subset=[
            "hotel_id",
            "review_text"
        ],
        inplace=True
    )


# ============================================================
# 18. SAVE FINAL CSV
# ============================================================

combined_df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 19. FINAL SUMMARY
# ============================================================

final_unique_hotels = (

    combined_df[
        "hotel_id"
    ].nunique()

    if not combined_df.empty

    else 0
)


print("\n")
print("=" * 60)
print("FINAL SUMMARY")
print("=" * 60)

print(
    "Existing unique hotels:",
    len(existing_hotel_ids)
)

print(
    "Additional hotels found:",
    len(new_hotels_by_id)
)

print(
    "Final unique hotels:",
    final_unique_hotels
)

print(
    "Final total rows:",
    len(combined_df)
)

print(
    "New review rows added:",
    len(new_df)
)

print(
    "Reviews skipped for empty text:",
    skipped_reviews
)

print(
    "CSV saved:",
    OUTPUT_FILE
)

print("=" * 60)


display(
    combined_df.head(10)
)

Enter your SerpApi API key: ··········

Existing Delhi CSV found.
Existing rows: 1345
Existing unique hotels: 83


============================================================
SEARCHING FOR 100 ADDITIONAL DELHI HOTELS
============================================================

Searching: Hotels in Central Delhi, Delhi
NEW HOTEL 1/100: Entire 1BHK Penthouse with Private Terrace 4th Flr
NEW HOTEL 2/100: The Lalit New Delhi
NEW HOTEL 3/100: The Metropolitan Hotel & Spa
NEW HOTEL 4/100: Ahuja Residency Sunder Nagar
NEW HOTEL 5/100: Hotel Connaught Royale, Delhi
NEW HOTEL 6/100: Radisson Blu Marina Hotel, Delhi Connaught Place
NEW HOTEL 7/100: Hotel Emporio Dx Paharganj New Delhi
NEW HOTEL 8/100: Hotel Shivam international
NEW HOTEL 9/100: Homlee Heritage Flat with kitchen in Central Delhi
NEW HOTEL 10/100: Hotel All In Homes
NEW HOTEL 11/100: The Twenties Hotel Kamla Nagar
NEW HOTEL 12/100: Hotel Aman Continental Delhi
NEW HOTEL 13/100: BnBBuddy Executive Studio Apt in West Delhi 720
NEW HOTEL 14/100: Royale Avenue BnB
NEW HOTEL 15/100: Hotel O Delhi Continental
NEW HOTEL 16/100: Nina Kochhar's Homestay - Deluxe Double Room
NEW HOTEL 17/100: Hotel Ruhaan - Delhi
NEW HOTEL 18/100: Hotel Dream Palace @ New Delhi Railway Station
NEW HOTEL 19/100: VacationBuddy Superb Furnished Studio Apartment 720 in West Delhi
NEW HOTEL 20/100: Hotel Prince Palace Deluxe
NEW HOTEL 21/100: Heritage Home
NEW HOTEL 22/100: Hotel Shelton
NEW HOTEL 23/100: Sweet Home Lodge delhi
NEW HOTEL 24/100: Hotel Karlo kastle @ Paharganj
NEW HOTEL 25/100: Hotel Ashoka Continental
NEW HOTEL 26/100: OYO Townhouse 838 Hotel Allure
NEW HOTEL 27/100: GAURANGA
NEW HOTEL 28/100: OYO Kamla Nagar
NEW HOTEL 29/100: Hotel Blue Bell
NEW HOTEL 30/100: Hotel Amar International
NEW HOTEL 31/100: Hotel Delhi Regency
NEW HOTEL 32/100: 3-bedroom bed & breakfast in amazing Delhi with AC near big park and good air
NEW HOTEL 33/100: Lavish Studio Apt in West /Central Delhi
NEW HOTEL 34/100: romantic
NEW HOTEL 35/100: Charming apartment in fabulous New Delhi with AC with rooftop area and a open
NEW HOTEL 36/100: Hotel Aiwan E Shahi
NEW HOTEL 37/100: Rams Inn
NEW HOTEL 38/100: Hotel Red stone inn New Delhi
NEW HOTEL 39/100: Hotel Nirmal Mahal
NEW HOTEL 40/100: Hotel vanson delite
NEW HOTEL 41/100: The Gold Inn
NEW HOTEL 42/100: Hotel Shanti Plaza
NEW HOTEL 43/100: FabExpress Silver Stone
NEW HOTEL 44/100: Sham Nath Villa
NEW HOTEL 45/100: Executive Studio Apt in DLF Midtown West Delhi
NEW HOTEL 46/100: Charming bed & breakfast in perfect New Delhi with WiFi, AC
NEW HOTEL 47/100: 3 Bedroom apartment in central Delhi Close to all major attractions
NEW HOTEL 48/100: Avyam Blue Terrace Apartment in New Delhi! Room-1 (Deluxe)
NEW HOTEL 49/100: Hotel De Romana
NEW HOTEL 50/100: ANMOL ROOMS
NEW HOTEL 51/100: Hotel Shiva Intercontinental
NEW HOTEL 52/100: Mahesh Guest House
NEW HOTEL 53/100: The Comfort Inn
NEW HOTEL 54/100: Hotel Sai Miracle
NEW HOTEL 55/100: Hotel Sonic Palace
NEW HOTEL 56/100: Hotel O Shyam Palace DX
NEW HOTEL 57/100: Homlee-Vintage 2BHK-Fort View-Bharat Mandapam-NDLS
NEW HOTEL 58/100: Vishal Hotel
NEW HOTEL 59/100: OYO Hotel Silver Palace
NEW HOTEL 60/100: Yes Boss By Backpackers Heaven
NEW HOTEL 61/100: Homlee-Value 1 BR-Central Delhi-terrace-view-lift
NEW HOTEL 62/100: Collection O Iconic Residency
NEW HOTEL 63/100: Hotel Sai International
NEW HOTEL 64/100: La Sagrita
NEW HOTEL 65/100: Breezy Rooftop Retreat - One-Bedroom Apartment
NEW HOTEL 66/100: Breezy Rooftop Retreat , Centrally located !
NEW HOTEL 67/100: Petite Homestays - Family Suite
NEW HOTEL 68/100: Hotel Raj Mahal inn
NEW HOTEL 69/100: Homlee-Vintage 2BHK-NDLS-Lift-Bharat Mandapam
NEW HOTEL 70/100: Hotel Apple Villa @ Paharganj
NEW HOTEL 71/100: बिश्नोई भवन
NEW HOTEL 72/100: Hotel O by OYO Karol Bagh Residency 1
NEW HOTEL 73/100: Indo continental
NEW HOTEL 74/100: Treebo Sisley The Boutique
NEW HOTEL 75/100: Rooftop Floor with a big Room
NEW HOTEL 76/100: OYO Capital O 664 Hotel Tourist
NEW HOTEL 77/100: Hotel Maharaja Continental
NEW HOTEL 78/100: Hotel Taj Mahal
NEW HOTEL 79/100: Hotel Awesome International
NEW HOTEL 80/100: Transit POD Stay – New Delhi | Airport Transit
NEW HOTEL 81/100: Kandh Brothers Homes
NEW HOTEL 82/100: Shree Delhi Gujarati Samaj
NEW HOTEL 83/100: Via Aura Palace
NEW HOTEL 84/100: Hotel O by OYO Raas Near Hira Sweet
NEW HOTEL 85/100: OYO 73548 Hotel Sunrise Dx
NEW HOTEL 86/100: Hotel Prem Deluxe
NEW HOTEL 87/100: Hotel Star International, New Delhi
NEW HOTEL 88/100: Hotel I Stay
NEW HOTEL 89/100: Hotel Satyam
NEW HOTEL 90/100: Mem International, A Family Hotel
NEW HOTEL 91/100: sunshine Palace
NEW HOTEL 92/100: Hotel O by OYO Amora Inn
NEW HOTEL 93/100: Hotel Singh Sahib
NEW HOTEL 94/100: Hotel O King Palace
NEW HOTEL 95/100: New Peace House
NEW HOTEL 96/100: cozy inn hostel
NEW HOTEL 97/100: Cottage Yes Sir Dx
NEW HOTEL 98/100: Nav Durga Guest House
NEW HOTEL 99/100: The Metrostay POD Hotel
NEW HOTEL 100/100: OYO Hotel Grand Neelam Near Jama Masjid
New unique hotels collected: 100


============================================================
HOTEL SEARCH COMPLETE
============================================================
Existing unique hotels: 83
Additional unique hotels found: 100
Expected final unique hotels: 183


============================================================
FETCHING REVIEWS FOR NEW HOTELS
============================================================

[1/100] Entire 1BHK Penthouse with Private Terrace 4th Flr
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[2/100] The Lalit New Delhi
Reviews with text: 8

[3/100] The Metropolitan Hotel & Spa
Reviews with text: 17

[4/100] Ahuja Residency Sunder Nagar
Reviews with text: 26

[5/100] Hotel Connaught Royale, Delhi
Reviews with text: 24

[6/100] Radisson Blu Marina Hotel, Delhi Connaught Place
Reviews with text: 14

[7/100] Hotel Emporio Dx Paharganj New Delhi
Reviews with text: 25

[8/100] Hotel Shivam international
Reviews with text: 20

[9/100] Homlee Heritage Flat with kitchen in Central Delhi
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[10/100] Hotel All In Homes
Reviews with text: 26

[11/100] The Twenties Hotel Kamla Nagar
Reviews with text: 16

[12/100] Hotel Aman Continental Delhi
Reviews with text: 14

[13/100] BnBBuddy Executive Studio Apt in West Delhi 720
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[14/100] Royale Avenue BnB
Reviews with text: 14

[15/100] Hotel O Delhi Continental
Reviews with text: 17

[16/100] Nina Kochhar's Homestay - Deluxe Double Room
Reviews with text: 1

[17/100] Hotel Ruhaan - Delhi
Reviews with text: 17

[18/100] Hotel Dream Palace @ New Delhi Railway Station
Reviews with text: 19

[19/100] VacationBuddy Superb Furnished Studio Apartment 720 in West Delhi
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[20/100] Hotel Prince Palace Deluxe
Reviews with text: 22

[21/100] Heritage Home
Reviews with text: 27

[22/100] Hotel Shelton
Reviews with text: 19

[23/100] Sweet Home Lodge delhi
Reviews with text: 17

[24/100] Hotel Karlo kastle @ Paharganj
Reviews with text: 23

[25/100] Hotel Ashoka Continental
Reviews with text: 17

[26/100] OYO Townhouse 838 Hotel Allure
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[27/100] GAURANGA
Reviews with text: 26

[28/100] OYO Kamla Nagar
Reviews with text: 11

[29/100] Hotel Blue Bell
Reviews with text: 11

[30/100] Hotel Amar International
Reviews with text: 20

[31/100] Hotel Delhi Regency
Reviews with text: 18

[32/100] 3-bedroom bed & breakfast in amazing Delhi with AC near big park and good air
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[33/100] Lavish Studio Apt in West /Central Delhi
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[34/100] romantic
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[35/100] Charming apartment in fabulous New Delhi with AC with rooftop area and a open
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[36/100] Hotel Aiwan E Shahi
Reviews with text: 19

[37/100] Rams Inn
Reviews with text: 19

[38/100] Hotel Red stone inn New Delhi
Reviews with text: 23

[39/100] Hotel Nirmal Mahal
Reviews with text: 14

[40/100] Hotel vanson delite
Reviews with text: 17

[41/100] The Gold Inn
Reviews with text: 20

[42/100] Hotel Shanti Plaza
Reviews with text: 19

[43/100] FabExpress Silver Stone
Reviews with text: 16

[44/100] Sham Nath Villa
Reviews with text: 19

[45/100] Executive Studio Apt in DLF Midtown West Delhi
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[46/100] Charming bed & breakfast in perfect New Delhi with WiFi, AC
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[47/100] 3 Bedroom apartment in central Delhi Close to all major attractions
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[48/100] Avyam Blue Terrace Apartment in New Delhi! Room-1 (Deluxe)
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[49/100] Hotel De Romana
Reviews with text: 24

[50/100] ANMOL ROOMS
Reviews with text: 0

[51/100] Hotel Shiva Intercontinental
Reviews with text: 19

[52/100] Mahesh Guest House
Reviews with text: 21

[53/100] The Comfort Inn
Reviews with text: 10

[54/100] Hotel Sai Miracle
Reviews with text: 20

[55/100] Hotel Sonic Palace
Reviews with text: 13

[56/100] Hotel O Shyam Palace DX
Reviews with text: 14

[57/100] Homlee-Vintage 2BHK-Fort View-Bharat Mandapam-NDLS
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[58/100] Vishal Hotel
Reviews with text: 17

[59/100] OYO Hotel Silver Palace
Reviews with text: 5

[60/100] Yes Boss By Backpackers Heaven
Reviews with text: 20

[61/100] Homlee-Value 1 BR-Central Delhi-terrace-view-lift
Reviews with text: 1

[62/100] Collection O Iconic Residency
Reviews with text: 15

[63/100] Hotel Sai International
Reviews with text: 18

[64/100] La Sagrita
Reviews with text: 17

[65/100] Breezy Rooftop Retreat - One-Bedroom Apartment
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[66/100] Breezy Rooftop Retreat , Centrally located !
Reviews with text: 1

[67/100] Petite Homestays - Family Suite
Reviews with text: 2

[68/100] Hotel Raj Mahal inn
Reviews with text: 25

[69/100] Homlee-Vintage 2BHK-NDLS-Lift-Bharat Mandapam
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[70/100] Hotel Apple Villa @ Paharganj
Reviews with text: 20

[71/100] बिश्नोई भवन
Reviews with text: 16

[72/100] Hotel O by OYO Karol Bagh Residency 1
Reviews with text: 23

[73/100] Indo continental
Reviews with text: 6

[74/100] Treebo Sisley The Boutique
Reviews with text: 0

[75/100] Rooftop Floor with a big Room
API error: Google Hotels hasn't returned any results for this query.
Reviews with text: 0

[76/100] OYO Capital O 664 Hotel Tourist
Reviews with text: 15

[77/100] Hotel Maharaja Continental
Reviews with text: 22

[78/100] Hotel Taj Mahal
Reviews with text: 14

[79/100] Hotel Awesome International
Reviews with text: 18

[80/100] Transit POD Stay – New Delhi | Airport Transit
Reviews with text: 12

[81/100] Kandh Brothers Homes
Reviews with text: 19

[82/100] Shree Delhi Gujarati Samaj
Reviews with text: 10

[83/100] Via Aura Palace
Reviews with text: 3

[84/100] Hotel O by OYO Raas Near Hira Sweet
Reviews with text: 21

[85/100] OYO 73548 Hotel Sunrise Dx
Reviews with text: 17

[86/100] Hotel Prem Deluxe
Reviews with text: 20

[87/100] Hotel Star International, New Delhi
Reviews with text: 18

[88/100] Hotel I Stay
Reviews with text: 6

[89/100] Hotel Satyam
Reviews with text: 18

[90/100] Mem International, A Family Hotel
Reviews with text: 23

[91/100] sunshine Palace
Reviews with text: 9

[92/100] Hotel O by OYO Amora Inn
Reviews with text: 20

[93/100] Hotel Singh Sahib
Reviews with text: 17

[94/100] Hotel O King Palace
Reviews with text: 3

[95/100] New Peace House
Reviews with text: 10

[96/100] cozy inn hostel
Reviews with text: 29

[97/100] Cottage Yes Sir Dx
Reviews with text: 20

[98/100] Nav Durga Guest House
Reviews with text: 17

[99/100] The Metrostay POD Hotel
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 5

[100/100] OYO Hotel Grand Neelam Near Jama Masjid
API error: 429
{
  "error": "Your account has run out of searches."
}
Reviews with text: 0


============================================================
FINAL SUMMARY
============================================================
Existing unique hotels: 83
Additional hotels found: 100
Final unique hotels: 163
Final total rows: 2608
New review rows added: 1295
Reviews skipped for empty text: 855
CSV saved: delhi_hotel_dataset.csv
============================================================

,hotel_name,hotel_id,city,location,price_per_night,hotel_category,customer_rating,review_count,amenities,review_text,individual_review_rating,review_date,review_source,search_area
0,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,I wouldn't recommend the most basic and cheape...,4.0,a week ago,Google,Central Delhi
1,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,very beautiful! peaceful! and maahi is super s...,5.0,2 weeks ago,Google,Central Delhi
2,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,Ranju is very good staff and help phul men,5.0,2 weeks ago,Google,Central Delhi
3,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,"This hotel is definitely not as described, the...",1.0,a month ago,Tripadvisor,Central Delhi
4,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,(Translated by Google) A wonderful place in th...,5.0,Edited a month ago,Google,Central Delhi
5,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,(Translated by Google) My experience at Jyoti ...,5.0,a month ago,Google,Central Delhi
6,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,"(Translated by Google) Average hotel, the best...",5.0,a month ago,Google,Central Delhi
7,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,The location felt unsafe and was not a place w...,3.0,a month ago,Google,Central Delhi
8,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,Good experience,5.0,2 months ago,Google,Central Delhi
9,Jyoti Mahal A Royal Heritage Hotel -Close to C...,ChgIuvLVx_qd7vgwGgwvZy8xcHR3aDhnbTIQAQ,Delhi,"Latitude: 28.642041, Longitude: 77.2117176",4480.0,3-star hotel,3.7,1548.0,Free breakfast | Free Wi-Fi | Free parking | A...,I really liked how they have presented their h...,5.0,2 months ago,Google,Central Delhi

In [ ]:
from google.colab import files

files.download("delhi_hotel_dataset.csv")